### ISSUE TITLE
UglifyJS breakage

### ISSUE THREAD

**Issue by troutowicz** [goatslacker/alt#100]
Just mentioning this here in case anyone else runs into the same issue.

I use webpack's UglifyJS plugin for one of my projects. Recently, I decided to use alt's bootstrap ability to pass some server side data to the client. This works great without UglifyJS, but when using UglifyJS with the mangle option, alt's `rollback`, `recycle`, and `bootstrap` methods will break. These methods call `setAppState`, which tries to find the keys of the passed in data object inside the current alt instances stores object. The stores object will contain mangled store names, whereas the data object will contain the correct store names.

I resolved this by telling UglifyJS to not touch the names of my alt store class names.

```javascript
new Webpack.optimize.UglifyJsPlugin({ mangle: { except: ['AppStore'] } })
```

**Comment by goatslacker** [comment]
Did you not give your stores any names?

**Comment by goatslacker** [comment]
This is the purpose of this warning: https://github.com/goatslacker/alt/blob/master/src/alt.js#L360

**Comment by troutowicz** [comment]
Yeah, it was given the name **AppStore**. But UglifyJS will mangle that and give it some random name like **t**. Then when you do something like:
```javascript
alt.bootstrap({
  altStores: {
    AppStore: {
      foo: bar 
    }
  }
});
```
`setAppState()` will fail during `forEach` when looking for a store named **AppState** which has since been mangled to **t**.

**Comment by goatslacker** [comment]
when you create your stores:

```js
alt.createStore(AppStore, 'AppStore');
```

the second key ensures your `AppStore` will retain that ref.

**Comment by troutowicz** [comment]
Thanks @goatslacker, didn't realize that key existed. :+1:
