### ISSUE TITLE
Webpack build warning

### ISSUE THREAD

**Issue by Blystad** [goatslacker/alt#11]
Hey,

I just started using webpack, and it spits out this warning when building:

>WARNING in ./~/alt/dist/alt.js
>Critical dependencies:
>3:434-441 This seem to be a pre-built javascript file. Even while this is possible, it's not recommended. Try to require to orginal source to get better results.
> @ ./~/alt/dist/alt.js 3:434-441

Not sure if it is a webpack issue, or an `alt` issue. I havn't noticed any problems so far, but since it's the only warninig it would be nice to get it fixed :smile:

**Comment by goatslacker** [comment]
What version of alt are you running?

**Comment by Blystad** [comment]
I was using 0.10.2. Updating to latest fixed the issue.
