### ISSUE TITLE
Encapsulate an alt instance  inside of a outer child.

### ISSUE THREAD

**Issue by daannijkamp** [goatslacker/alt#118]
Is there anything against the idea of to encapsulate an alt instance inside of a outer child?
The Weather Tab has a parent (App.jsx) that has a child (WeatherTab.jsx). 
(Parent + alt --> Child + alt )
I want to have inside the child another child that also works like a mini app.  
(Parent + alt --> Child + alt --> Child + alt )

I'm making the following:
A Dashboard that has multiple (Widget Groups) tabs. Inside a widget group tab there are multiple widgets for data visualization.

**Comment by alvinsng** [comment]
Hey @daannijkamp 

I would not recommend having 2 levels deep in alts. Alts do not support child alts. AltManager is a wrapper for alts so if you need 2 levels deep then it is best to just use the key name spacing.

So altManager.get('widget1-tab3') and fetch all tabs by going altManager.findWhere(/widget1-/)

However, ideally an alt is all you need for each widget. Each tab is a store inside that alt.

**Comment by daannijkamp** [comment]
Thank you for your response! Ideally I also want an alt with each tab as a store. But the dashboard is dynamically generated and different for each user. Basically there are no standard "widget groups" and widgets. 

Any ideas how I can achieve this with a single alt? My current solution is half flux for laying out the tabs/widget groups and the parent widget components  + Ajax calls inside the widget components for rendering the (complex) widgets elements.

**Comment by goatslacker** [comment]
Btw it's totally possible to have a parent Alt deal with children alt:

```js
// pseudo-code.

alt.createStore({
  displayName: 'AltStore',

  state: { alts: {} },

  bindListeners: {
    addNewAlt: Actions.addNewAlt
  },

  addNewAlt({ id, alt }) {
    this.state.alts[id] = alt;
  }
});
```

**Comment by special-character** [comment]
In the example above, would it be possible to have the parent wait for some store in each of the alt instances to complete before moving on? I am currently using alt instances and realized the parent instance can't directly waitFor the child instances because each has their own dispatcher.
