### ISSUE TITLE
Why don't we have setState in public methods?

### ISSUE THREAD

**Issue by quangbuule** [goatslacker/alt#119]
@goatslacker, is `setState()` method a bad idea when calling in public methods?

**Comment by troutowicz** [comment]
flux uses a unidirectional data flow.

view fires action -> dispatcher fires action callback -> store updates state -> view gets new state

Using `setState()` in public methods (in a view) would go against that flow.

**Comment by goatslacker** [comment]
One of the core principles of flux is that stores have no direct setter methods.
