### ISSUE TITLE
Chat example not running

### ISSUE THREAD

**Issue by behl1** [goatslacker/alt#12]
WARN: Dropping unused function argument exports [-:1,437]
WARN: Dropping unused function argument module [-:1,430]

I get like a 100 of these warnings when I run the command "npm run build" (obviously I run this only after installing the dependencies) for the chat example. Have any idea of what's going wrong?

**Comment by codekirei** [comment]
Pretty sure that's just [uglifyjs's compressor](https://github.com/mishoo/UglifyJS2#compressor-options) doing its thing.

If you remove compression from the build command, the warnings go away  (`-m` instead of `-cm` ):

```javascript
//before
"build": "NODE_ENV=production ./node_modules/browserify/bin/cmd.js -t esnext . | uglifyjs -cm > js/bundle.min.js",

//after
"build": "NODE_ENV=production ./node_modules/browserify/bin/cmd.js -t esnext . | uglifyjs -m > js/bundle.min.js",
```

**Comment by behl1** [comment]
Thanks. It does get minified, but gives me js error when I open index.html:

Uncaught TypeError: object is not a function   bundle.min.js:144 
6.../../../    bundle.min.js:1 
s     bundle.min.js:1 
(anonymous function)    bundle.min.js:84 
3.../alt   bundle.min.js:1  
s   bundle.min.js:1 
(anonymous function)   bundle.min.js:226 
9.../actions/ChatMessageActionCreators    bundle.min.js:1 
s    bundle.min.js:1 
(anonymous function)    bundle.min.js:324 
11.../stores/MessageStore    bundle.min.js:1 
s    bundle.min.js:1 
(anonymous function)   bundle.min.js:192 
8../MessageSection.react    bundle.min.js:1 
s  bundle.min.js:1 
(anonymous function)   bundle.min.js:163 
7../ChatExampleData   bundle.min.js:1 
s  bundle.min.js:1 
e   bundle.min.js:1 
(anonymous function)

**Comment by goatslacker** [comment]
Oh weird, I just opened it and didn't get an error. Try removing the minification part in package.json and opening the file.

Also what browser are you using?

**Comment by behl1** [comment]
I am using chrome, but thanks. The problem resolved itself when I removed the minification part. Very weird as I have never encountered any problem before with uglify.
