### ISSUE TITLE
example gets this.todos

### ISSUE THREAD

**Issue by continuata** [goatslacker/alt#120]
I'm confused by your Store example; it is supposed to demonstrate how to update the `todos` object on the Store class. But as far as I can tell `this.setState({ todos })` doesn't set the `todos` object directly on the Store, as it can only be seen with `this.getState()` ... so `this.todos` is empty.

Also in your code you have 

    const { todos } = this.todos

... which is the equivalent of

    var todos = this.todos.todos

Am I missing something here? Or were you intending to write `const { todos } = this.getState()` for the getter methods?

**Comment by continuata** [comment]
Oh I think I figured it out ....

Public methods have restricted access to the class, so you need to use `this.getState()` in those, but bound listeners have direct access to the class.

Although, that still doesn't explain the `const { todos} = this.todos` line.

**Comment by goatslacker** [comment]
Good catch. Mind submitting a PR? It should be const todos = this.todos

**Comment by goatslacker** [comment]
Are you still confused by setState?

**Comment by continuata** [comment]
done ... and no, not confused any more with setState. Thanks :-)

**Comment by goatslacker** [comment]
FYI TodoStore can be written like:

```js
  updateTodo({ id, text }) {
    this.todos[id] = this.todos[id] || {};
    this.todos[id].text = text;
  }
```

**Comment by continuata** [comment]
thanks ... that's really helpful
