### ISSUE TITLE
Where in production?

### ISSUE THREAD

**Issue by razagill** [goatslacker/alt#123]
Hey guys,
I'm looking for flux implementations and `alt` seems like a very good minimal approach with a lot less magic. Just wanted to ask around the community that how many of you are using `alt` in production and what has been your experience with it?

**Comment by troutowicz** [comment]
Take a look at issue #8. So far alt has worked really well for my personal projects. 

>  alt  seems like a very good minimal approach with a lot less magic

alt has its share of magic ;) What alt does do have is less boilerplate.

**Comment by goatslacker** [comment]
Airbnb uses alt in production on airbnb.com for some key components on the site.

We're also using it on [airpal](https://github.com/airbnb/airpal/tree/master/src/main/resources/assets) which is an internal tool we use to query large data sets. + we're using alt on various internal tools and internal large applications.

**Comment by razagill** [comment]
Thanks for references guys, helped a lot.
