### ISSUE TITLE
this.dispatch not being called

### ISSUE THREAD

**Issue by razagill** [goatslacker/alt#124]
Hey guys,
I'm trying to integrate alt in an existing application. I've setup the store like below:
```
import alt from '../alt.js';
import SessionActions from '../actions/SessionActions.js';
class SessionStore {
  constructor() {
    this.bindListeners({
      onTest: SessionActions.DO_LOGIN_PHONE
    });
  }
  onTest(data) {
    console.log('test');
  }
}
export default alt.createStore(SessionStore, 'SessionStore');
```
And the SessionActions is as below:

```
import alt from '../alt.js';
class SessionActions {

  doLoginPhone(phone) {
    this.dispatch(phone);
  }
}
export default alt.createActions(SessionActions);
```
And here is the react component calling the SessionActions:

```
import React from 'react';
import SessionActions from '../../../actions/SessionActions.js';
var LoginPhone = React.createClass({

  _onSubmit: function(e) {
    e.preventDefault();
    let phone = this.refs.phone.getDOMNode().value;
    SessionActions.doLoginPhone(phone);
  },
  render: function() {
    return (
      <div>
        <form onSubmit={this._onSubmit}>
          <div className="form-group">
            <input type="tel" ref="phone" className="form-control" id="phoneNumber" placeholder="Enter Phone"/>
          </div>
          <br/>
            <button type="submit" className="btn btn-success col-xs-12">Send Phone</button>
        </form>
      </div>
    );
  }
});
module.exports = LoginPhone;
```
But onTest is never being called. This is so simple I might just be missing something really fundamental here. Any ideas?

**Comment by goatslacker** [comment]
Without any other context that looks fine. Is `doLoginPhone` even being called?

btw you can get support on [gitter](https://gitter.im/goatslacker/alt).

**Comment by razagill** [comment]
Yes checked and `doLoginPhone` is being called. I'll move this to gitter instead.

**Comment by ppiekarczyk** [comment]
@razagill I'm having the same issue, did you fix this?

**Comment by razagill** [comment]
Hi @ppiekarczyk , As far as I remember, in my case it was a very simple problem. I wasn't including `SessionStore` anywhere in my application so it wasn't there after webpack was done bundling, hence no listener on the `SessionAction`. If that's not your issue, just post the code and we can have a look.

**Comment by ppiekarczyk** [comment]
You were right @razagill ! Thank you for following up!
