### ISSUE TITLE
schizophrenic stores

### ISSUE THREAD

**Issue by pekeler** [goatslacker/alt#126]
I know a bunch has been written about this already, but I still wonder if the api for stores could be more straightforward where I don't have to think for every store method whether the context (this) is my Store or an AltStore with one requiring the use of getState() and the other having direct access to the state.

Specifically, what just annoyed me about this: I want a helper method on my store to search for and return a specific item in the store's state. This method is used both internally by one of the store's action handlers, and also externally by a component. I end up having to implement two versions of this helper method, one using getState() the other without.

Or am I doing this all wrong? :)

**Comment by goatslacker** [comment]
```js
const FooStore = alt.createStore({
  state: { hello: 123 },

  publicMethods: {
    getHello() {
      return this.getState().hello;
    }
  },

  internalDoSomethingWithHello() {
    const hello = this.getInstance().getHello();
  }
});
```

or if you're feeling classy...

```js
class FooStore {
  constructor() {
    this.hello = 123

    this.exportPublicMethods({
      getHelloAlsoWorks: this.getHelloAlsoWorks.bind(this),

      getHello() {
        return this.getState().hello
      }
    })

    internalDoSomethingWithHello() {
      const hello = this.getInstance().getHello();
    }

    getHelloAlsoWorks() {
      return this.hello;
    }
  }
 }
```

**Comment by pekeler** [comment]
Ah, so either publicMethod.bind(this) so it works internally and externally without needing to call getState(), or use getInstance() when calling a public method internally. I think I prefer the former. Thanks @goatslacker!
