### ISSUE TITLE
site navbar is not responsive

### ISSUE THREAD

**Issue by jdlehman** [goatslacker/alt#128]
- the navbar is a fixed width and causes the site to not look great on mobile
![alt](https://cloud.githubusercontent.com/assets/3144695/6977258/f52faa02-d987-11e4-997f-919bfa40cfae.png)

**Comment by goatslacker** [comment]
Ah yes, it's been on my mental todo list. I'm thinking we can just use the css classes the framework provides to target a smaller nav bar, or media queries?

**Comment by jdlehman** [comment]
Haha same, I just wanted to put it here so we don't forget.

**Comment by jdlehman** [comment]
Solved with: https://github.com/goatslacker/alt/pull/131
