### ISSUE TITLE
Provide a way to load a Snapshot

### ISSUE THREAD

**Issue by mfunkie** [goatslacker/alt#129]
Taking a snapshot is a great idea for logging State, but it would be very nice in regards to QA.

The idea would be to expose a way for a QA to take a snapshot the moment before an interaction reproduces a bug, and then the QA could provide that snapshot to a developer who could then load the snapshot and easily reproduce a bug.

**Comment by jdlehman** [comment]
Hey @mfunkie, you can already do this!

See the [bootstrap](https://github.com/goatslacker/alt/blob/master/docs/bootstrap.md#bootstrap) docs.

Essentially you can do something like this:

```js
var snapshot = alt.takeSnapshot();
alt.bootstrap(snapshot);
```

**Comment by mfunkie** [comment]
Thank you! Sorry I missed it, I was looking for a 'loadSnapshot' type function.

**Comment by jdlehman** [comment]
If you want to get fancy you can do something like this (which might suit your actual use case):

This makes use of [beforeEach](https://github.com/goatslacker/alt/blob/master/docs/createStore.md#storemodelbeforeeach) and [afterEach](https://github.com/goatslacker/alt/blob/master/docs/createStore.md#storemodelaftereach).

```js
var lastSnapshot;

class MyStore {
   constructor() {
      this.error = false;
   }

  beforeEach(action, payload, state) {
    lastSnapshot = alt.takeSnapshot();
  }

  afterEach(action, payload, state) {
    if(state.error) {
      alt.bootstrap(lastSnapshot);
    }
  }

  onMyAction(payload) {
    try {
      // do something
    }
    catch(e) {
       this.error = true; 
    }
  }
}
```

**Comment by goatslacker** [comment]
I'm working on a dev tool which your QA team can install on chrome and be able to send you a snapshot file. 

You can then load this file into your app.

**Comment by mfunkie** [comment]
Thats awesome!  Will we be able to visually inspect the stores through the dev tool?

**Comment by goatslacker** [comment]
That's the idea. Inspect the stores, record dispatched, view all dispatches going through, search and filter, flush and recycle stores, etc. 

I have a working copy on my machine just needs polish.
