### ISSUE TITLE
Is there possibility for memory leaks?

### ISSUE THREAD

**Issue by voronianski** [goatslacker/alt#133]
I'm facing some strange issues with memory - after some high load of the app its' memory usage increases, but afterwards memory is not cleaned. 

I'm using latest Alt in isomorphic app via Alt-instances. There is a class that extends Alt like

```javascript
class Flux extends Alt {
    constructor() {
        super();
        // register all actions and stores
        // this.addActions();
        // this.addStores();
    }
}
``` 

and I'm creating instance of it `new Flux()` on server per request, then `takeSnapshot` and pass snapshot to rendered html. Is there a chance for memory leaks in alt because of flux class somehow keeping data?

I noticed that `flush` reduces amount of memory usage but it breaks isomorphism if calling it before `React.renderToString(React.createElement(Handler, { flux }));`.

**Comment by goatslacker** [comment]
Not that I am aware of. I can help you debug the cause though in case it is alt or perhaps I can add documentation on how to avoid these. It can be a number of things: are you unlistening to stores in react components properly? Are your stores complex or simple and serializable?

**Comment by goatslacker** [comment]
Also, how are you detecting these leaks currently?

**Comment by voronianski** [comment]
@goatslacker I'm detecting them just by memory usage on server via `pm2 status`.

Mostly stores contain onHandlers and some static methods:

```javascript
class ArticleStore {
    constructor() {
        this.articles = [];
        this.isFetching = true;

        let articleActions = this.alt.getActions('articles');
        this.bindActions(articleActions);
    }

    onRequestArticles(requestOptions) {
        this.isFetching = true;
    }

    onReceiveArticles(data) {
        this.isFetching = false;
        if (data && data.articles) {
            this.articles = data.articles;
        }
    }

    onFailReceiveArticles() {
        this.isFetching = false;
        this.articles = [];
    }

    static getArticle(articleId) {
        let { articles } = this.getState();
        return articles.find((article) => {
            return article.articleId === articleId.replace(/\–/gi, '-');
        });
    }
}

export default ArticleStore;
```

**Comment by goatslacker** [comment]
I just twitter DM'd you.

**Comment by voronianski** [comment]
@goatslacker sorry, I didn't see your tweet, anyway thanks! 

I did some updates and as for now I'm observing normal performance of the app. But I'll keep this open for a while because the most high-load days happen to weekend and it's better to check once more.

**Comment by LePetitDev** [comment]
@voronianski For future reference, what did you end up doing to address the memory leak?

**Comment by goatslacker** [comment]
No worries, yeah I'd love to know as well. I did some profiling by issuing 1 million requests thrown at both a simple instance based Alt approach and a singleton approach and memory remained leveled. I did this with both takeSnapshot and flush. My example may be too simple though.
