### ISSUE TITLE
npm run build hangs on windows

### ISSUE THREAD

**Issue by nemoo** [goatslacker/alt#134]
I tried to get the Todomcv example to run on windows:
When i run the command ```npm run build``` (after ```npm install```), the command line hangs, showing: 

> todomvc-alt@1.0.0 build C:\Users\Username\Documents\GitHub\alt\examples\todomvc
> browserify . > js/bundle.js

Any ideas what could be the problem?

**Comment by jdlehman** [comment]
This could have something to do with browserify/babel.  I do not have a windows machine to try to debug this on, so I'd appreciate any help debugging from someone that does.

**Comment by srph** [comment]
Adding the `-v` option might help, like so:

```
$ browserify -v . > js/bundle.js
```

**Comment by goatslacker** [comment]
feel free to add it in as a PR

**Comment by nemoo** [comment]
I was able to find a -d option in  browserify. when i ran ```browserify -d . > js/bundle.js``` i got: Error: Cannot find module 'object-assign' from 'C:\Users\Username\Documents\GitHub\alt\dist'

So i tried ```npm install``` in the alt root directory to maybe create that dist directory. Then i got an error that python is missing. 
So i installed python and set the environment variable, now i get a new error: 
```npm ERR! Failed at the contextify@0.1.13 install script 'node-gyp rebuild'.```

```
gyp ERR! configure error
gyp ERR! stack Error: spawn C:\Program Files\Python 3.5 ENOENT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
gyp ERR! stack     at child_process.js:1137:20
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.3.9600
```

Now I don't want to waste anyone's time here. It seems that I stumble from one problem into the next.

**Comment by srph** [comment]
I see. I'm kind of interested to solve this since I stumbled upon problems with the other two examples as well. Although, they're different issues.

**Comment by goatslacker** [comment]
That's weird. @nemoo have you used [babel](http://babeljs.io/) on your machine before?

**Comment by nemoo** [comment]
No, i just wanted to try out the alt examples as a first dive into this world of react based SPAs.

**Comment by goatslacker** [comment]
What version of windows are you on?

**Comment by nemoo** [comment]
8.1

**Comment by goatslacker** [comment]
@neemo I found this online:

https://github.com/brianmcd/contextify/wiki/Windows-Installation-Guide

It's a problem with jsdom, you don't need jsdom to run the examples. I might just move the examples out to a separate repo so people don't have to jump through hoops.
