### ISSUE TITLE
preserving/exporting methods doesn't seem to work with static.

### ISSUE THREAD

**Issue by Aesthetickz** [goatslacker/alt#135]
My original question was about the this.exportPublicMethods not seeming to work, but it was because my unit test was corrupt. But my second question is that the alternative way of exporting public methods from a store doesn't seem to work (making the method static). Can this be because of the transpilation to ES5 with babel?

**Comment by jdlehman** [comment]
Can you provide some code so we can take a look at what you are doing?

You can also use the ES3 module pattern with alt: [example](https://github.com/goatslacker/alt/blob/cb2864257663c15db2d9a4bc53819e4d9336a222/test/es3-module-pattern.js#L9-L36)

Gonna add an issue to add docs for this so we can point people to something more substantial for using alt without ES6.

**Comment by Aesthetickz** [comment]
I am using ES6. I want to have more methods on the store then just listeners. 

import AltApp from '../core/alt-app';
import ControlInstanceActions from './control-instance-actions';

class ControlInstanceStore {
    constructor() {
        this.controls = [];

        this.bindAction(ControlInstanceActions.addControl, this.onControlAdded);
        this.bindAction(ControlInstanceActions.removeControl, this.onControlRemoved);

        //this.exportPublicMethods({
        //    getNewInstanceId: this.getNewInstanceId
        //});
    }

    onControlAdded(payload) {

        if(payload.controlTypeId && payload.name) {
            const {controlTypeId, name} = payload;
            this.controls.push({
                controlTypeId: controlTypeId,
                controlInstanceId: this.getNewInstanceId(),
                name: name
            });
        }
    }

    onControlRemoved(payload){
        if(payload.controlInstanceId) {
            const controlInstanceId = payload.controlInstanceId;
            this.controls = this.controls.filter((control) => control.controlInstanceId !== controlInstanceId);
            console.log(this.controls);
        }
    }

    static getNewInstanceId() {
        return Math.round((Math.random() * 1000000))
    }
}

export default AltApp.createStore(ControlInstanceStore);

This won't work. If i make the last method static my whole class does not work anymore

**Comment by goatslacker** [comment]
> my whole class does not work anymore

What do you mean by this?

**Comment by Aesthetickz** [comment]
Sorry I gave a wrong explaination. It's just that the onControlAdded method does not work anymore because it cannot find the this.getNewInstanceId() method:

import AltApp from '../core/alt-app';
    import ControlInstanceActions from './control-instance-actions';
    
    class ControlInstanceStore {
        constructor() {
            this.controls = [];
    
            this.bindAction(ControlInstanceActions.addControl, this.onControlAdded);
            this.bindAction(ControlInstanceActions.removeControl, this.onControlRemoved);
        }
    
        onControlAdded(control) {
            if(control.typeId && control.name) {
                control.instanceId = this.getNewInstanceId();
                this.controls.push(control);
            }
        }
    
        onControlRemoved(payload){
            if(payload.instanceId) {
                const instanceId = payload.instanceId;
                this.controls = this.controls.filter((control) => control.instanceId !== instanceId);
            }
        }
    
        static getNewInstanceId() {
            return Math.round((Math.random() * 1000000))
        }
    }
    
    export default AltApp.createStore(ControlInstanceStore);

 TypeError: undefined is not a function
            at Store.onControlAdded (C:/Users/ng/AppData/Local/Temp/f3e099e480930b2aa72bf0296f44e873.browserify:75:47 <- C:/Users/ng/Projects/greenboxui-react/app/control-instance/control-instance-store.js:14:38)

**Comment by goatslacker** [comment]
Ah yes that's correct behavior. Static methods are not available in `this` inside the class.

You probably want to use [`exportPublicMethods`](http://goatslacker.github.io/alt/docs/createStore/)

```js
class FooStore {
  constructor() {
    this.exportPublicMethods({ getNewInstanceId: this.getNewInstanceId })
  }

  fooMethod() {
    this.getNewInstanceId()
  }

  getNewInstanceId() { }
}

fooStore = alt.createStore(FooStore)

fooStore.getNewInstanceId()
```

**Comment by Aesthetickz** [comment]
Okay thank you, that was what I was allready using.
