### ISSUE TITLE
Please pay attention one more time to 71 issue

### ISSUE THREAD

**Issue by deser** [goatslacker/alt#136]
Please pay attention to my last comment in https://github.com/goatslacker/alt/issues/71. Thanks

**Comment by jdlehman** [comment]
> Can you provide me some details in which way I can modify alt dispatcher?

By default alt uses Facebook's [dispatcher](https://github.com/facebook/flux/blob/master/src/Dispatcher.js), but you can also supply your own as long as it has the same interface.

Here is how you can [use your own](https://github.com/goatslacker/alt/blob/master/docs/index.md#dispatcher) by passing in a config object to alt.

**Comment by goatslacker** [comment]
It's not a bad idea to provide a custom dispatcher that implements this queueing behavior as an addon and allow people to load it in. I'll accept that PR.

**Comment by deser** [comment]
OK, thanks guys!
