### ISSUE TITLE
AltManager confusion

### ISSUE THREAD

**Issue by continuata** [goatslacker/alt#138]
I'm referring to the weathertabs example app in an attempt to learn how to use AltManager

I can create alt instances to pass as props to child components, but I get a crash when trying to associate stores or actions with them using

```javascript
statics: { 
    registerStore: MyStore, 
    registerAction: MyActions 
},
```
It seems to crash in the AltManagerMixin because 

```javascript
var storeName = Store.name;
var actionName = Action.name;
```
are both undefined ... should I be setting them somehow?

**Comment by goatslacker** [comment]
cc @alvinsng

**Comment by alvinsng** [comment]
Hey @continuata 

Are you passing in MyStore as a class and not an instance of a store correct? The `Store.name` refers to the class name of the store and it should be defined if you're using ES6 classes.

**Comment by continuata** [comment]
aha ... ok, yes that was the problem, I was passing an instance.
Now it's got the actions class in the alt instance, but isn't setting it on `this.actions`
Should that happen automatically via the mixin?

**Comment by continuata** [comment]
ignore me ... it's `this.action` isn't it :-)
(which works)
