### ISSUE TITLE
Documentation page's assets are not loading

### ISSUE THREAD

**Issue by srph** [goatslacker/alt#140]
![screen shot 2015-04-12 at 4 21 39 am](https://cloud.githubusercontent.com/assets/5093058/7103139/c9f1bb96-e0cb-11e4-8121-a8e95da1d72b.png)

I'm not sure if this is just an issue with me. Can anybody confirm? As I can see from the screenshot above, the paths may have leading slashes `/`.

**Edit**: I just confirmed that the paths have leading slashes. Mind if I send a PR?

**Comment by goatslacker** [comment]
It's not just the leading slashes but rather that I'm using the wrong url in my config file :(

**Comment by goatslacker** [comment]
Thanks for opening!

**Comment by goatslacker** [comment]
http://goatslacker.github.io/alt/
http://alt.js.org/

both urls now work :)

**Comment by srph** [comment]
I see, thanks!
