### ISSUE TITLE
Make lifecycle an event emitter

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#145]
Currently lifecycle events are added to an object and passed into the AltStore so when adding listeners with the same name you override each other.

The goal here would be to be able to add multiple lifecycle handlers.

Dumb Example:

```js
this.on('init', setupInternalDatabase)
this.on('init', transformValues)
```

A concern here would be memory usage, if a store gets removed do the lifecycle events also get GC'd?

**Comment by goatslacker** [comment]
This isn't really possible because of serialize and deserialize which return :(

**Comment by goatslacker** [comment]
Opening this again. I think there's value in this.

**Comment by jdlehman** [comment]
#213 makes this possible again :)
