### ISSUE TITLE
Add a live interactive todolist tutorial on alt.js.org homepage

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#178]
Split pane, code on the left and the live todolist on the right. Lets you play with alt.

**Comment by srph** [comment]
Would JSFiddle be a no-no?

**Comment by goatslacker** [comment]
I hadn't thought about it. I guess it's ok if I can embed it :)

**Comment by goatslacker** [comment]
https://github.com/goatslacker/alt/issues/206
