### ISSUE TITLE
Road to 1.0.0

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#185]
I feel we're pretty close. I'm kicking off this discussion to figure out any features you'd really like to see before we hit v1.

Breaking changes and crazy ideas are welcome for food for thought.

**Comment by Aesthetickz** [comment]
Maybe figure out a bit more elegant/intuitive way to define public (and private?) methods on stores (and actions?). I really like to split up my classes in to multiple methods to keep code clean. The current method works fine but it's not very DRY.

**Comment by Aesthetickz** [comment]
Also maybe an elegant way to create methods to get a specific state property, maybe filtered by something, or with a certain predicate. So if you have a property messages you could do: MessageStore.getMessages(). Or MessageStore.getMessages.all(), MessageStore.getMessages.by({'id':  102332525 }); Just some idea's, don't know if it bloats the framework too much, or if it's better to let people create their own methods.

**Comment by Aesthetickz** [comment]
An option to trigger a store update event manually. To notifiy views after an async event.

**Comment by goatslacker** [comment]
@Aesthetickz you can already do some of these things.

Trigger a store update event manually:

```js
onFoo() {
  setTimeout(() => {
    this.emitChange();
  }, 100);
}
```

Creating methods on a specific property is as easy as using something like lodash, or extending your store:

```js
class TodoStore extends CollectionMethods { }

class MessageStore {
  constructor() {
    this.messages = new Collection();
  }
}
```

Any suggestions from DRYing things up? Currently you can use static properties or `this.exportPublicMethods` which is pretty flexible IMO. I'm all ears for suggestions though!

**Comment by Aesthetickz** [comment]
I did not know about the emitchange method, that's very nice! Well static does not seem to work with the babel compiler, but exportPublicMethod does. Maybe prefixing a method with _ or something else preserves it?

**Comment by goatslacker** [comment]
```js
class MessageStore {
  constructor() {
    this.messages = []
  }

  static getMessages() {
    var messages = this.getState().messages;
  }
}
```

**Comment by Aesthetickz** [comment]
Yeah so that method does not work for me. Also is there better support possible for ImmutableJs in Stores. Currently the bootstrap on init fix is quite ugly.

**Comment by goatslacker** [comment]
There will be in the next release. Check out the docs: https://github.com/goatslacker/alt/blob/master/docs/utils/immutable.md

**Comment by Aesthetickz** [comment]
That is, awesome!

**Comment by Aesthetickz** [comment]
I have another idea. Maybe a test utility to fake actions on store tests. Currently I am doing this:

    function unregisterParameter(controlInstanceId, parameterId) {
        AltApp.dispatcher.dispatch({
            action: ParameterActions.UNREGISTER_PARAMETER,
            data: { controlInstanceId: controlInstanceId, parameterId: parameterId }
        })
    }

and using that function in my tests..
But if you have some amount of actions it can become a lot of code and annoying to do. I myself can't currently come up with a better suggestion on how to make this more easy, because you also want some amount of customization in this. But maybe you do.

**Comment by goatslacker** [comment]
Closing this because when we underdash with marty we'll probably go 1.0
