### ISSUE TITLE
When installing from github via npm lib is missing

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#187]
Not sure what to do here.

From what I know our only two options are:

* Check the compiled output lib/ and utils/ into github
* Move the build stuff from dev-deps to dependencies and have an npm postinstall script that runs build

**Comment by Dakuan** [comment]
this is a massive PITA for developing with npm modules generally. Option 2 seems to be the best way to go, but not without it's problems, eg different versions of react

**Comment by goatslacker** [comment]
I think I should just put out alpha releases on npm rather than having people install from github.
