### ISSUE TITLE
AltContainer rendering bug on alt.js.org

### ISSUE THREAD

**Issue by doginthehat** [goatslacker/alt#189]
On the [AltContainer documentation page](http://alt.js.org/docs/components/altContainer/), there's a small rendering bug of the Markdown code.

Under `actions` the second code example is not displaying the value of the actions attribute:
![screen shot 2015-04-21 at 10 54 00](https://cloud.githubusercontent.com/assets/843366/7243764/f86e089e-e814-11e4-9049-5e78c73579c4.png)

It looks ok when [viewed on github](https://github.com/goatslacker/alt/blob/master/docs/components/altContainer.md) though.

**Comment by goatslacker** [comment]
Thanks. This is probably due to Jekyll and {{}} syntax. I'll see if a new release fixes this issue

**Comment by srph** [comment]
New release of :question: Won't a backslash be enough in this case? :smile:

**Comment by goatslacker** [comment]
New release of the website, backslash doesn't work unfortunately :(

**Comment by goatslacker** [comment]
Fixed
