### ISSUE TITLE
Action name available during dispatch

### ISSUE THREAD

**Issue by jareware** [goatslacker/alt#192]
Having the action name available during dispatch would be useful for several reasons, for instance:
 * debugging to see which action is dispatching
 * sending actions over to an analytics tool

Currently the easiest way to get it is:
```js
app.dispatcher.register(function(payload) {
  var actionName = payload.action.toString().replace(/.*#(\w+).*/, '$1');
});
```
but digging it out from the Symbol through `toString()` isn't too pretty.

Also, when munging for production with e.g. `uglify` you lose at least the store name. Extra credit for figuring out how to preserve that as well.

**Comment by goatslacker** [comment]
@jareware if you give your stores proper names via `displayName` or using the identifier passed into `alt.createStore` then you won't lose them while munging.

**Comment by jareware** [comment]
Excellent point, that's probably where we should dig those up if we end up implementing this.

**Comment by goatslacker** [comment]
I still don't know how or what to do with this...

**Comment by jareware** [comment]
I'm sorry I haven't had the time to dig into this; feel free to close if you're on a bug patrol.

As to what this *could* look like, for instance:
```js
app.dispatcher.register(function(payload) {
  console.log('Dispatching:', payload.actionNamespace, payload.actionName);
});
```

But that'd essentially just be a cleaner version of using the above regex and `displayName` as per your tip.
