### ISSUE TITLE
Allow lifecycle events to be added to a store post-construction

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#199]

**Comment by jdlehman** [comment]
were you thinking something like `MyStore.on('bootstrap', function() {})`?

Also wondering the use case you had in mind.  I suppose it could provide value to future utils.

**Comment by goatslacker** [comment]
I think this was a solution I was thinking about when I was building a util but I solved it in a different way. I'll reopen with more details if I think of a better use case.

Sorry sometimes I'm just thinking out loud and I just quickly jot these things down not knowing if its a good idea or not.
