### ISSUE TITLE
Ideas for the alt website homepage

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#206]
A getting started section. 

A live todo list example. 

A footer with the site menu

**Comment by mehcode** [comment]
Isomorphic and built with react.js / alt / iso

**Comment by goatslacker** [comment]
An example you mean?

**Comment by mehcode** [comment]
I mean the website itself should be an isomorphic application built with react.js / alt / iso / react-router with heavily documented source code.

**Comment by cmwelsh** [comment]
You can host this type of application for free using a single Heroku dyno and CloudFlare CDN rules. It'd be just as convenient as a GitHub Pages workflow for editors.

**Comment by goatslacker** [comment]
I'm on the fence about that as the website is nothing but static content which is complete overkill for react and flux. It makes for a not so great example but how to over engineer things.

**Comment by mehcode** [comment]
If that's the concern then make the website a bit more involved and not static. Have it remotely load its content from markdown files from github (making it even more convenient for editors). 

One of the key things about isomorphic applications is SEO -- showing this in the wild would be a great example.

**Comment by srph** [comment]
Has anybody checked [**component-playground**](https://github.com/FormidableLabs/component-playground).
