### ISSUE TITLE
error thrown on listenTo(store, onChange)

### ISSUE THREAD

**Issue by lostpebble** [goatslacker/alt#21]
On the newest version, 0.13.7, I am getting an error when using the `listenTo()` function (when using the `ListenerMixin`).

The error: `Uncaught TypeError: Cannot read property 'bind' of undefined`

It is being thrown on `fn.bind(context)` here in the `add` function:
```
var MIXIN_REGISTRY = '_alt store listener registry_'

	var Subscribe = {
	  create: function (context) {
	    context[MIXIN_REGISTRY] = []
	  },

	  add: function (context, store, fn) {
	    var handler = fn.bind(context)
	    context[MIXIN_REGISTRY].push({ store: store, handler: handler })
	    store.listen(handler)
	  },

	  destroy: function (context) {
	    context[MIXIN_REGISTRY].forEach(function (x) {
	      x.store.unlisten(x.handler)
	    })
	    context[MIXIN_REGISTRY] = []
	  }
	}

	module.exports = Subscribe
```

I was making a new project when it happened and reverted back to 0.13.2 that I was using on previous projects and it works fine now.

**Comment by goatslacker** [comment]
Can you provide an example on how you're using listenTo?

**Comment by lostpebble** [comment]
Sure, here is my component:
```
var React = require('react');
var WeatherStore = require('../../flux/stores/WeatherStore');
var WeatherActions = require('../../flux/actions/WeatherActions');
var ListenerMixin = require('alt/mixins/ListenerMixin');

var Constants = require('../../Constants');

var WeatherPage = React.createClass({
    mixins: [ListenerMixin],

    getInitialState() {
        return WeatherStore.getState();
    },

    componentWillMount() {
        this.listenTo(WeatherStore, this._onChange);
    },

    _onChange() {
        console.log("something changed in the matrix");
        this.setState( WeatherStore.getState() );
    },

    render() {
        return (
            <div>
                <h1>Monthly Climate App</h1>
            </div>
        )
    }
});

module.exports = WeatherPage;
```

**Comment by mshick** [comment]
My app builds also broke with the latest version. I'm using react-router, so tracing the issue proved tricky, but it boiled down to the ListenerMixin. The errors were `cannot call method push of undefined`. My use of the mixin is similar to @lostpebble. 

I was able to resolve it by doing the following:

```js
  listenTo: function (store, handler) {
+    this[MIXIN_REGISTRY] = this[MIXIN_REGISTRY] || [];
.
.
.
- ListenerMixin[MIXIN_REGISTRY] = []
```

There may be unintended consequences to this approach, so I haven't made a PR, but hopefully this helps you debug?

**Comment by goatslacker** [comment]
That's pretty crappy, the tests are working fine and I've been able to update other apps just fine so this is a bit puzzling.

I'll amend this change and push until I figure out the root cause.

**Comment by goatslacker** [comment]
This was fixed here: a3a83b963c970e44db10f13afd0c20f74d01084b

I'll refactor this to provide a better solution tonight.

**Comment by mshick** [comment]
Thanks.

When updating to 0.13.8 I'm getting a sea of `bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call.` warnings, and parts of my app get really erratic and break in a sort of confounding way -- no errors are produced but I can't navigate anywhere. Reverting to 0.13.4 solves the problem with no other changes.

**Comment by goatslacker** [comment]
What React version are both of you using?

**Comment by goatslacker** [comment]
I temporarily reverted ListenerMixin to its original behaviour until I get to the bottom of this.

**Comment by mshick** [comment]
@goatslacker I'm using 0.12.2, and also react-router 0.12.4.

**Comment by goatslacker** [comment]
Thanks. I've got a permanent fix incoming.

**Comment by goatslacker** [comment]
1e5ca13d93f66f6839277dadf9eb3c62989f5569
