### ISSUE TITLE
Remove the static method additions to stores?

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#211]
The only way to export public methods should be through `this.exportPublicMethod()`

This gives us a small perf boost when creating stores.

**Comment by jdlehman** [comment]
I think this would be a good addition to `0.16.0`.  I personally like the more explicit `exportPublicMethod` over `static`.

**Comment by troutowicz** [comment]
agreed :+1:

**Comment by srph** [comment]
I prefer `exportPublicMethod` as well :+1:

**Comment by goatslacker** [comment]
Probably in 0.17.0, there's a quite a bit of breaking changes in 0.16.0 already.

**Comment by frederickfogerty** [comment]
I'm slightly reluctant to see `static` go - I really liked the brevity in declaration of public methods. I create a lot of them so that the implementation detail of a stores data is hidden, and I thought static was a nice, concise, way of creating them. I guess `exportPublicMethods` is a better option, but I never saw anything wrong with static. If it gives a perf boost then I guess I'm all for it (although wouldn't removing exportPublicMethods have the same perf boost?)

**Comment by goatslacker** [comment]
It may not be worth the small perf boost, I need to do some more digging.

Something I've been thinking about:

```js
class TodoStore {
  static publicMethods = {
    getTodos() {
      return this.getState().todos;
    },

    getCount() {
      return Object.keys(this.getState().todos).length;
    }
  }
}
```

**Comment by frederickfogerty** [comment]
Or just 
```js
class TodoStore {
  static publicMethods = {
    getTodos: this.getTodos,
    getCount: this.getCount
  }
  getTodos () {
    return this.getState().todos;   
  }
  
  getCount () {
    return Object.keys(this.getState().todos).length;
  }
}
```

**Comment by goatslacker** [comment]
It can't be this.getTodos because this is undefined in that context.

**Comment by frederickfogerty** [comment]
My example is actually similar to the original static implementation. I do like the idea of being able to define multiple public methods to one internal method, or not having the name of the exported method tied to the name in the class/store. Although, in saying that, it introduces another complexity when debugging.

**Comment by goatslacker** [comment]
Probably won't be removing this since the perf gain is not worth it. We can reopen later
