### ISSUE TITLE
Mixin replacement for futures React releases?

### ISSUE THREAD

**Issue by RaitoBezarius** [goatslacker/alt#217]
Hi, I was thinking if Alt was going to provide a replacement for mixin as React said it is going to deprecate them (ES6 components with react@0.13.x cannot use mixins).

What about doing a factory that will pass store's state by props to the _child_ component?

**Comment by goatslacker** [comment]
Something like http://alt.js.org/docs/components/altContainer/ ?

**Comment by RaitoBezarius** [comment]
@goatslacker Completely. Thanks !

**Comment by goatslacker** [comment]
Np!
