### ISSUE TITLE
Fetching Data - `Continue to next step…` 404s

### ISSUE THREAD

**Issue by bebraw** [goatslacker/alt#218]
1. http://alt.js.org/guide/async/
2. Hit `Continue to next step…`
3. 404

Looks like there is an extra `s` at the url.

It might be a good idea to run some 404 checker on the site to find these.

**Comment by dobrite** [comment]
Next step is also broke [here](http://alt.js.org/guide/) due to an extra 's'.

**Comment by goatslacker** [comment]
Fixed. Thanks all!
