### ISSUE TITLE
The link for "continue to next step" is broken on the Getting Started page

### ISSUE THREAD

**Issue by firstdoit** [goatslacker/alt#237]
Here: https://github.com/goatslacker/alt/blob/master/web/guides/getting-started/index.md

Although the link in the markdown appears correct, the live site points to: 

http://alt.js.org/guide/actions.md

Which `404`s, unfortunately.

I'm sorry I don't know how to fix it, so I can only point to the problem :)

**Comment by bebraw** [comment]
The same problem is visible at http://alt.js.org/guide/actions/ (link to stores). It's some systematic error. Probably has something to do with the system that converts Markdown to HTML.

**Comment by bebraw** [comment]
https://github.com/goatslacker/alt/commit/41da980bfc0b40b65210a1417944ed42c8aa6898 broke it.

**Comment by bebraw** [comment]
@firstdoit If you want to try to fix it, look into https://github.com/goatslacker/alt/blob/master/web/Rakefile#L78.

**Comment by goatslacker** [comment]
That commit was supposed to fix it :(

**Comment by bebraw** [comment]
It's probably very close. That `((?<link>.+?).md` part looks a bit suspicious to me. `.` is dangerous in regex always.

**Comment by bebraw** [comment]
As a quick fix maybe it's enough just to strip `.md` if it's hanging around.

**Comment by jdlehman** [comment]
We probably want to escape the `.` if nothing else.

**Comment by ozkxr** [comment]
I think you are using jekyll or hexo to generate the site. I try to fix it and add a PR but I noticed that the code is generated from a source. I forget to add it as a issue anyway. Just add the links without the .md part, and use absolute urls, no relative ones, I think Jekyll and Hexo have helpers to achieve that.

:sunglasses: :+1:

**Comment by goatslacker** [comment]
Jekyll. But we have a custom rake task that parses the links for web.

**Comment by ozkxr** [comment]
Ok, I thought you were using the Jekyll way

**Comment by jdlehman** [comment]
These links are now fixed. Let us know if you find any other issues on the site.

**Comment by firstdoit** [comment]
:star2:
