### ISSUE TITLE
Searchable API Documentation (website related)

### ISSUE THREAD

**Issue by af7** [goatslacker/alt#239]
Hello, is it possible that your API documentation on your website has a SEARCH box? http://alt.js.org/guide/

For example, I had no idea what "listen" and "unlisten" does (I saw it on another project that uses Alt). Since the guide is "category based" I had to open all categories and perform find there.

I assume you get the point, have what jQuery has.

If time permits the inclusion of search within Docs (and only there) would be nice. Keep up the GREAT work!

**Comment by goatslacker** [comment]
Ok fuck it I'll build one with alt. It'll make for a nice React+Alt example.

**Comment by af7** [comment]
That would be a great example!

**Comment by bebraw** [comment]
@goatslacker Look into [lunr](http://lunrjs.com/). It's fairly easy to work with. You just generate a static index and then let it operate against that on frontend. Sweet and simple.

**Comment by goatslacker** [comment]
Thanks @bebraw that's perfect. I had it starred from before but had forgotten about lunr.

I'll write up the frontend and let lunr handle the indexing. https://github.com/goatslacker/alt/pull/241

**Comment by goatslacker** [comment]
Done.

Setup the repo here: https://github.com/goatslacker/alt-search-docs
Added the search here: 9ba3602c394ebf00103da035e81f4e8751f1ba0e
You can view it here: alt.js.org

**Comment by bebraw** [comment]
Looks great!

**Comment by bebraw** [comment]
@goatslacker Tiny tweak. Add `placeholder="Search"` at the input there to make the intent clearer. Better UX.

**Comment by goatslacker** [comment]
Ah yes.

**Comment by troutowicz** [comment]
Looks great @goatslacker !

**Comment by af7** [comment]
Nice! Good work!

Does it render all "API Documentation" section? Because when I search for `AltContainer` (which exists there) it does nothing.

Is this a small "bug" to be fixed or expected behavior?

**Comment by goatslacker** [comment]
Bug to be fixed the indexer doesn't traverse directories
