### ISSUE TITLE
[question] setState() behaviour in immutable store?

### ISSUE THREAD

**Issue by vkbansal** [goatslacker/alt#242]
If I define my state as follows:
```js
this.state = {
    a: Immutable.List([]),
    b: Immutable.List([])
}
```
And later If I perform something like:
```js
const { b } = this.state;
this.setState({ 
    b: b.push(1)
})
```

I expected the outcome to be (similar to React):
```js
{
  a: [ ],
  b: [1]
}
```

but Instead it is:
```js
{
  b: [1]
}
```
Is this expected behavior or a bug?

If it is the expected behavior then what's the work-around other than assigning each property every-time.

**Comment by goatslacker** [comment]
how are you creating that immutable store?

If you're using the immutable addon then your entire state should be an immutable object not just its properties.

You can use a regular store for that and get the setState behavior you want.

**Comment by vkbansal** [comment]
Yes. I'm using `@immutable` to create the Store.

So If I remove it, that will fix the problem. Right?

**Comment by goatslacker** [comment]
Yup!

There's not much benefit in using the decorator like that since it mainly adds hooks for serialization and deserialization but your state has to be immutable.

**Comment by vkbansal** [comment]
> There's not much benefit in using the decorator like that since it mainly adds hooks for serialization and deserialization but your state has to be immutable.

OK !
I misunderstood the usage.

Thanks for the quick reply!

**Comment by mull** [comment]
@goatslacker is there any reason why setState() for @immutable can't work like setState() normally does?

**Comment by srph** [comment]
mind elaborating, @mull? :smile

**Comment by jdlehman** [comment]
@mull `setState` usually uses `Object.assign` and essentially merges the existing object with the new data. This is not compatible with libraries like immutable-js because `Object.assign` only works with POJOs.  Immutable data structures cannot be mutated so they always return a new data structure with the modified data in it rather than mutating the existing one. So the updated `setState` just swaps the reference to the new data structure.

Hopefully some of that makes sense (didn't have the time for a long reply at the moment)

**Comment by mull** [comment]
@jdlehman thanks for the reply. I ended up making my own @immutable decorator which expects state to be an Immutable.Map - then setState is as simple as

```
    setState(currentState, nextState) {
      this.state = currentState.merge(nextState);
      return this.state;
    },
```

@srph sorry for the vagueness!

**Comment by jdlehman** [comment]
Nice was going to suggest that as well. Glad you found something that works for you.
