### ISSUE TITLE
Version 0.16.4 AltContainer no longer passes store props. 

### ISSUE THREAD

**Issue by jarsbe** [goatslacker/alt#249]
Hello, I'm moving from 0.15.4 to 0.16.4 and using ES5 and working with Alt instances and I have an `AltContainer`.

```
<AltContainer stores={[flux.getStore('MyStore')]} 
              actions={MyActions: flux.getActions('MyActions')}>
  <MyComponent />
</AltContainer>
```

The actions are passed correctly. However, the store doesn't pass any data as props to `MyComponent`.

Is there something obvious that I have missed? I've taken a read through the changelog but nothing stands out.

**Comment by frederickfogerty** [comment]
AFAIK, you have have to define the stores as `stores={{myPropKey: flux.getStore('MyStore')}}` now

**Comment by jarsbe** [comment]
Cheers @frederickfogerty - that does the trick. Bit of a shame that everything must be accessed via the `myPropKey` though.

**Comment by goatslacker** [comment]
You probably want to use `store`:

```html
<AltContainer store={flux.getStore('MyStore')} 
              actions={MyActions: flux.getActions('MyActions')}>
  <MyComponent />
</AltContainer>
```

**Comment by jarsbe** [comment]
@goatslacker `store` works well but is it possible to explicitly send data in directly as props without for multiple stores, or must things be accessed via the particular store key?

**Comment by goatslacker** [comment]
There are two ways you can do that, use `stores` or use `inject`. http://alt.js.org/docs/components/altContainer/
