### ISSUE TITLE
Web Utils with ES5 & instances

### ISSUE THREAD

**Issue by jarsbe** [goatslacker/alt#254]
Hello, I'm working in an ES5 project using Alt instances. I want to break out my data fetching utilities from Stores. Here's what I'm trying to achieve:

- Actions send events. 
- Stores update data. 
- Web Utils fetch data.

The problem is integrating web utils into Alt.

Say I have a `Books` collection. I've also got a sorting component with it's own Store and Actions.

``` Actions
var SortActions = {

  sort: function(query) {
    this.dispatch(query);

    BookWebUtils.sort(query);
  }
};
```

``` BookWebUtils
var BookWebUtils = {
  sort: function(query) {
    BookData.fetch(query).then(function(response) {
      BooksAction.successLoadingBooks(response);
    }).catch(function(message) {
      BooksAction.errorLoadingBooks(message);
    });
  }
}
```

Here book data returns a promise. The issue is accessing BooksAction. 

`SortActions` requires `BookWebUtils` which in turn requires a flux instance (to access BooksActions).

I've taken a look at https://github.com/goatslacker/alt/issues/57 but since I'm using instances I'm a little stuck on what to do. 

I'd really like to use utilities rather than forcing everything into the Store. Any help would be much appreciated!

**Comment by goatslacker** [comment]
First, have you looked at: http://alt.js.org/docs/async/ ?

Next, you can call `BookWebUtils` with your alt instance:

```js
BookWebUtils.sort(this.alt, query);
```

**Comment by jarsbe** [comment]
Ah that async API looks nice. I tried implementing it but no dice! I had a look through the code and saw I could add a datasource key to the config object of a store. This didn't seem to achieve anything though. I followed your demo from issue #233 but couldn't override `getState`. I'm using 0.16.5 and instances. So the only difference with your code is `alt.createStore(StoreClass)`.

**Comment by goatslacker** [comment]
Can you post some code?

**Comment by jarsbe** [comment]
Sure thing:

```
var Alt = require('alt'),
    MyActions = require('./actions/my-actions'),
    MyStore = require('./stores/my-store');

function Flux() {
  Alt.apply(this, arguments);

  this.addActions('MyActions', MyActions);
  this.addStore('MyStore', MyStore(this.getActions('MyActions')));
}

Flux.prototype = Object.create(Alt.prototype, {
  constructor: {
    value: Flux,
    enumerable: false,
    writable: true,
    configurable: true
  }
});

Flux.__proto__ = Alt;

module.exports = Flux;
```
```
function MyStore(MyActions) {

  return {
    displayName: 'MyStore',
   
    ... bind listeners etc
    state: {
      collection: {},
    }
  };
}

MyStore.config = {
  getState: function (state) { console.log('Hello'); return state }
}
```

```
var flux = new Flux();
flux.getStore('MyStore').getState();
// No console.log Hello
```

**Comment by goatslacker** [comment]
Ah so to override getState you need to put the config in the object you're returning.

**Comment by jarsbe** [comment]
Ah wonderful - thank you!
