### ISSUE TITLE
connectToStores

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#256]
Race condition where if you do action calling in componentDidMount you might not receive the update since the store has not been listened to yet.

**Comment by michaelBenin** [comment]
Recently I've been using alt in a project where I'm executing react-router on the server. 

I am receiving an error of:

    [ReferenceError: document is not defined]

This is happening when I'm executing my component on the server, and it is removed when I remove these lines:

````
 componentWillMount() {
    //RepoDetailsStore.listen(this.onChange);
    var params = this.getParams();
    ReposActions.fetchRepo(params.owner, params.name);
  },
  componentWillUnmount() {
    //RepoDetailsStore.unlisten(this.onChange);
  },
````

Is there a way that when this is called on the server, there is a check for what environment it's running it and prevent this error? 

LMK if this is related to connectToStores or if this belongs in a separate issue, or if I'm doing something wrong. I'm following the github example. 

I'd be happy to create a repo with a repro. 

I'm 1 week into react and flux. 

Thank you!

**Comment by goatslacker** [comment]
I'm a little confused, how is that code related to connect to stores?

From the looks of it I think you're setting state on the server and you're getting that error.

**Comment by michaelBenin** [comment]
I will delete this comment and open a separate issue.

**Comment by goatslacker** [comment]
@chrishoage 

Fixing this by creating an onDidMount hook

**Comment by chrishoage** [comment]
Sounds great, let me know if you would like me to PR my test (or clean the test up at all, noticed some better way to test method calls in your other tests)

**Comment by goatslacker** [comment]
I put up your test as a PR already: #304 just gotta implement the call on that PR.

**Comment by chrishoage** [comment]
Oh sweet, thanks man!

**Comment by goatslacker** [comment]
464bb26c83d3618628d1fddc834c8bc51d3eb5b2
