### ISSUE TITLE
Add a way to add arguments to actions in Sources

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#258]
If you wish to pass in some extra information to your loading, success, fail actions there should be a way to add those values in.

Some sort of merge args/merge props function

**Comment by goatslacker** [comment]
So this could be a new method `interceptResponse` or something? It would take in the parameter of the value that's being passed to success/loading/failed and you would return something from it (anything). That value would then be passed to the loading/success/failed action.

Perhaps we can also pass in the corresponding action that is being called so you know which state you're in:

```js
fetchUser = {
  remote() { }
  local() { }
  interceptResponse(data, action) {
    return 12; // always returns 12 to loading/success/failed
  }
}
```

**Comment by jdlehman** [comment]
I like that approach. An alternative that could provide more custom control over each action:

```
fetchUser = {
  remote() { },
  local() { },
  loading: {
    action: MyLoadingAction,
    interceptResponse(data) {
      return 12; // always returns 12 to loading
    }
  },
  error: {
    action: MyErrorAction,
    interceptResponse(data) {
      return 1; // always returns 1 to success
    }
  }
}
```

This is just me throwing out a suggestion.  I actually think I prefer what you suggested as it is simpler.  But this is just an idea if we find there is a reason people need to return different data to each action and do not want to return data they are not using.

**Comment by goatslacker** [comment]
cc @wlue who initially had the idea

**Comment by wlue** [comment]
If combined with the proposed change in #261, so looking something like this:

```
const UserSource = (alt) => {
  return {
    fetchUser(id) {
      return {
        remote(state) {}
        interceptResponse(data, action) {
          return {args: {id}, data};
        }
      }
    }
  };
};
```

I think this would work.

**Comment by chrishoage** [comment]
When might interceptResponse be released? Is there a workaround to pass in data to the loading action handler currently?

**Comment by goatslacker** [comment]
6f074a305e265ad0201ae76135d8f5bcbcb500bf
