### ISSUE TITLE
Change source API

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#261]
Proposed API:

```js
const UserSource = (alt) => {
  return {
    fetchUser: {
      remote(state, id) {
        ...
      }
    }
  };
};
```

This new API would check if the source is an object or a function, if its a function then it would call it with `alt` instance as its first parameter (for instance support). Otherwise it would just import things in.

Benefits of this approach are that the alt context is defined once at the top.

Alternative approach:

```js
const UserSource = (alt) => {
  return {
    fetchUser(id) {
      return {
        remote(state) {
          ...
        }
      }
    }
  };
};
```

In this solution the parameters are defined in a single place.

Cons to this solution are that it requires an extra function call.

Thoughts?

cc @wlue @jdlehman

**Comment by wlue** [comment]
I like the second approach. It makes it clear what the arguments for the call are.

**Comment by goatslacker** [comment]
The nice thing about the first approach is that it can be made backwards compatible, not so much for the second approach.

The second approach will also suffer from being rebuilt (remote, local, etc) every time that it is called.

**Comment by chrishoage** [comment]
One thing that seems a little odd to me is the fact that seemingly everything else (Actions/Stores) in Alt is made from Classes. Would there be a way to create data sources from classes? If classes were used it would also allow for decorators on the source, not just on the properties.

**Comment by goatslacker** [comment]
Classes would work as long as you return an object.

```js
class UserSource {
  constructor(alt) {
    return {
      ...
    }
  }
}
```

**Comment by chrishoage** [comment]
After some thought I vote for the alternative approach because it would allow for stores to be created like the following, which I think is cleaner 

```javascript
function createSource (alt) {
  return function (SourceClass) {
    return new SourceClass(alt)
  }
}

@createSource(alt)
class UserSource {

  constructor(alt) {
    this.alt = alt
  }
  
  fetchUser(id) {
    return {
      remote(state) {
        return request.get(`/users/${id}`)
      },
      success: UserActions.fetchedUser,
      error: UserActions.fetchedUserError
    }
  }
  
}
```

**Comment by goatslacker** [comment]
I think we're pretty set with: function (for context) or object.

```js
const Source = {
  doThing: {
    remote() { },
    success: action,
    error: action
  }
}
```

It makes sense for the definitions to be keys rather than methods because:

* It is only evaluated once when they're created and attached to the store.
* They define a "spec" of how your call should behave.
* It's terse.

The minor inconvenience is that args you pass in get appended to remote/local after `state`. I don't think this is a deal breaker though and it's something we can live with.

**Comment by wlue** [comment]
Perhaps something that might make `remote` and `local` make more sense is if the `state` arg wasn't supplied, and the arguments were purely based on what's passed into the action. My thought is that you can always access state through the alt instance.
