### ISSUE TITLE
Cannot push on undefined in Suscribe.js with 0.13.10

### ISSUE THREAD

**Issue by mshick** [goatslacker/alt#28]
Similar issue that you've been working on. Things were working for me with 0.13.9, but with .10 that array creation issue seems to have shifted over to the Subscribe.js mixin. I get: `Cannot read property 'push' of undefined`.

Looking through the code, I see where you call `add` on the subscribe mixin from within the listener mixin, but I don't see where the `create` method was called.

**Comment by goatslacker** [comment]
It gets called on componentWillMount

**Comment by mshick** [comment]
I see. We had a custom mixin that was wrapping up some functionality of alt but not including it specifically as a mixin, so I think that's where the problem is. Thanks!

**Comment by goatslacker** [comment]
<3 sweet
