### ISSUE TITLE
Test dispatch on async failed

### ISSUE THREAD

**Issue by eversadia** [goatslacker/alt#281]
Here are the sample code

```javascript
class SampleActions {
  async myMethod( data ) {
    var url = 'http://someurl';
    try {

      let response = await jsonp( 'GET', url);
      console.log(response.body);
      this.dispatch(response.body);
    } catch(err) {
      console.log(err);
      this.dispatch(err);
    }
  }
}
```

I was testing the SampleActions.myMethod using sinon to check for the dispatch. Unfortunately it fails, I'm not sure if  i was doing it wrong using the async await or I'm testing it the wrong way. If you try to remove the async await the dispatch is working correctly ( my test is based on your example how to test dispatch)..

**Comment by goatslacker** [comment]
I'll check it out today

**Comment by goatslacker** [comment]
https://gist.github.com/goatslacker/27a577a27dfbb16ef28d

**Comment by eversadia** [comment]
Here are my sample test, I was trying to test  the dispatch

https://gist.github.com/eversadia/26615c04e0703a1c40c8

**Comment by goatslacker** [comment]
It's working:

https://gist.github.com/goatslacker/056c9a00aa62fe088f95

Can you inspect the symbol you're getting? My guess is that you're using babel's Symbol implementation?

**Comment by goatslacker** [comment]
Updated the gist: It's not working because async/await if asynchronous so you need to account for that.
