### ISSUE TITLE
[ReferenceError: document is not defined] - calling listen and unlisten on server

### ISSUE THREAD

**Issue by michaelBenin** [goatslacker/alt#282]
Recently I've been using alt in a project where I'm executing react-router on the server. 

I am receiving an error of:

    [ReferenceError: document is not defined]

This is happening when I'm executing my component on the server, and it is removed when I remove these lines:

````
 componentWillMount() {
    //RepoDetailsStore.listen(this.onChange);
    var params = this.getParams();
    ReposActions.fetchRepo(params.owner, params.name);
  },
  componentWillUnmount() {
    //RepoDetailsStore.unlisten(this.onChange);
  },
````

I'm executing my routes on the server with react router, or setting state on the server:

````
import React from 'react';
import Router from 'react-router';
import routes from '../../../react_router/react_router';

export default (req, res) => {
  Router.run(routes, req.url, (Handler, state) => {

    if(state.routes[1].isNotFound) {
        res.status(404);
    }

    var content = React.renderToString(React.createElement(Handler));
    res.send('<!doctype>' + content);
  });
};
````

Is there a way that when this is called on the server, there is a check for what environment it's running it and prevent this error? 

I'd be happy to create a repo with a repro.

**Comment by goatslacker** [comment]
I usually typeof window === 'undefined' on the server

**Comment by goatslacker** [comment]
you should definitely setup store listeners in componentDidMount and not WillMount since WillMount runs on the server.

**Comment by michaelBenin** [comment]
Awesome, thanks so much for responding.
