### ISSUE TITLE
Why this.setState is undefined in React ES6 class?

### ISSUE THREAD

**Issue by theaqua** [goatslacker/alt#283]
Hi, I trying to use ES6's classes for React (syntax as `class X extends React.Component`) and [alt.js](http://alt.js.org) as flux library. When something changed in my store, my view calls `onChange`, but it throws error `Uncaught TypeError: this.setState is not a function`.

My React component:

    import React from 'react';
    import { Router, Link } from 'react-router';

    import PropertiesActions from '../../actions/properties';
    import PropertiesStore from '../../stores/properties';
    import PropertiesComponent from '../../components/properties/list';

    // Module
    class PropertiesView extends React.Component {
      constructor(props) {
        super(props);

        this.state = PropertiesStore.getState();
      }

      componentDidMount() {
        PropertiesStore.listen(this.onChange);

        PropertiesActions.getList();
      }

      componentWillUnmount() {
        PropertiesStore.unlisten(this.onChange);
      }

      onChange(state) {
        this.setState(state);
      }

      render() {
        return (<PropertiesComponent properties={this.state.properties} {...this.props} />)
      }
    };

    PropertiesView.contextTypes = {
      router: React.PropTypes.func
    };

    // Export
    export default PropertiesView;

**Comment by troutowicz** [comment]
React components using ES6 classes no longer autobind `this`. In your constructor, add:

`this.onChange = this.onChange.bind(this)`

**Comment by theaqua** [comment]
@troutowicz thanks!

**Comment by LePetitDev** [comment]
@troutowicz :clap:

**Comment by jonnywyatt** [comment]
@troutowicz - nice one, saved me some time thanks

**Comment by gchandrasa** [comment]
@troutowicz thank you, you really save my day!

**Comment by goatslacker** [comment]
FYI Make sure you do `this.onChange = this.onChange.bind(this)` in your constructor: https://medium.com/@goatslacker/react-0-13-x-and-autobinding-b4906189425d

**Comment by jdlehman** [comment]
You can also use this [decorator](https://github.com/andreypopp/autobind-decorator)

**Comment by goatslacker** [comment]
Disclaimer ^^ requires a polyfill and I think it doesn't work on IE8.

**Comment by kiki-le-singe** [comment]
@troutowicz thanks!

**Comment by lenage** [comment]
@troutowicz Thanks, it works like charm!

**Comment by troutowicz** [comment]
:blush:

**Comment by kiki-le-singe** [comment]
You can also use the following code by combining ES6 and ES7:

> Note: Don't forget to setup Babel for this [babelify](https://www.npmjs.com/package/babelify#enable-experimental-transforms)

```javascript
onChange = (state) => {
  this.setState(state);
}
```

See [React on ES6+](http://babeljs.io/blog/2015/06/07/react-on-es6-plus/) from Steven Luscher

**Comment by mgrodek** [comment]
Aaaagrh.. that was killing me! Thanks a lot for this.

**Comment by arcseldon** [comment]
:+1:

**Comment by arcseldon** [comment]
@jdlehman / @kiki-le-singe  - Thank you for point the arrow syntax option which auto-binds enclosing scope this.

**Comment by aryalprakash** [comment]
thanks!

**Comment by iOSQiao** [comment]
very good.

**Comment by kubante** [comment]
saved my morning

**Comment by jorgeluis11** [comment]
Hello everyone,

Another cleaner approach is this one:

```
    onTextChange(){
		// this.state can be used in this function
	}

	render(){
		return (
			<div>
				<input
				 onChange={() => this.onTextChange()}/>
			</div>
		)
	}
```

In case anyone needs the **event** parameter.
```
    onTextChange(event){
		// this. and event can be used
	}

	render(){
		return (
			<div>
				<input
				 onChange={(event) => this.onTextChange(event)}/>
			</div>
		)
	}
```

@theaqua

**Comment by mrbarde** [comment]
Hi! @troutowicz your answer seemed to have helped a lot of users on this issue except me of course, now i get the following error `Cannot read property 'bind' of undefined` please what could be the issue? thanks, eagerly awaiting your response!

**Comment by kevinSuttle** [comment]
Updated link: http://babeljs.io/blog/2015/06/07/react-on-es6-plus

**Comment by mrbarde** [comment]
Thanks @kevinSuttle problem solved,

Just in case anybody like me comes here you simply bin the object to your desired method like so.
    construct(){
        self();
        this.yourMethod = this.yourMethod.bind(this);
    }
And you're done!

**Comment by shadrech** [comment]
I used the arrow function to bind this to the onChange method but keep getting the 'Unexpected token' error. Even in the Steven Luscher blog post (updated link above), the [code](https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&experimental=true&loose=false&spec=false&code=class%20PostInfo%20extends%20React.Component%20%7B%0A%09handleOptionsButtonClick%20%3D%20(e)%20%3D%3E%20%7B%0A%20%20%20%20this.setState(%7BshowOptionsModal%3A%20true%7D)%3B%0A%20%20%7D%0A%7D) on the Arrow Function section gives same error. What could I be doing wrong @troutowicz @kevinSuttle @mrbarde

**Comment by kevinSuttle** [comment]
@shadrech This is phoned-in response, but I did come across this package that handles binding for you using ES7 decorators. https://github.com/andreypopp/autobind-decorator

**Comment by shadrech** [comment]
@kevinSuttle Thanks for the package, will try it out.
But why is the arrow function not working? I sit to do with the ES version I'm using?

**Comment by nodox** [comment]
This was super helpful. [autobind](https://github.com/andreypopp/autobind-decorator) came in handy when I needed to bind my methods

**Comment by TeodorKolev** [comment]
none of this works for me

**Comment by goatslacker** [comment]
@TeodorKolev why is it not working?

**Comment by goatslacker** [comment]
@TeodorKolev why is it not working?

**Comment by Pines-Cheng** [comment]
or   ::this.onChange ,this is more convenient.

**Comment by mrbarde** [comment]
@TeodorKolev you could try using react autobind, works like magic.https://www.npmjs.com/package/react-autobind

**Comment by hanserino** [comment]
@troutowicz Thanks! To all others implementing this, note that adding the onChange binding itself won't fix anything. You'll need to add your specific function you want to bind to the constructor. If it's a resize handling function, do `this.handleResize = this.handleResize.bind(this);`

**Comment by jasan-s** [comment]
Hey guys I keep getting this error when using this line of code `this.handleRequestOpen({open: true}):`

>  Uncaught TypeError: Cannot read property 'handleRequestOpen' of undefined

Its not from binding I think. Any thoughts? Initially I was just trying to call  
`this.setState({ open: false })`. Should it know what "this" is?

My code: 

```
class HomeContainer extends Component {

  static propTypes = {
    authError: PropTypes.string,
    removeError: PropTypes.func.isRequired,
    fetchingUserSuccess: PropTypes.func.isRequired,
    authUser: PropTypes.func.isRequired
  }

  static contextTypes = {
    router: PropTypes.object.isRequired
  }

  constructor (props) {
    super(props)
    this.state = {
      open: false
    }
  }
  componentDidMount () {
    firebaseAuth.getRedirectResult().then((authUser) => {
    // The signed-in user info.
      console.log('User Data from Oauth Redirect: ', authUser)
      const userData = authUser.user.providerData[0]
      const userInfo = formatUserInfo(userData.displayName, userData.photoURL, userData.email, authUser.user.uid)
      return (this.props.fetchingUserSuccess(authUser.user.uid, userInfo))
    })
    .then((user) => {
      return saveUser((user.user))
    })
    .then((user) => {
      return (this.props.authUser(user.uid))
    }).then((user) => {
      this.context.router.replace('feed')
    }).catch(function (error) {
      // Handle Errors here.
      const errorCode = error.code
      const errorMessage = error.message
      // The email of the user's account used.
      const email = error.email
      // The firebase.auth.AuthCredential type that was used.
      const credential = error.credential
      // if error is that there is already an account with that email
      if (error.code === 'auth/account-exists-with-different-credential') {
        // console.log(errorMessage)
        firebaseAuth.fetchProvidersForEmail(email).then(function (providers) {
           // If the user has several providers,
          // the first provider in the list will be the "recommended" provider to use.
          console.log('A account already exists with this email, Use this to sign in: ', providers[0])
          if (providers[0] === 'google.com') {
            this.handleRequestOpen({open: true})
          }
        })
      }
    })
  }

  handleRequestOpen = (state) => {
    this.setState(state)
  }

  handleRequestClose = () => {
    this.setState({
      open: false
    })
  }
  render () {
    return (
      <div>
      <Snackbar
          open={this.state.open}
          message= 'A account already exists with this email'
          autoHideDuration={4000}
          onRequestClose={this.handleRequestClose.bind(this)}/>
      <Home />
      </div>
    )
  }
}
```

**Comment by thecodecafe** [comment]
@jasan-s If you want any method(function) within your class to work, you need to bind it, in your constructor enter the following code, `this.handleRequestOpen = this.handleRequestOpen.bind(this);`
you should do the same for handle request close, hope this helped? :D

**Comment by jasan-s** [comment]
@mrbarde thanks. I instead changed my older syntax of using function to newer arrow function () => {}
and that solved the issue.

**Comment by Labyrins** [comment]
Thank you so much, dudes. I solved my problem.

**Comment by vicky507** [comment]
In my code i got uncaught type error which shows its not defined while i have bind it within constructor.
Pls help me

**Comment by aliaro428** [comment]
@troutowicz thanks

**Comment by zachowdhury** [comment]
> React components using ES6 classes no longer autobind `this` to non React methods. In your constructor, add:
> 
> `this.onChange = this.onChange.bind(this)`

thanx to @troutowicz This solved  my problem

**Comment by srihari906** [comment]
I am getting TypeError: Cannot read property 'name' of undefined, when the page loads.

I have registered onSubmit in the constructor
this.onSubmit = this.onSubmit.bind(this); 

pls help me

**Comment by Anuskhan** [comment]
Use Arrow function . func =( )=>{ }

**Comment by nateeither** [comment]
> React components using ES6 classes no longer autobind `this` to non React methods. In your constructor, add:
> 
> `this.onChange = this.onChange.bind(this)`

You saved my day

**Comment by sagaraideabits** [comment]
Thank you

**Comment by npacifique** [comment]
@troutowicz your response was very helpful, thank you
