### ISSUE TITLE
StoreModel Config without ES7

### ISSUE THREAD

**Issue by dkingman** [goatslacker/alt#286]
For starters, I'd like to say thank you for creating this library.

From the example in the docs on creating stores:

```
class TodoStore {
  static config = {
    stateKey: 'state'
  }
  constructor() {
    this.state = { todos: {} }
  }
}

new TodoStore()
```

This only works (at least for Babel) by opting in to *Expiremental* mode. Since, class properties are still a stage 0 proposal I'd rather not be using them. By what other means can a `alt store` be configured?

**Comment by goatslacker** [comment]
Thanks :)

You can use plain JS syntax:

TodoStore.config = {}

**Comment by dkingman** [comment]
Ah I see. Thanks.
