### ISSUE TITLE
more modular ? grouping relevant files together

### ISSUE THREAD

**Issue by rkoberg** [goatslacker/alt#289]
New to flux & react and therefore alt. I am coming with with good experience from the angular world. After a few large projects I started keeping my apps 'components' or 'modules' together rather than depositing them in well known folders, which in flux/react app are: actions, components, images, scss/components, and stores. And in server: config, controllers, models, and views. From what I have seen this is what is the recommended approach. But when a project gets very large with a great many 'components' it becomes difficult to navigate a project.

I was wondering if a different directory based approach would be more useful as projects get larger.  For example a user component in app/components/user might contain:
* login
-- Login.react.js
-- _login.scss
* logout
-- Logout.react.js
-- _logout.scss
* UserActions.js
* UserStore.js
* user-routes.js // define the routes close to the code
* images
-- default-avatar.png

And in the server/components/user:
* user-config.js
* users-controller.js
* user-model.js
* user-routes.js

and app/components/navigation could contain:
* Navigation.react.js
* _navigation.scss

So instead of jumping around to what could turn out to be extremely long lists of files in well known folders, you group the code for quick and easy access. What do you think? Obviously a lot of thought has gone into the current folder structure and it is what everyone seems to use, but was wondering what others do for a large project with many components. I don't see anything that is stopping me from do what I describe above, but was wondering if you can foresee problems or perhaps alt might even adopt the structure I describe as the default/best practice? :)

**Comment by goatslacker** [comment]
You might find this interesting: 

https://gist.github.com/ryanflorence/daafb1e3cb8ad740b346

**Comment by goatslacker** [comment]
A different answer, alt doesn't concern itself with how you structure your files but I guess something like this could belong in a style guide somewhere or a best practices advice.

In a large project normally your sub pages are probably divided into their own folders or apps already so you'd probably keep flux to that scope.
