### ISSUE TITLE
fix Store.unlisten(undefined)

### ISSUE THREAD

**Issue by pstoica** [goatslacker/alt#292]
I stumbled across a case where someone accidentally called .unlisten with undefined. I stepped through the EE code and found out it wipes the listeners if the function is undefined. Can we safeguard this on the Alt side, maybe even make it an invariant?

**Comment by goatslacker** [comment]
I'm cool with this being an invariant for next patch release, that's kinda funny.

This is going away in 0.17.0 btw.

**Comment by pstoica** [comment]
Cool, I'll add it. I encouraged switching connectToStores btw.. definitely hate writing subscription logic, glad to hear it's going away.

**Comment by goatslacker** [comment]
oh yeah definitely, best practice is to AltContainer or connectToStores

**Comment by goatslacker** [comment]
4998c6a8c2881ee98be97cf229cdf61c2ab105c0
