### ISSUE TITLE
Misleading defer docs?

### ISSUE THREAD

**Issue by pstoica** [goatslacker/alt#297]
Got a question about these docs:

https://github.com/goatslacker/alt/blob/master/docs/actions.md#actiondefer

This example should be fine without defer since all of these lines can be synchronous and separate dispatch loops, right? Can the example be changed to run in an action handler from a store?

**Comment by goatslacker** [comment]
Yup that should be ok

**Comment by goatslacker** [comment]
I'll remove those examples

**Comment by goatslacker** [comment]
42106ae974638b8bd63949a0503b16d50809ceb4
