### ISSUE TITLE
emitChange within Store

### ISSUE THREAD

**Issue by willcosgrove** [goatslacker/alt#3]
Is there a way to emit a change from within a store?  I'll give you an example where this would be helpful:

```coffee
class TaskStore
  constructor: ->
    @bindActions(App.Actions)
    @collection = []

  onSearch: (query) ->
    $.ajax
      url: '/search/tasks'
      method: 'get'
      dataType: 'json'
      data: {q: query}
      success: (results) =>
        @collection = @collection + results
        # currently not possible
        # @emitChange()
        # what I have to do instead is access the store from "outside"
        App.Stores.TaskStore.emitChange()
    false # prevent the default change emit, because nothing has changed until the success callback fires

App.Stores.TaskStore = alt.createStore(TaskStore)
```

So as you can see, my action runs and triggers an ajax call.  The state of the store will not have changed until the ajax call completes.  It would be great to be able to emit a change from within that success callback.  What do you think?

**Comment by goatslacker** [comment]
This is on purpose to discourage asynchronous events in stores so they can instead live in utils or as part of actions[1]. Your workaround is fine.

I was actually thinking of including the stores inside the alt instance, what would you think of having `alt.stores.TaskStore` available?


[1]:

```js
class TaskActions
  search: ->
    $.ajax
      url: '/search/tasks'
      method: 'get'
      dataType: 'json'
      data: {q: query}
      success: (results) =>
        @dispatch(results)
  }

class TaskStore
  constructor: ->
    @bindActions(TaskActions)
    @collection = []

  onSearch: (results) ->
    @collection = @collection + results
```

**Comment by goatslacker** [comment]
forgot to mention, you can do

```js
class TodoStore
  onSearch: ->
    $.ajax
      success: (results) ->
        @getInstance.emitChange()
```

**Comment by willcosgrove** [comment]
I didn't know about `@getInstance()`, I definitely prefer that.  As far as making the stores available from Alt, I'm not sure I have much of an opinion on it.  I'm already kind of doing that myself.  I've got a global object named the same as my app, and then I have objects on it for each kind of "component" (component is a bad word... since components are one of the "components").  So basically, I'm doing what you proposed already.  And even if Alt offered it, I would still do it myself, because there are other things to keep track of besides what Alt is managing.

Just my 2¢.

Thanks for the help!  Sorry I'm the only one spamming your issues.  You're about to get another :wink:

**Comment by goatslacker** [comment]
No worries, keep them coming!

**Comment by kentor** [comment]
How would you handle getting cached data from stores if it's available, and making a request if it isn't? Put that logic in the component?

**Comment by willcosgrove** [comment]
I would say that the component would grab all the cached data from the store, and would initially search from that.  Then once the number of results drops below a threshold, I would fire an action to search.  The store would then update it's cache with the results of the search, which would trigger a change event, and the component would refresh it's cache, and the filter would be run again, this time including the results from the search.

Sorry for the run on, I'm on an iPhone, and stream of consciousness took over.

**Comment by goatslacker** [comment]
@willcosgrove out of curiosity, why are you placing the data fetching inside the store rather than in a util or in an action? I'm asking because I'm trying to better understand how people use flux and how that would fit in different environments.
