### ISSUE TITLE
Alt 0.16.8 dispatcher dispatches the event for action function even if dispatch method is not called

### ISSUE THREAD

**Issue by adaniliuk** [goatslacker/alt#301]
Dispatcher dispatches the event for action function even if dispatch method is not called. So in the below case if item is falsy dispatcher calls dispatch internally anyway.

```javascript
add(item) {
  if (!item) return;
  this.dispatch(item);
}
```

**Comment by adaniliuk** [comment]
Probably this is caused by this change https://github.com/goatslacker/alt/commit/460a749c28c0156bbf8bae5e2c791cf3a07f3c42

Will check further.

**Comment by yujingz** [comment]
Same here. My code dispatches data after a async call is finished. Alt 0.16.8 ended up dispatch it twice. One with undefined data, One with valid data
```
  fetchItem(itemId) {
    http.get(`/items/${itemId}`)
    .then((item) => {
       this.dispatch(item)
    })
  }
```
Object {action: Symbol(alt/MainActions.fetchItem), data: undefined, details: Object}
Object {action: Symbol(alt/MainActions.fetchItem), data: Object, details: Object}

**Comment by goatslacker** [comment]
Download 0.16.9 on npm or here:

https://github.com/goatslacker/alt/releases/tag/v0.16.9

Fixed by this commit: 6921567e682eed6a0a0ff400eaace40073f326fd

**Comment by adaniliuk** [comment]
Great, thank you @goatslacker

**Comment by goatslacker** [comment]
I'll be bringing this back in 0.17.0 (because its a breaking change) where if you return undefined it won't dispatch
