### ISSUE TITLE
react & alt + RxJS?

### ISSUE THREAD

**Issue by iyn** [goatslacker/alt#303]
I have a question that is not directly related to the `alt` development but I hope you won't mind me posting it here rather than elsewhere. 

I've been using `react` with `alt` for a few months now and I really like this mix & workflow, I'm way more productive than I was before and it's just more fun. Recently I've read/watch more about `ReactiveX` (http://reactivex.io/) and it seems pretty interesting. The video about Netflix approach to async JS (https://www.youtube.com/watch?v=XRYN2xt11Ek) really made me curious to learn more. I'm interested, if it's possible to somehow combine `react`, `alt` and `RxJS` (https://github.com/Reactive-Extensions/RxJS)? I've found few flux implementations that use `RxJS`, but I'd prefer to stick with `alt` (I've tried multiple flux implementations before and, for me at least, `alt` is the best). My UI is completely separated from the backend, so I communicate with the API pretty heavily - at the moment I use promises to handle async but thought of using techniques that `RxJS` introduces is appealing (particularly after watching the video from Netflix).

I may totally misunderstood the whole concept of `RxJS` - if so, let me know. But maybe the combination of `react`, `alt` & `RxJS` makes some sense - I'd love to read what people think about this. I'm trying to grasp this conceptually, I'd appreciate all input (explanations, ideas, links etc). Thanks :)

**Comment by frederickfogerty** [comment]
Afaik, @goatslacker has added in some FP stuff into alt, such as https://github.com/goatslacker/alt/pull/279. He is currently writing docs for it. 

If you're looking for a reactive flux implementation, take a look at https://github.com/optimizely/nuclear-js

**Comment by goatslacker** [comment]
Hey @iyn sorry for the late reply. Alt has some reactive ideas baked in but RxJS and Alt are two separate things. If you do manage to get all 3 playing nicely together then give me a shout, I'd love to see an example!
