### ISSUE TITLE
Question: Why is "onDeserialize" not utilized on rollback?

### ISSUE THREAD

**Issue by vkbansal** [goatslacker/alt#305]
I have a use case where I'm using `snapshot` and `rollback` and my state objects are Immutable.

So I have the following code
```js
"use strict";

import { createStore } from "../alt";
import { List, fromJS } from "immutable";

import actions from "../actions/my-actions";

@createStore
class MyStore {
    constructor() {
        this.on("serialize", () => {
            return {
                variables: this.variables.toJS()
            };
        });

        this.on("deserialize", (data) => {
            return fromJS(data);
        });

        this.on("rollback", () => {
            this.variables = fromJS(this.variables);
        });

        this.bindActions(actions);

        this.variables = List([]);
    }

}

export default MyStore;
```

I had to implement `rollback` listeners to make it work correctly.

Why can't `deserialize` handle that?

**Comment by goatslacker** [comment]
It should be.

Rollback:

https://github.com/goatslacker/alt/blob/master/src/alt/index.js#L136

calls setAppState:

https://github.com/goatslacker/alt/blob/master/src/alt/utils/StateFunctions.js#L10

**Comment by vkbansal** [comment]
I'll try it once again and let you know.

**Comment by vkbansal** [comment]
I've made a quick demo here: http://vkbansal.github.io/alt-test/

Repo is located here: https://github.com/vkbansal/alt-test

1. Click on `Load Data`
2. Delete some entries
3. Take a snapshot
4. Delete some more entries
5. Rollback

See what happens

**Comment by goatslacker** [comment]
Found the issue, the class should look like this:

```js
class Foo {
  static config = {
    onSerialize(state) {
      ...
    }

    onDeserialize(state) {
      ...
    }
  }
}
```

**Comment by vkbansal** [comment]
Okay. Then apparently your docs aren't updated:
https://github.com/goatslacker/alt/blob/master/docs/utils/immutable.md#serializingdeserializing-immutable-data

**Comment by goatslacker** [comment]
Ouch, thank you!

**Comment by vkbansal** [comment]
Updated and tested the code and it works as intended.

**Comment by jdlehman** [comment]
@vkbansal thanks for catching that. The other serialization docs are up to date, but I missed that page.

Just updated the docs to reflect the actual api.
