### ISSUE TITLE
Add documentation for mixins

### ISSUE THREAD

**Issue by jdlehman** [goatslacker/alt#31]
I did not notice that there were several other mixins available (other than the `ListenerMixin`) until I was going through the source code.  Some have helpful inline docs, but a Mixin section in the README would be very helpful in acquainting users with what is available and a quick example of usage.

**Comment by goatslacker** [comment]
Totally. I have a github pages coming soon and I'll add the docs there.

Moving forward, I'm keeping the readme as a topical guide. The website will have the full nitty gritty API docs.

I'll be adding a mixins section to both so I'll keep this open until I do.

**Comment by goatslacker** [comment]
I'm closing this because I want to leave the mixins undocumented. I believe AltContainer is the future and mixins are dead.

**Comment by jdlehman** [comment]
:+1: to components over mixins
