### ISSUE TITLE
getState setState

### ISSUE THREAD

**Issue by TeckniX** [goatslacker/alt#310]
From the doc, it's a bit weird that the instance has to be retrieved to get the state, but this doesn't matter when setting the state?
From docs `getState`:
```js
class MyStore {
  handleFoo() {

    setTimeout(() => {
      // get state of store instance.
      let state = this.getInstance().getState();
    }, 100);

    // supress emitting a change.
    return false;
  }
}
```
From docs `setState`:
```js
class MyStore {
  handleFoo() {
    this.foo = 0;

    setTimeout(() => {
      // set foo to 1 and emit a change.
      this.setState({
        foo: 1
      });
    }, 100);

    // supress emitting a change.
    return false;
  }
}
```
it would be nice if both of them just used: `this.getState()` and `this.setState()`

**Comment by goatslacker** [comment]
Where is this at?

**Comment by TeckniX** [comment]
@goatslacker within these docs:
http://alt.js.org/docs/createStore/
Look for `StoreModel#setState`
The other one is mentioned under `StoreModel#getInstance`, the doc example is for emitChange(), but it's noted to be the same instance call for getState(). 

I even sent to the console the `this` object and the getState() isn't defined, yet setState() is.

**Comment by goatslacker** [comment]
I don't see where it mentions getInstance().getState() in the docs, you already have access to state inside a store, there's no reason to getState() from there

**Comment by TeckniX** [comment]
@goatslacker it mentions the following `getInstance: This method retrieves the store instance which contains other methods like getEventEmitter(), getState(), and emitChange().`

**Comment by goatslacker** [comment]
I'll remove that bit from getInstance so there's no confusion :)

**Comment by TeckniX** [comment]
Thanks - Although getState isn't availble without getInstance(), correct?

**Comment by david0178418** [comment]
You should be able to access it at this.state in that context.

**Comment by goatslacker** [comment]
Yeah getState isn't and won't be available without getInstance(). getState does a shallow copy so you probably want to use as little of it as possible.

**Comment by TeckniX** [comment]
cool thanks for the follow-up and good explanation
