### ISSUE TITLE
Server side and Flux alt instance(s)

### ISSUE THREAD

**Issue by darul75** [goatslacker/alt#311]
Hi @goatslacker,

I know it has been a big deal to provide all this documentation but I feel still quite confusing with idea of flux on both server and client sides.

I try to follow documentation to create a Flux instance on each request on server side and pass this flux instance to all my components.

Then on client side, I try to understand what I need to do, looking at iso example too https://github.com/goatslacker/iso

But difference between singleton (and flush on every request) and not singleton is quite difficult to understand for me now :) keep looking..

If you can describe the main difference of singleton vs multi-instances and impacts, by instance passing flux to all components looks weird ;)

Thx,

Julien

**Comment by goatslacker** [comment]
The singleton model is a bit easier to understand and follow and you don't have to pass the instance around your app through props or as context.

**Comment by darul75** [comment]
Ok thanks for clarifying it
