### ISSUE TITLE
Remove v0.17.0 tag

### ISSUE THREAD

**Issue by david0178418** [goatslacker/alt#313]
It seems the v0.17.0 tag was made prematurely.  As of now, that tag is older than v0.16.10.

This causes an issue in bower where bower install alt is installing the outdated 17 vs the latest 16.  I imagine that the intention is to publish the latter.  If so, then you may want to see about nixing that tag.

**Comment by goatslacker** [comment]
oh thanks, will do.

**Comment by mathieul** [comment]
That'd be really nice to remove this tag. When you install alt using bower with `bower install alt --save`, you automatically get 0.17.0. It took me a while to figure out why the code was out of sync with the documentation (the documentation is really amazing by the way :+1:).

**Comment by goatslacker** [comment]
Done

**Comment by mathieul** [comment]
Thanks :smiley:
