### ISSUE TITLE
Confusing isomorphic documentation in README.md

### ISSUE THREAD

**Issue by wonnage** [goatslacker/alt#314]
https://github.com/goatslacker/alt/blame/master/README.md#L745 is really confusing. 

1. I thought Alt was a standalone implementation of design pattern used in Flux? Why is it suddenly talking about creating instances of flux? What is meant by "flux" in this context? It's confusing to use "alt" and "flux" interchangeably. 

2. How does creating multiple instances of alt/flux help with isomorphic rendering? You say it's similar to how fluxible does it, but in what way? 

3. The code snippet uses document.body and React.render which would not be available on the server.

**Comment by goatslacker** [comment]
Alt is flux. Both terms can be used interchangeably since flux is just an idea and alt is the implementation of that idea.

I'll amend the README to get into specifics in how it helps with server side rendering and I'll split up the document.body stuff.

**Comment by goatslacker** [comment]
https://github.com/goatslacker/alt/commit/6ece83fa5521e398122a1cd175c1e8d9f9c1b2da

**Comment by wonnage** [comment]
awesome, thanks for clearing that up :)
