### ISSUE TITLE
Alt is swallowing errors in a store

### ISSUE THREAD

**Issue by iamnirav** [goatslacker/alt#315]
`throw new Error('derp');` doesn't throw an error :cry:

**Comment by goatslacker** [comment]
This is a promise error

**Comment by iamnirav** [comment]
So what's the resolution/workaround?

**Comment by goatslacker** [comment]
Resolved by upgrading to 0.16.10 which reverses the then/catch handlers in data sources.

**Comment by iamnirav** [comment]
Cool, thanks! :+1:
