### ISSUE TITLE
imports not available in store methods

### ISSUE THREAD

**Issue by iamnirav** [goatslacker/alt#316]
```js
import alt from '../flux/alt';
import MyActions from '../actions/MyActions';

class MyStore {
  constructor() {
    this.bindActions(MyActions); // works fine
  }

  mySpecificAction() {
    MyActions // not defined
    alt // not defined
  }
}

export default alt.createStore(MyStore, 'MyStore');
```

**Comment by goatslacker** [comment]
```js
import Alt from 'alt';

const alt = new Alt()

const MyActions = alt.generateActions('mySpecificAction')

alt.createStore(class MyStore {
  constructor() {
    this.bindActions(MyActions); // works fine
  }

  mySpecificAction() {
    console.log(alt)
  }
})

MyActions.mySpecificAction()
```

I get the console.log to output fine here

**Comment by transedward** [comment]
I run into kind of the same issue, but even worse
![screen shot 2015-06-16 at 3 22 53 pm](https://cloud.githubusercontent.com/assets/7189930/8177984/c5748d7e-143c-11e5-8f3a-7f07df9f778c.png)
I have two stores in same folder requiring same ServerActions
I use debug in both constructor but one got undefined, one got the actual object.
this is kind of weird, I tried with the latest version of iojs or 
`rm -rf node_module && npm cache clean && npm i ` and whatever things I can think of
but still failed

@goatslacker , what might other possible reason??

**Comment by transedward** [comment]
These are the basic snipper I did
```js
// ServerActions.js
'use strict';

import alt from '../alt';
import debug from 'debug';

const debugServerActions = debug('messag:serverActions');

class ServerActions {
    login() {
       // some codes here ...
    }

    logout(){
      // other codes
    }
}

export default alt.createActions(ServerActions);

// AuthStore.js
'use strict';

import alt from '../alt';
import ServerActions from '../actions/ServerActions';
import debug from 'debug';

const debugAuthStore = debug('messag:AuthStore');

class AuthStore {

  constructor() {
    debugAuthStore('ServerActions', ServerActions);

    this.bindActions(ServerActions);
    this.state = {
    };
  }

  login(){
  }

  logout(){
  }
}

export default alt.createStore(AuthStore, 'AuthStore');

// and the same in ThreadStore.js
```

**Comment by iamnirav** [comment]
I found that actually `debugger` doesn't always have access to all references in the current context. This is due to some browser implementation details—there are vague references to this around the internet (though I can't seem to find one right now :disappointed: ).

**Comment by goatslacker** [comment]
This is an issue with chrome's debugger and keeping closed over references in context when using things like eval or Promises. From what I understood, it's a wontfix on their end because resolving the scope every time is a massive perf hit and this was sort of edge case, now with promises being used more in the wild I'm not sure what they'll come up with.

**Comment by david0178418** [comment]
@iamnirav I've run into that.  I always assumed it to be the result of a runtime optimization off some sort. It's you assign out to a temporary variable in the scope you need to debug, you can access it.
