### ISSUE TITLE
connectToStores clobbers existing statics

### ISSUE THREAD

**Issue by wonnage** [goatslacker/alt#317]
If you have any statics on the component wrapped by connectToStores, they'll become inaccessible afterwards.

**Comment by goatslacker** [comment]
Yeah this is known. There isn't really a good solution that I know of. Current workaround is to define your own HoC that has the static properties.

I can maybe provide this as an addon?

**Comment by goatslacker** [comment]
https://github.com/goatslacker/alt/blob/master/src/utils/statics.js
