### ISSUE TITLE
Noob: Can I <script> src or do I need to use a module loader?

### ISSUE THREAD

**Issue by anjdreas** [goatslacker/alt#329]
With react, reflux, react-router and others I can simply `<script>` source these things during development and not bother setting up webpack or browserify. I tried this with alt.js, but I can't see it as `window.Alt` or similar?

I'm using this "browser build" from the getting started guide: https://cdn.rawgit.com/goatslacker/alt/master/dist/alt.js

I'm kind of new to all this, so it's probably a rookie mistake. Any pointers would be appreciated.

**Comment by froatsnook** [comment]
I use `dist/alt-with-addons.js` with a `<script>`!

**Comment by anjdreas** [comment]
How exactly do you use alt then? I can source it, but I don't see how to access it.
Do you use it like this?

`window.alt.createStore(TodoStore, 'TodoStore');`

**Comment by froatsnook** [comment]
The script only creates `window.Alt`.  So first do `alt = new Alt()`

**Comment by goatslacker** [comment]
<script src="https://cdn.rawgit.com/goatslacker/alt/master/dist/alt.js"></script>
<script>var alt = new window.Alt();</script>

**Comment by anjdreas** [comment]
Thanks guys.
