### ISSUE TITLE
Issue with Store.listen/Store.unlisten in ES6 and .bind(this)

### ISSUE THREAD

**Issue by eisisig** [goatslacker/alt#33]
I'm using React 0.13-rc and writing the components in ES6

The problem is that when the callback method is bound to `this`in both the listen and unlisten calls the  event isn't removed in the "removeListener". So next time the component loads the callback is added again, then again, and...

```js
class MyComponent extends React.Component {
	componentDidMount () {
		MyStore.listen(this.onStoreChange.bind(this));
	}
	componentWillUnmount () {
		MyStore.unlisten(this.onStoreChange.bind(this));
	}
	onStoreChange () {
		// Event "change" is not removed so on next "onStoreChange"
		// it will be called 2, then 3, 4.... Because it was added again in the
		// componentDidMount method
	}
}

class MyComponent extends React.Component {
	componentDidMount () {
		MyStore.listen(this.onStoreChange);
	}
	componentWillUnmount () {
		MyStore.unlisten(this.onStoreChange);
	}
	onStoreChange () {
		// This works but "this" is the wrong context so no `this.setState()`
	}
}
```
Any ideas? I'm not really sure why this would be a problem. I'll look into it but hopefully this is something easy and I'm missing something ;)

P.S. Great work! Im loving Alt (used reflux) and tried all the others

**Comment by goatslacker** [comment]
Yeah the solution is quite easy :)

```js
class MyComponent extends React.Component {
  constructor() {
    this.onStoreChange = this.onStoreChange.bind(this);
  }
  componentDidMount() { 
    MyStore.listen(this.onStoreChange);
  }
  componentWillUnmount() {
    MyStore.unlisten(this.onStoreChange);
  }
}
```

**Comment by eisisig** [comment]
Maaan... Makes me feel silly :) Thanks man!

But this works really strange to me. Is this a ES6 thing or? Do you know that

**Comment by frederickfogerty** [comment]
@eisisig http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding

**Comment by eisisig** [comment]
@frederickfogerty ahhh had forgotten this :-/ Maybe a time for the bed... :) Thanks for the help guys! :+1:

**Comment by goatslacker** [comment]
No worries. Is what an ES6 thing? The lack of mixins/traits, yes. The binding, that's just a JS thing.

**Comment by eisisig** [comment]
No I was wondering about the .bind(this)... Forgot that React doesn't autobind in 0.13... :)

**Comment by frederickfogerty** [comment]
@goatslacker just realised I linked the same link as you, oops!
