### ISSUE TITLE
Dependencies between normalized stores?

### ISSUE THREAD

**Issue by clessg** [goatslacker/alt#330]
I'm pretty new to Flux, and I'm having some trouble understanding a few things.

For some extra fun, let's use Pokemon as an example. Imagine the player is in a battle. The various parts of the `Battle` component are:

- The Pokemon you have in play, its level, its HP and its EXP.
- The Pokemon the enemy has in play, its level and its HP.

Imagine that somewhere else on the page, there is a `PokemonList` component that shows every Pokemon in the `PokemonStore`, and the information therein must be kept in sync with the Pokemon in the battle. Thus, changing the player Pokemon's HP could change two otherwise unrelated components, `Battle` and `PokemonList`.

We might have a `PokemonStore` and a `BattleStore`. The `BattleStore` may look like:

    {
      playerPokemonID: 1,
      enemyPokemonID: 2
    }

Given a `PokemonStore` such as:

    {
      1: { name: 'Bulbasaur', level: 5, hp: 10, exp: 125 },
      2: { name: 'Charmander', level: 5, hp: 12, exp: 125 }
    }

Our `Battle` view would then depend on `BattleStore`. But would it also depend on `PokemonStore`, considering `BattleStore` is normalized? I suppose that it may look like this:

    @connectToStores
    class Battle extends React.Component {
      static getStores() {
        return [BattleStore, PokemonStore];
      }

      static getPropsFromStores() {
        return {
          playerPokemon: PokemonStore.getByID(BattleStore.getState().playerPokemonID),
          enemyPokemon: PokemonStore.getByID(BattleStore.getState().enemyPokemonID)
        };
      }
    }

Would this be the proper way to handle computed state? It doesn't really feel right to me to be doing this in the view. If later on, we decide to add double or triple battles, or add more state to the `BattleStore`, the view's reduction logic will continue to get more complex.

Another way would be to have a single getter on the `BattleStore` and move the dependency on `PokemonStore` into `BattleStore`:

    class BattleStore {
      static getBattle() {
        const state = this.getState();

        return {
          playerPokemon: PokemonStore.getByID(state.playerPokemonID),
          enemyPokemon: PokemonStore.getByID(state.enemyPokemonID)
        };
      }
    }

    @connectToStores
    class Battle extends React.Component {
      static getStores() {
        return [BattleStore];
      }

      static getPropsFromStores() {
        return BattleStore.getBattle();
      }
    }

This introduces a direct dependency on `PokemonStore` in the `BattleStore`'s getter. This does work, but if the `PokemonStore` updates, the `Battle` view will not be notified. To fix this, we can listen to any `PokemonActions` and use `waitFor` to ensure we don't get stale data.

    class BattleStore {
      constructor() {
        this.bindAction(PokemonActions.changePokemonHP, this.onPokemonHPChanged);
      }

      onPokemonHPChanged() {
        this.waitFor(PokemonStore);
      }
    }

Now the view will be properly notified whenever the Pokemon's HP changes.

Unfortunately, we will have to add a new action handler in `BattleStore` for almost every Pokemon action: `changePokemonEXP`, `changePokemonLevel`, etc., all of which simply invoke `waitFor`. Otherwise the view won't be notified.

What would be the proper way to handle this without denormalizing the stores?

**Comment by srph** [comment]
Why not have a `PokemonStore` and `EnemyPokemonStore`? What's stored in both stores are both the pokemons in use.

**Comment by vkbansal** [comment]
@clessg Any progress on this? I too am in a similar situation.

The talk below from react-europe also talks about similar situation.
https://www.youtube.com/watch?v=Uu4Yz2HmCgE

**Comment by clessg** [comment]
I've been using Redux lately, and [Redux has good information on the subject](http://rackt.github.io/redux/docs/advanced/AsyncActions.html). Basically: keep things normalized, and use "selectors" to compute derived state.

Because Redux doesn't dispatch until all reducers have updated, there is no need for `waitFor`. To have computed state, [you can use reselect](http://rackt.github.io/redux/docs/recipes/ComputingDerivedData.html). Everything is very efficient and results are memoized.

I still haven't figured it out in normal Flux. `waitFor` is problematic. I would avoid it and instead compute state in the view (or extract that logic into a function of some sort). Unfortunately that has problems of its own.

**Comment by vkbansal** [comment]
I have a huge app and migrating is not an option for me. Thanks anyways,

**Comment by taion** [comment]
Broadly, you have 3 options here:

- Merge your stores
- Use `waitFor`
- Break up your dispatch into multiple actions in sequence (most likely with an action creator method) that the different stores listen to
