### ISSUE TITLE
Pass in values for data source async methods?

### ISSUE THREAD

**Issue by eventhough** [goatslacker/alt#331]
I'm implementing [async](http://alt.js.org/docs/async/) for one of my stores and I want to know if it's possible to pass values into async methods (ex: `.performSearch()`).

For example, what if we want to load data from the server via one of our sources but we also need to provide default query parameters? It seems weird that I would need to somehow store these defaults into state so that I could access them in my data source.

Another use case - what if we need to load a parameter from the URL for a rowId and use the id within our data source? How would the data source access the URL without having it set in store state? Thanks!

**Comment by eventhough** [comment]
Okay, clearly I spoke way too soon because I just randomly decided to test passing in additional context via async functions from my store and it looks like these context variables are being passed through to the data source. Maybe it would be good to add this to the docs?

**this works:**
```javascript
SomeStore.performFind('hello', 'goodbye');

performFind: {
    remote(state, foo, bar) {
      console.log('remote:', foo); // `remote: hello`
      console.log('remote:', bar); // `remote: goodbye`
      return ComplaintApi.find(state.defaultFindQuery);
    },

    local(state, foo, bar) {
      console.log('local:', foo);
      console.log('local:', bar);
      return state.records;
    },

    shouldFetch(state, foo, bar) {
      console.log('should:', foo);
      console.log('should:', bar);
      return true;
    },
    ....
  }
```

**Comment by goatslacker** [comment]
yup that does work:

It's already listed in the docs: http://alt.js.org/docs/async/#remotestate-object-args-any

**Comment by eventhough** [comment]
Thanks for the response.
