### ISSUE TITLE
this.dispatch & this.actions are not accessible in React Native.

### ISSUE THREAD

**Issue by danscan** [goatslacker/alt#332]
When using an ActionsClass to create actions, `this.dispatch` and `this.actions` are undefined from within action methods.  

Source:

```javascript
var alt = require('../alt')

// Load utils
var APIUtils = require('../utils/APIUtils')

class SessionActions {
  constructor() {
    this.signInSuccess = this.signInSuccess.bind(this)
    this.signInError = this.signInError.bind(this)
  }

  signIn(userId, password) {
    console.log('this.dispatch:', this.dispatch)  // this.dispatch: undefined
    APIUtils.signIn(userId, password)
      .then(this.signInSuccess)
      .catch(this.signInError)
  }

  signInSuccess(user) {
    console.log('SessionActions#signInSuccess user:', user)
    console.log('this.dispatch:', this.dispatch)  // this.dispatch: undefined
    this.dispatch(user)
  }

  signInError(error) {
    console.log('SessionActions#signInError error:', error)
    console.log('this.dispatch:', this.dispatch)  // this.dispatch: undefined
    this.dispatch(error)
  }
}

module.exports = alt.createActions(SessionActions)
```

**Comment by danscan** [comment]
I've tried with ReactNative latest stable, and 0.6.0-rc (which moved from JSTransform to babel)

**Comment by goatslacker** [comment]
that looks fine, you actually don't have to bind to this in the constructor.

**Comment by hiro1107** [comment]
Hi, is this issue solved? I currently have same problem. 

    import alt from '../alt';
    import ApiConstants from '../constants/ApiConstants';
    import AuthApiUtils from '../utils/AuthApiUtils';
    import logError from '../utils/logError';
    
    class UserActions {
      login(email, password) {
        AuthApiUtils.loginWithEmail(email, password).then(
          (data) => {
            this.actions.loginSucceeded(data);
          }
        ).catch(logError);
      }
      loginSucceeded(data) {
        this.dispatch(data);
      }
    }
        
    export default alt.createActions(UserActions); 


this.dispatch is undefined.

**Comment by magrinj** [comment]
Hello, 

if you use the latest alt version or over `0.18` this.dispatch was removed: [Change](https://github.com/goatslacker/alt/blob/master/CHANGELOG.md#breaking-changes)
