### ISSUE TITLE
Multiple component

### ISSUE THREAD

**Issue by isergey** [goatslacker/alt#338]
Hello!
Please tell me how to organize actions and storages, if I have the same component running in multiple instances. For example, 2 task list (Component ToDo), or 2 carts (Cart). What to do when want to dynamically add another component, such as adding another task list to the page by clicking Add button? 

Do I need to create for a new ToDo one more sorage and actions, or to make separation data within existing?

Thank for answer and cool library!

**Comment by jdlehman** [comment]
Hi @isergey.  You can approach this problem in the same manner that you keep track of todo items in the todo list.  So your todo list might have its data in an array in a store.  You take this same strategy and have an array of todo lists, where each task list has a list of todo items.

To add dynamically, you can add an action that adds an item to the todo list array in your store.  Then your render function just needs to iterate over each todo list (and over each todo list's items if you want to display those as well).
