### ISSUE TITLE
store#listen ignores store.config.getState

### ISSUE THREAD

**Issue by ryanfields** [goatslacker/alt#339]
Handlers passed to store#listen receive the result of Alt's default getState implementation, rather than the result of calling my store.config.getState implementations.

**Comment by goatslacker** [comment]
You mean the state passed to listen?

**Comment by goatslacker** [comment]
Yeah getState override is just supposed to override getState. Not what's passed to listen. You may want to check out the output method.

**Comment by ryanfields** [comment]
That feels counterintuitive.  If I've overridden getState, I feel like I'm saying to Alt "whenever something asks for state from this store, this is the representation of state that should be delivered".  Is there a reason that listen should not offer up the same state representation as getState?

Also, what output method are you referring to?

**Comment by goatslacker** [comment]
Oops I don't think I have docs for that. I'll get that fixed. 

getState is just meant to be a convenience to access state. State is normally accessed via the listener though. And output controls what gets sent there. 

I'll write up some docs for it

**Comment by goatslacker** [comment]
https://github.com/goatslacker/alt/commit/6dd01d4d1043a7bbf9c68873161e736f4698a1b3
