### ISSUE TITLE
Own state in combination with ReactStateMagicMixin

### ISSUE THREAD

**Issue by philippotto** [goatslacker/alt#34]
Is it possible to add own properties to the state, if it is managed by the ReactStateMagicMixin? Or should be everything put into stores?

Maybe the need for additional properties also means that one should refactor the component? I'm not sure about this. Would be interested in hearing some opinions.

**Comment by goatslacker** [comment]
It's possible to add your own properties to state.

```js
var React = require('react')
var Alt = require('alt')

var alt = new Alt()

var ReactStateMagicMixin = require('alt/mixins/ReactStateMagicMixin')

var FooStore = alt.createStore(function () {
  this.test = 'hello'
}, 'FooStore')

var Foo = React.createClass({
  mixins: [ReactStateMagicMixin],

  statics: {
    registerStores: {
      foo: FooStore
    }
  },

  getInitialState: function () {
    return {
      world: 'world'
    }
  },

  componentWillMount: function () {
    this.setState({ excl: '!' })
  },

  render: function () {
    return React.DOM.div(null, this.state.foo.test + ' ' + this.state.world + this.state.excl)
  }
})

var str = React.renderToString(React.createElement(Foo))

console.log(str) // <div>hello world!</div>
```

The recommended pattern is to only add in any component specific state to your component. Examples include: `isModalOpen`, `classHidden`, `tooltipOn`, etc...

Put everything else (any business state) in stores.

**Comment by philippotto** [comment]
Ah, cool, I wasn't aware that `setState` merges the parameter object into the old existing state. That's why I thought that the state would get overwritten, when I looked at the mixin source code. Thank you!
