### ISSUE TITLE
connectToStore context

### ISSUE THREAD

**Issue by asaf** [goatslacker/alt#341]
Hey,

I've seen some new commits related to passing context for the `connecToStore` higher order components but i'm still having a problem accessing the context in my wrapped component,

In my top app component, I pass `Alt` instances via:
```js
getChildContext () {
         return { alt: alt };
}
```

then in child components, I can access the correct `Alt` instance via context, ie:
```js
componentDidMount() 
   this.context.alt.getActions('myActions').niceAction('foo');
 }
```
Unfortunately, when using `connectToStore: contextTypes` React won't expose the context, I guess this is because `connectToStore` component has no `contextTypes` defined,

If i'm talking nonsense please let me know what would the appropriate approach to propagate context properly :)

Thanks

**Comment by goatslacker** [comment]
yeah makes sense, wonder if i should provide a context type for connectToStores

**Comment by asaf** [comment]
@goatslacker Do we have any other alternatives?, I wonder if there's an elegant way just to propagate the entire context as is, i'm super new to React but this may be related: https://github.com/facebook/react/pull/3615

**Comment by goatslacker** [comment]
Yeah React is switching to parent based contexts. I think just defining the context in your parent element and passing it down using getChildContext will provide context for any children.

**Comment by dbatiste** [comment]
I know this issue is closed, but I thought I would leave a comment with my findings in case anyone else is having trouble with this.  When using the connectToStores decorator, the parent-defined context is not propagated:
```
@connectToStores
class Application extends React.Component {
    ...
}
Application.contextTypes = {
	myFunc: React.PropTypes.func
};
export default Application;
```
However, I've found that explicitly calling `connectToStores` results in the React context being propagated as expected.  For example:
```
class Application extends React.Component {
    ...
}
Application.contextTypes = {
	myFunc: React.PropTypes.func
};
export default connectToStores(Application);
```
