### ISSUE TITLE
Best place to call async functions?

### ISSUE THREAD

**Issue by milesj** [goatslacker/alt#346]
First off, awesome project, loving every bit of it. 

My question is in regard to async calls, as I haven't seen an answer for this in the docs. I currently have an AuctionStore, registered with an AuctionSource, which defines a fetchAuctions call.

Is the `componentDidMount()` still the best place to trigger this call? For example:

```javascript
import React from 'react';
import BindStores from 'alt/utils/connectToStores';
import AuctionStore from 'stores/AuctionStore';

@BindStores
export default class AuctionList extends React.Component {
    static getStores() {
        return [AuctionStore];
    }

    static getPropsFromStores() {
        return {
            auctions: AuctionStore.getState().auctions
        };
    }

    componentDidMount() {
        AuctionStore.fetchAuctions();
    }
    
    render() {
        // ...
    }
}
```

It seems very inefficient as the initial render occurs with empty/no props, and then re-renders again once the AJAX request finishes. I've tried moving the call to `componentWillMount()`, which sped it up a bit, but still seems janky.

Do you have a suggestion on speeding up this process? Or do I have to manually trigger these AJAX calls preemptively before the specific component will be used, so that the stores state is already ready.

**Comment by srph** [comment]
[Resolves](//github.com/ericclemmons/react-resolver)?

**Comment by milesj** [comment]
I was thinking about this a bit more. Couldn't we move the async calls to `getPropsFromStore()`, since the `local()` method returns the state anyways (if it exists), else returns null? We'd simply have to handle the null/empty state in the `render()` method.

```javascript
static getPropsFromStores() {
        return {
            auctions: AuctionStore.fetchAuctions()
        };
    }
```

Not sure if this would have any side effects though.

**Comment by daniellacosse** [comment]
What would be wrong with placing that call in the constructor?

**Comment by milesj** [comment]
Nothing I believe. JW what the ideal/most efficient way to do this is.

**Comment by goatslacker** [comment]
You may want to follow the development of: https://github.com/goatslacker/alt/blob/master/src/utils/Render.js which does what you want it to do.

It'll not render the component until it fetches the data.

**Comment by milesj** [comment]
Interesting. Any example on how to use it?

**Comment by goatslacker** [comment]
There aren't any full fledge examples just yet.

**Comment by goatslacker** [comment]
Closing in favor of #300
