### ISSUE TITLE
How to test action callbacks in stores?

### ISSUE THREAD

**Issue by georgwiese** [goatslacker/alt#35]
If I have a store like this:

```javascript
module.exports = alt.createStore(class SomeStore {

  constructor() {
    this.bindActions(SomeActions);
  }

  onSomeAction(parameter) {
    // Code to test...
  }

});
```

How would I test `onSomeAction()`?

I can't find a way to call this method from the test as it is not accessible from the outside. I also tried calling `SomeActions.someAction()` from the test, but `onSomeAction()` didn't end up being called.

What is the recommended way of doing this?

**Comment by goatslacker** [comment]
This is a good question. One way is to export the class itself `SomeStore` so you can access its internal components.

**Comment by bizmurr** [comment]
Hm, so would you define `SomeStore`, and then do alt.createStore(SomeStore), and then export `SomeStore`?

**Comment by goatslacker** [comment]
You can have two files if you want to export a single thing from each file. The "Store Model" (SomeStore) and then the Alt Store instance (alt.createStore(SomeStore)). Or you can export them both from a single file.

This is similar to the old question on how do you test private state within an application.

```js
var x = [];


// how to test?
function addtox(y) {
  return x.push(y);
}

module.exports = function () {
  // does something else
}
```

**Comment by georgwiese** [comment]
But don't I also need access to the `store` instance in [this line](https://github.com/goatslacker/alt/blob/master/src/alt.js#L269) if I'm using `this` in the private method?

How would I call the function?

```javascript
SomeStoreClass.prototype.onSomeAction.call( /* what? */, parameter );
```

**Comment by troutowicz** [comment]
You could create a new class that extends SomeStore

```javascript
class SomeStore {

  constructor() {
    this.bindActions(SomeActions);
  }
  
  onSomeAction(parameter) {
  	this.foo = parameter;
  }
}

class OtherStore extends SomeStore {

  constructor() {}

  onSomeAction(parameter) {
  	super.onSomeAction(parameter);
  }
}

var otherStore = new OtherStore();
otherStore.onSomeAction('bar');

console.log(otherStore.foo === 'bar');
```

**Comment by goatslacker** [comment]
@georgwiese from the example listed above it would be quite simple as long as the method you're calling is isolated to the store.

```js
class SomeStore {

  constructor() {
    this.bindActions(SomeActions);
  }

  onSomeAction(parameter) {
    // Code to test...
  }

}

// tests.js

// You would need to mock bindActions.
var someStore = new SomeStore();

// test onSomeAction
someStore.onSomeAction('foo');
```

**Comment by georgwiese** [comment]
I see. It's not really optimal, because the object is different from the object being used in the application. Also, you'd have to mock any methods that `alt.createStore()` adds to the object, like `bindActions()`, `getInstance()`, ....

Are there any plans to make testing easier, e.g. by making private methods accessible via a semi-secret `_privateMethods` hash?

**Comment by philippotto** [comment]
I agree with @georgwiese. The "semi-secret" `_privateMethods` object could hold the methods bound to the right [context](https://github.com/goatslacker/alt/blob/master/src/alt.js#L269). So that testing would be as easy as `someStore._privateMethods.someMethod()`.

Then the behaviour of the methods should be exactly like it would when called by the dispatcher. Additionally, one wouldn't have to export additional objects for the sole purpose of testing.

**Comment by jdlehman** [comment]
I ran into this problem recently as well, but found a rather elegant way to get around it using ES6 modules. (you can probably do the same thing with require's named modules, but I am going to use ES6 modules syntax here).  As a note, I am compiling my code with [webpack](https://github.com/webpack/webpack) and [babel-loader](https://github.com/babel/babel-loader).

Here is how I define my store:
```javascript
// stores/MyStore.js
import alt from 'AppAlt'; // my app's instance of alt

export class MyStore {
  constructor() {}

  myMethod() {
   console.log('you found me');
  }

  static myStaticMethod() {
    console.log('already accessible');
  }
}

export default alt.createStore(MyStore, 'MyStore');
```

```javascript
// MyStore_test.js

import AltWrappedStore, {MyStore as UnwrappedStore} from 'stores/MyStore';

// we can already do this, so no surprises here
AltWrappedStore.myStaticMethod(); //=> "already accessible"
UnwrappedStore.myStaticMethod(); //=> "already accessible"

// now we can access instance methods on our unwrapped store, which is just the class
var wrapped = new AltWrappedStore();
wrapped.myMethod(); //=> Error
var unwrapped = new UnwrappedStore();
unwrapped.myMethod(); //=> "you found me"
```

**Comment by goatslacker** [comment]
@jdlehman++

**Comment by goatslacker** [comment]
I'm keeping this ticket open so I can provide some examples on how to test stores.

I'll do jest and mocha.

@georgwiese @philippotto would it be better if alt came with some built-in utils to mock these functions?

The object used in the application (the Alt Store) and the object defined (the Store Model) are two separate things that can be tested independently.

**Comment by troutowicz** [comment]
We could get a little creative :)

https://gist.github.com/troutowicz/d9dcb7e7e9e77032f602

```javascript
const Alt = require('alt');
const alt = new Alt();
// const AppActions = require('../actions/AppActions');

class SomeStore {
  constructor() {
    // this.bindActions(AppActions);
    
    this.foo = '';
  }
  
  onSomeAction(val) {
    this.foo = val;
  }
}

const AltWrappedStore = alt.createStore(SomeStore);
const UnwrappedStore = AltWrappedStore[Object.getOwnPropertySymbols(AltWrappedStore)[2]];

UnwrappedStore.onSomeAction('bar');

console.log('foo == ' + AltWrappedStore.getState().foo);
```

**Comment by goatslacker** [comment]
Clever :)

**Comment by philippotto** [comment]
@goatslacker Yes, I think some built-in utils for mocking would be nice. For the sole purpose of documenting an idiomatic way of how to test stores in alt it would be appropriate, I think.

**Comment by georgwiese** [comment]
That sounds good, thanks in advance :)

**Comment by troutowicz** [comment]
@georgwiese @philippotto 

I know I didn't really explain my snippet above, but it does everything you want. Alt uses symbols to manage internal 'alt wrapper' class properties. They are semi-private by design, and this gives a way to obtain the original store class.

**Comment by georgwiese** [comment]
@troutowicz Yes, I got that and I think it is the best solution so far :) Still it would be good to have an "official" way (that is more stable than relying on Symbol indices) and examples.

**Comment by troutowicz** [comment]
Sure, having to rely on symbol index is not ideal. But remember, alt makes this difficult intentionally. The stores are meant to be immutable by everything other than actions. In the case of unit tests, I don't see a problem with having to reference the correct symbol index.

**Comment by goatslacker** [comment]
Created an issue to track publishing the example #45

**Comment by goatslacker** [comment]
I added an [AltTestingUtils](https://github.com/goatslacker/alt/blob/master/utils/AltTestingUtils.js) on commit 10f38648cad65628b9668e783af5dd70b44a3954 which auto-stubs `bindActions` and friends for you. 

There's also the [testing stores documentation](https://github.com/goatslacker/alt/blob/master/docs/testing/stores.md) which @jdlehman mostly wrote. In there you'll find an example on how to use AltTestingUtils, the same example can be found in [alt's own tests](https://github.com/goatslacker/alt/blob/master/test/testing-utils.js) .

And finally I've documented how to use jest to test here: 182f8365526b34961fabe3cbcf3a013b9b5a2778

The [chat example](https://github.com/goatslacker/alt/tree/master/examples/chat) now includes [full working jest tests](https://github.com/goatslacker/alt/tree/master/examples/chat/js/stores/__tests__).

**Comment by goatslacker** [comment]
If there's something I didn't cover mention it and we can open a new ticket for it.

**Comment by georgwiese** [comment]
@goatslacker Thanks a lot! Great support :)

**Comment by chrisdibble** [comment]
Sorry to reopen a year old dialog, but was AltTestingUtils removed from the repo?

**Comment by goatslacker** [comment]
It's here now https://github.com/altjs/utils
