### ISSUE TITLE
Allow using `this` in actions.

### ISSUE THREAD

**Issue by DanielSundberg** [goatslacker/alt#351]
I'm trying to figure out how to unit test my store and actions. I have the following actions class:

```javascript
import SystemSettingsResource from 'SystemSettings';

class MyActions {
    constructor() {
    }

    saveSetting(setting) {
        SystemSettingsResource.Save(setting);
    }
}
export default alt.createActions(MyActions );
```

Now I want to test this with a mocked SystemSettingsResource. Normally I would refactor the MyActions class to take this resource as a dependency in the constructor :

```javascript
class MyActions {
    constructor(systemSettingsResource) {
        this.systemSettingsResource = systemSettingsResource;
    }

    saveSetting(setting) {
        this.systemSettingsResource.Save(setting);
    }
}
```

However, this doesn't play well with `export default alt.createActions(CaseActions);`. I've tried to study docs and examples but I havn't really found anything useful. I've seen docs about creating an "Unwrapped" instance of the action class. Is that the proposed solution in this case?

**Comment by jdlehman** [comment]
You can pass arguments to your constructor from `alt.createActions`'s third argument.

Do something like:
`` `js
export default alt.createActions(CaseActions, {}, systemSettingsResource, otherConstructorArg)
```

This will allow you inject your dependencies and test that way. 

Another strategy would be to use something like [sinon](http://sinonjs.org/) and mock the prototype of the SystemSettingsResource.

**Comment by DanielSundberg** [comment]
@jdlehman, _otherConstructorArg_ is exactly what I need! Didn't find that in the docs.

**Comment by jdlehman** [comment]
Awesome, I will add that now to make sure no one else has the same problem.

**Comment by DanielSundberg** [comment]
Still can't get it to work. Maybe it's my ES6 knowledge that's missing. I changed my code to do the following:

```js
import SystemSettingsResource from 'SystemSettings';

class MyActions {
    constructor(systemSettingsResource) {
        this.systemSettingsResource = systemSettingsResource;
    }

    saveSetting(setting) {
        this.systemSettingsResource.Save(setting);
    }
}
export default alt.createActions(MyActions, {}, SystemSettingsResource );
```

In the `saveSetting` method `this.systemSettingsResource` doesn't exist. When debugging I can see that `this` is something different in the constructor (ActionCreator) than in the method (AltAction). How can I save the constructor argument for later usage?

**Comment by goatslacker** [comment]
Stuff (this) in actions is currently hijacked :(

**Comment by jdlehman** [comment]
we should also make sure we add some regression tests for this.

**Comment by DanielSundberg** [comment]
Ok, sounds great!

**Comment by ziflex** [comment]
@goatslacker is it still relevant ? I ran some tests and it looks like it works now.

**Comment by goatslacker** [comment]
If you ran tests on master then it works.

**Comment by ziflex** [comment]
@goatslacker yep, on master.

**Comment by kandaraj** [comment]
You could do something like this.

```constructor(systemSettingsResource) {
        MyActions.systemSettingsResource = systemSettingsResource;
}```
