### ISSUE TITLE
connectToStores doesn't update props-from-stores on mounted components

### ISSUE THREAD

**Issue by necolas** [goatslacker/alt#358]
`connectToStores` doesn't update the props it provides to a component when that component is re-rendered (i.e., already mounted). it re-renders the component when a store emits a change event, but I got caught out assuming that the props it initially sources from stores would be re-evaluated each time the component is rendered (since it is meant to allow you to "use this.props like normal"). in contrast, `AltContainer` re-evaluates props-from-stores via `componentWillReceiveProps`.

is this a bug in `connectToStores`, or the unintended use of the util?

**Comment by goatslacker** [comment]
Let me write a fail test for this

**Comment by goatslacker** [comment]
Intended use. Props are only eval'd [onChange](https://github.com/goatslacker/alt/blob/master/src/utils/connectToStores.js#L78).

**Comment by goatslacker** [comment]
ca7f455e89ea0f9a3b3c7e15f21bc7c10b870aca

**Comment by necolas** [comment]
Are you preparing for a bigger release? Is this patch something we should apply to a fork and depend on until then?

**Comment by goatslacker** [comment]
I want to release 0.17.0 but I need to write docs and fix the Render stuff. I would fork and patch for now.
