### ISSUE TITLE
Calling store static methods from within other store statics

### ISSUE THREAD

**Issue by mshick** [goatslacker/alt#36]
You are currently unable to call a store static method from within another static method using `this`. This can be limiting in some cases, and the workarounds are ugly. I realize there might be some design challenges, but I'd love to be able to do, e.g.:

```js
static foo(a1) { return this.getState().foo[a1]; }
static bar() { return this.foo('baz'); }
```

**Comment by goatslacker** [comment]
```js
static foo(a1) { return this.getState().foo[a1]; }
static bar() { return this.getInstance().foo('baz'); }
```

**Comment by mshick** [comment]
Ah, thanks, I'll try that.

**Comment by mshick** [comment]
@goatslacker It doesn't look like `getInstance` is available within static methods. It is undefined for me in 0.13 and 0.14 versions of alt.

**Comment by troutowicz** [comment]
Normal `static` methods do not get access to the object instance. It is only after the alt magic (`createStore`) that they are transformed into instance methods and given access to the new object instance. `getInstance()` is not available in the new object instance.

But this doesn't matter, `static` methods can be accessed inside other `static` methods using `this` just fine.

**Comment by mshick** [comment]
Ah, I see that is working now. Perhaps it's a recent change? That's the ideal approach, for sure. Thanks.

**Comment by goatslacker** [comment]
Ah silly me yes the static is part of the instance itself.
