### ISSUE TITLE
underdash: Isomorphic Rendering

### ISSUE THREAD

**Issue by taion** [goatslacker/alt#360]
ref #337

Points made in various comments:
- Server rendering is important. We should pick something that makes sense and go with that.
- Want to preserve from Marty "The diagnostics from server rendering"
- Render loop for repeatedly re-rendering root component until async data load is resolved: https://github.com/goatslacker/alt/issues/337#issuecomment-114019298 (description of Marty's approach), https://github.com/martyjs/marty-lib/blob/v0.10.6/src/application/renderToString.js (current Marty implementation)
- Do we want instance-based, singleton-based, or both?

**Comment by goatslacker** [comment]
#364

**Comment by taion** [comment]
I think this is irrelevant now.
