### ISSUE TITLE
underdash: Application and Classes

### ISSUE THREAD

**Issue by taion** [goatslacker/alt#363]
ref #337 

Sort of a grab bag.
- Alt doesn't require a specific base class for any of its objects. Relevant behaviors are set up at registration time.
- Marty has base classes for everything. Registration essentially just registers the object to the app.

See: https://github.com/goatslacker/alt/pull/344

Gitter discussion from https://gitter.im/goatslacker/alt?at=558b7039ad7e376201fe886b through https://gitter.im/goatslacker/alt?at=558ba568e6702c3a57647179.

**Comment by taion** [comment]
One migration-related thought - what if we deprecate e.g. `#createActions()` in favor of something like `#register()`? This would make it possible to put the Alt compat wrappers in the deprecated functions to avoid breaking existing users and allowing gradual migration.

**Comment by goatslacker** [comment]
I don't have an opinion here. Registration is essential if you're going the instance approach, if you're doing singletons then the registration happens whenever you import the store or action.

I think deprecating createStore, createActions in favor of a register decorator/function call makes sense.

**Comment by taion** [comment]
I think this is irrelevant now.
