### ISSUE TITLE
TypeError when prerendering with react-rails

### ISSUE THREAD

**Issue by fletcher91** [goatslacker/alt#367]
I've run in to a problem with pre-rendering components in Rails (using [react-rails](https://github.com/reactjs/react-rails) and [browserify-rails](https://github.com/browserify-rails/browserify-rails)) which seem to happen when createActions (or something related to actions) is touched by the prerenderer.
I've spent a lot of time trying to debug the issue, but I couldn't get it right, so I've set up a demo repo which isolates the exception thrown [here](https://github.com/fletcher91/browserify-react-rails) (which may also double as a boilerplate if this can be fixed :) ).

[The traces](https://gist.github.com/fletcher91/3cbe8a8487e9763a3da8) are a bit different, but they seem to relate to the same issue (something with actions and Symbols).

**Comment by fletcher91** [comment]
This issue seems to go away when switching to Babel, will investigate in said repo and report back.

**Comment by fletcher91** [comment]
Can confirm that it's working with Babel.

**Comment by goatslacker** [comment]
What do you mean using babel? What were you using before?
