### ISSUE TITLE
For bindListeners, bindAction and bindActions, which one is prefer to use?

### ISSUE THREAD

**Issue by lenage** [goatslacker/alt#371]
I know it defined at [StoreMixin.js#L108-L177](https://github.com/goatslacker/alt/blob/master/src/alt/store/StoreMixin.js#L108-L177),

and also know how to use it, but could someone tell me, when and which is prefer to use for most of time?

Thanks

**Comment by goatslacker** [comment]
Personal preference. I mostly use bind listeners which lets me specify in a short way exactly what to listen for.

**Comment by taion** [comment]
Don't forget the `@bind` decorator, if you have decorators enabled. It's nice in that it doesn't involve any explicit string keys like the others, so a bit less potential for typos.

**Comment by lenage** [comment]
I just tried `bindListeners` and `bindActions` with below code:

**bindListeners**
```
// action
class TokenAction {
    constructor() {
        this.generateActions(
            'getTokenSuccess',
            'getTokenFailure'
        )
    }
}

// store
class TokenStore {
    constructor() {
        this.bindListeners({
            getTokenSuccess: TokenAction.getTokenSuccess
        })
        this.token = ''
        this.status = null
    }

    getTokenSuccess (res) {
        this.token = res.data.token
        this.status = null
    }

    getTokenFailure (errRes) {
        this.status = 'Error: ' + errRes.data
    }
}
```

**bindActions**

```
// action
class TokenAction {
    constructor() {
        this.generateActions(
            'getTokenSuccess',
            'getTokenFailure'
        )
    }
}

TokenAction = alt.createActions(TokenAction);

// store
class TokenStore {
    constructor() {
        this.bindActions(TokenAction)
        this.token = ''
        this.status = null
    }

    getTokenSuccess (res) {
        this.token = res.data.token
        this.status = null
    }

    getTokenFailure (errRes) {
        this.status = 'Error: ' + errRes.data
    }
}
```

and `bindActions` doesn't work for me, I can't get `res` in `getTokenSuccess`.  any tricks?

**Comment by lenage** [comment]
`TokenAction` equals to `{GET_TOKEN: Symbol(alt/TokenAction.getToken), GET_TOKEN_SUCCESS: Symbol(alt/QTokenAction.getTokenSuccess), GET_TOKEN_FAILURE: Symbol(alt/TokenAction.getTokenFailure)}`

and `bindActions` also requires `action` and  `symbol`  as params, see [StoreMixin.js#L132](https://github.com/goatslacker/alt/blob/master/src/alt/store/StoreMixin.js#L132), 

if because of `GET_TOKEN` is not defined in `TokenStore`, what handler function name should be?

**Comment by goatslacker** [comment]
This works fine:

```js
import Alt from 'alt'

const alt = new Alt()

// action
class TokenAction {
    constructor() {
        this.generateActions(
            'getTokenSuccess',
            'getTokenFailure'
        )
    }
}

TokenAction = alt.createActions(TokenAction);

// store
class TokenStore {
    constructor() {
        this.bindActions(TokenAction)
        this.token = ''
        this.status = null
    }

    getTokenSuccess (res) {
      console.log('im here')
        this.token = res.data.token
        this.status = null
    }

    getTokenFailure (errRes) {
        this.status = 'Error: ' + errRes.data
    }
}

const Store = alt.createStore(TokenStore)

TokenAction.getTokenSuccess({ data: { token: 'it works' } })

```
