### ISSUE TITLE
Documentation in README.md looks wrong

### ISSUE THREAD

**Issue by kswope** [goatslacker/alt#372]
I've been focusing on the README docs and looks like in a few places it hasn't kept up to date, is misleading, or is just wrong.

```
class TodoActions {
  updateTodo(id, text) {
    return { id, text }
  }
}
```

In the alt.js.org docs this would be
```
class TodoActions {
  updateTodo(id, text) {
    this.dispatch({ id, text })
  }
}
```

I'm just starting out with alt.js but the first version looks like its shooting blanks, and I can confirm this with hours of hair pulling.

Another example:

```
class TodoStore {
  constructor() {
    this.bindListeners({
      updateTodo: TodoActions.updateTodo
    });

    this.state = {
      todos: []
    };
  }

  updateTodo(todo) {
    this.setState({ todos: this.state.todos.concat(todo) });
  }
}
```

This above example led me to believe that this.state has has a significant name and furthermore that this.setState has some mergtastic abilities like the React setState does, but looks like it doesn't actually update anything, it just seems to fire off an event and send the return value to the bound listeners.

The docs on alt.js.org are much more clear about this

>
Instance variables defined anywhere in the store will become the state. This resembles how we reason about and build normal JS classes. You can initiaize these in the constructor and then update them directly in the prototype methods.

Personally I don't like the name setState at all, since it doesn't actually set anything, unlike the React version.  Wouldn't purposing emitChange with a return value make more sense? But that's just my opinionated opinion.

I bet I could find a few more examples, but I gave up on the README docs.  The alt.js.org docs are good, maybe the README docs should just be nuked.

**Comment by goatslacker** [comment]
Thanks for the feedback.

The README in the repo tracks `master` branch which is NOT what is currently on npm (version 0.16.10) I recommend visiting the [v0.16.10](https://github.com/goatslacker/alt/tree/v0.16.10) tag and checking out the docs there, or by visiting alt.js.org which should have the latest deployed docs.

In our future world we'll be relying more on `this.state` and `this.setState`, and also return to dispatch in actions. Actually, the future alt might look a [little different](https://github.com/goatslacker/alt/issues/337). I'd love to have your opinions posted there :)

Perhaps a disclaimer that the README in alt repo is for master and not what's currently published would be good. Then again, I normally publish very often...this one has been a bit of an anomaly.

**Comment by kswope** [comment]
> The README in the repo tracks master branch which is NOT what is currently on npm 

Translation:  

> The first documentation the user sees is wrong for whoever does the least surprising things when trying out this flux implementation.

But not just wrong, but wrong in the worst way, no syntax or runtime errors, just silently fails.   Should have a big warning at the top and easier to find link to alt.js.org

**Comment by goatslacker** [comment]
Yeah fair enough, it's not obvious.

So there's no more confusion:

https://github.com/goatslacker/alt/commit/da9869839ad63304d4f226270264184411bc3ca7
