### ISSUE TITLE
waitFor() semantics

### ISSUE THREAD

**Issue by mattmccray** [goatslacker/alt#38]
Currently the `waitFor` method is pretty much the same as the stock Facebook one:

```javascript
this.waitFor([ AStore.dispatchToken, OtherStore.dispatchToken ])
```

I'd like to make the dispatcher entirely an implementation detail. The `waitFor` method can extract the `dispatcherToken`s itself.

To me, this reads much nicer:

```javascript
this.waitFor( AStore, OtherStore)
```

Or, if you feel strongly about passing an array instead of iterating the arguments:

```javascript
this.waitFor([ AStore, OtherStore ])
```

What do you think? I'd be happy to create a PR if it's something you think fits with alt's vision of Flux.

**Comment by goatslacker** [comment]
That sounds good. If we can make it backward compatible I'm all about that PR.
