### ISSUE TITLE
Alt and Webpack Bug

### ISSUE THREAD

**Issue by nlhkh** [goatslacker/alt#382]
Alt cannot be bundled.

    ./~/alt/utils/connectToStores.js 3.37 kB {0} [built] [2 errors]
    ./~/alt/lib/index.js 12.5 kB {0} [built] [5 errors]
    ERROR in Loader /Users/khanguyen/Desktop/flux-alt/node_modules/alt/node_modules/babel/index.js didn't return a function
     @ ./~/alt/utils/connectToStores.js 56:13-29

    ERROR in Loader /Users/khanguyen/Desktop/flux-alt/node_modules/alt/node_modules/babel/index.js didn't return a function
     @ ./~/alt/utils/connectToStores.js 60:17-39

    ERROR in Loader /Users/khanguyen/Desktop/flux-alt/node_modules/alt/node_modules/babel/index.js didn't return a function
     @ ./~/alt/lib/index.js 77:27-60

    ERROR in Loader /Users/khanguyen/Desktop/flux-alt/node_modules/alt/node_modules/babel/index.js didn't return a function
     @ ./~/alt/lib/index.js 89:21-48

    ERROR in Loader /Users/khanguyen/Desktop/flux-alt/node_modules/alt/node_modules/babel/index.js didn't return a function
     @ ./~/alt/lib/index.js 85:13-31

    ERROR in Loader /Users/khanguyen/Desktop/flux-alt/node_modules/alt/node_modules/babel/index.js didn't return a function
     @ ./~/alt/lib/index.js 93:15-35

    ERROR in Loader /Users/khanguyen/Desktop/flux-alt/node_modules/alt/node_modules/babel/index.js didn't return a function
     @ ./~/alt/lib/index.js 75:12-27

**Comment by goatslacker** [comment]
That looks like an issue with babel?

**Comment by goatslacker** [comment]
Can you give me a bit more info into what you're trying to do and what's going on?

**Comment by nlhkh** [comment]
hi @goatslacker I was just trying out Alt so my setup is very minimal. I fixed the issue, although I still don't know why the fix works. In my loaders in webpack config, when loading babel, I include this property `include: path.resolve(__dirname, 'src'),` where `src` is where all my dev code goes to.

The resulting *webpack.config.js* file is as follow:

    var path = require('path');
    var config = {
      entry: [
        'webpack/hot/dev-server',
        'webpack-dev-server/client?http://0.0.0.0:8080',
        path.resolve(__dirname, 'src/components/index.jsx')
      ],
      output: {
        path: path.resolve(__dirname, 'build'),
        filename: 'bundle.js'
      },
      module: {
        loaders: [
          {
            test: /\.jsx?$/,
            loader: 'babel?stage=1',
            include: path.resolve(__dirname, 'src'),
            exclude: /(node_modules|bower_components)/,
          }
        ]
      }
    };
    module.exports = config;

**Comment by thebitguru** [comment]
FYI, I had this issue in one of my project that lead me to this.  The resolution that @nlhkh mentioned did not work for me, but I thought I would mention what did.  In my case I had `babel` npm package installed instead of `babel-loader`.  Removing `babel` and installing `babel-loader` fixed it.  Based on the path in the first post I am guessing the issue is the same here.

**Comment by taion** [comment]
You don't need to remove `babel` if e.g. you need the Babel CLI. When you just specify `babel` in the webpack config, webpack will try `babel-loader` first. But anyway installing the loader is the correct fix.

**Comment by thebitguru** [comment]
That makes sense, @taion.  Thanks for the info.

**Comment by peter-mouland** [comment]
sounds like this can be closed :)

**Comment by georgiana-gligor** [comment]
Big thank you to @nlhkh for pointing me in the right direction for a similar problem not related to alt.
