### ISSUE TITLE
connectToStores combined with addStore

### ISSUE THREAD

**Issue by jonaswindey** [goatslacker/alt#385]
I'm using alt instances (http://alt.js.org/docs/altInstances/) instead of alt.createStore, and I want to use the @connectToStores decorator to reduce some boilerplate.

however:
```
  static getStores() {
    return [this.props.flux
      .getStore('inquiries')];
  }

  static getPropsFromStores() {
    return this.props.flux
      .getStore('inquiries').getState();
  }
``` 
Gives me an undefined for this.props (and this.props.flux)
Any way I can access the alt instances in those static methods?

**Comment by goatslacker** [comment]
Those functions get props and context passed in as args:

getPropsFromStores(props, context)
