### ISSUE TITLE
AltContainer requires deprecated 'react/addons' package

### ISSUE THREAD

**Issue by mmoss** [goatslacker/alt#387]
React is deprecating their addons package: https://github.com/facebook/react/blob/master/packages/react/addons.js

The **require** in the warning string is currently being parsed and causing an issue when the latest react (*0.14.0-beta1*) is used in conjunction with alt.

**Comment by goatslacker** [comment]
When React 0.14 ships we'll figure it out :) In the mean time Alt is supposed to work with 0.12+

**Comment by am80l** [comment]
Upgraded today and came across this issue. Just a warning so no biggy, but :+1:  on this issue :)

**Comment by goatslacker** [comment]
Stopped requiring it here: 0570617ef5a1c8cca444a183c6d0bce91927dabd

there are still other warnings to take care of.
