### ISSUE TITLE
exportPublicMethods does not export methods under mocha...

### ISSUE THREAD

**Issue by jcalfee** [goatslacker/alt#389]
Can you think of any reason this would fail?  We run this code fine in the browser and it works.  It is just when I go to run any mocha test that imports an Alt store, the exportPublicMethods is called with good data but the static store methods do not exist.

A console.log of the store shows {} or a Object.keys(Store) shows [] ...  

Hope you don't mind all the links.  Not sure how to show you.  Let me know if I can clarify or if if this is not an Alt issue.  thanks...

This is the alt store that is exported as follows:
`module.exports = alt.createStore(WalletStore, "WalletStore")`
Then calls _export on its parent:
https://github.com/cryptonomex/graphene-ui/blob/9cceb5247acd0b46d5f99b8dd039104af10cc912/dl/src/stores/WalletStore.js#L24

In the _export method, a console.log shows that the methods are being passed to `this.exportPublicMethods`:
https://github.com/cryptonomex/graphene-ui/blob/9cceb5247acd0b46d5f99b8dd039104af10cc912/dl/src/stores/BaseStore.js#L10

Finally, it comes up empty (again, only from mocha though):
https://github.com/cryptonomex/graphene-ui/blob/9cceb5247acd0b46d5f99b8dd039104af10cc912/dl/src/actions/WalletActions.js#L8

Mocha usage:
https://github.com/cryptonomex/graphene-ui/blob/9cceb5247acd0b46d5f99b8dd039104af10cc912/dl/package.json#L18

Mocha test:
https://github.com/cryptonomex/graphene-ui/blob/9cceb5247acd0b46d5f99b8dd039104af10cc912/dl/test/wallet_action_test.js#L69

... that method call into this class and ends up erroring here:
`TypeError: Object [object Object] has no method 'isLocked'`
https://github.com/cryptonomex/graphene-ui/blob/9cceb5247acd0b46d5f99b8dd039104af10cc912/dl/src/actions/WalletActions.js#L24

**Comment by jcalfee** [comment]
I see the same error when using a static method (static isLocked) instead of exportPublicMethods...

**Comment by jcalfee** [comment]
I see the error .. Not Alt..

Somehow the "import" is returning an object before the store is actually exported (via module.exports)....

**Comment by goatslacker** [comment]
Circular dependency?

**Comment by jcalfee** [comment]
Yes! .. Thank you .. ha

**Comment by jcalfee** [comment]
If only there were such a thing as error trapping and reporting .. Imagine the time we would save.
