### ISSUE TITLE
registerAsync not a function in AltTestingUtils.makeStoreTestable

### ISSUE THREAD

**Issue by YoYuUm** [goatslacker/alt#397]
Hello! 

I'm trying to write a store test using AltTestingUtils.makeStoreTestable from 'alt/utils/AltTestingUtils'. My store class is using registerAsync on the constructor, and I get the error ```TypeError: this.registerAsync is not a function``` when I try to create a testable store. 

Is this a bug, or I'm I supposed to get around this somehow? 

Thanks!

**Comment by goatslacker** [comment]
Yup it's a bug, we can add registerAsync and exportAsync to AltTestingUtils. Do you want to or shall I?

**Comment by YoYuUm** [comment]
I can try.

**Comment by goatslacker** [comment]
Thanks!
