### ISSUE TITLE
Store Mixins

### ISSUE THREAD

**Issue by willcosgrove** [goatslacker/alt#4]
What do you think about adding store mixins?  Mixins would be able to add bindings to actions, and define the functions they get bound to.  There would also need to be a way to pass information into the mixins from the store.  Although, this could also be achieved through a sort of Mixin Generator.

I've got a certain bit of functionality that I'm having to clone to pretty much every Store I have.  It pertains to listing for an action that fires when the app gets new data from a websocket.  It needs to grab the data out of the object at the key that matches the store's name TaskStore would grab "tasks", etc.  So the mixin would need to be able to get that unique "data_key" that it needs to look for in it's action handler.

Does this sound like a good idea?  Or would it be better to just leave it to the user to implement mixins if they need it?

**Comment by goatslacker** [comment]
Does es6/coffee-script `extends` do what you need or were you thinking of something else?

```js
class TaskStore extends MyStoreMixin
  onSearch: ->
    @doSomethingProvidedInMixin()
```

you can also use something like es6's `Object.assign`, or underscore's `_.extend`

```js
class TaskStore
  onSearch: ->
    @mixingFunction()

Object.assign(TaskStore.prototype, {
  mixingFunction: ->
    true
})
```

**Comment by goatslacker** [comment]
If you're using classes to build components in [React 0.13](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html) you lose mixins. I'm deferring to ES7 to add proper mixin support. In the mean time you can use extend, Object.assign, or function calls.
