### ISSUE TITLE
how to call action from same action class?

### ISSUE THREAD

**Issue by jongbeau** [goatslacker/alt#40]
I'm able to workaround the scope issue by creating a var outside the class, but it makes me feel dirty. Is there a cleaner way? I know the typical pattern is to call out to another module, which can then create the action as normal. Is there another way?

```
var self
class TestActions() {
  action1() {
    //do stuff, maybe talk to an API
    self.action2()
  }
}
self = alt.createActions(TestActions)
module.exports = self
```

**Comment by troutowicz** [comment]
```javascript
class TestActions() {
  action1() {
    //do stuff, maybe talk to an API
    this.actions.action2()
  }

  action2() {
    ...
  }
}
```

**Comment by goatslacker** [comment]
Beat me to it. @troutowicz++

**Comment by jongbeau** [comment]
Thanks guys. I was debugging through source maps and the "this" variable was out of scope due to the source map :)
