### ISSUE TITLE
Component methods undefined after using connectToStores

### ISSUE THREAD

**Issue by xpepermint** [goatslacker/alt#402]
I wrap my component with `connectToStores` and then I would like to further extend it.

```js
// simplified component example
import connectToStores from 'alt/utils/connectToStores';
import connectToSockets from 'my-extension-which-like-connectToStores';
import React from 'react';
import LocationActions from '../actions/LocationActions';
import LocationStore from '../stores/LocationStore';
import LocationSocket from '../sockets/LocationSocket';

class Locations extends React.Component {
  static getStores() {
    return [LocationStore];
  }

  static getSockets() {
    return [LocationSocket];
  }

  static getPropsFromStores() {
    return LocationStore.getState();
  }

  render() {
    return (
      <ul>
        {this.props.locations.map((location) => {
          return (
            <li key={location.id}>
              <b>{location.name}</b>
              <span>, {location.updatedAt}</span>
            </li>
          );
        })}
      </ul>
    );
  }
}

export default connectToSockets(connectToStores(Locations));
```
Method `connectToSockets` will throw error saying `getSockets method is not found`. That's because `connectToStores` does not copy custom static methods. Why not having a class that we extend from (the usual OOP cycle)? Any suggestions?

**Comment by goatslacker** [comment]
You'd want to use something like statics: https://github.com/goatslacker/alt/blob/master/src/utils/statics.js

**Comment by xpepermint** [comment]
Hum, thanks for the tip. It would be nice if the `connectToStores` would already do that since `class extends` copies static methods by default. I would say that at the moment `connectToStores` returns unexpected object - I would expect that only additional methods are inserted not that static methods are `removed`. What do you think? Can we add this?

**Comment by taion** [comment]
@xpepermint ES6 classes as polyfilled by Babel do _not_ always have static methods inherited: https://babeljs.io/docs/advanced/caveats/#classes-10-and-below-

**Comment by xpepermint** [comment]
Sure? Hum... I didn't know that (works for me). OK so using `statics` is the best solution for now. Thx.

**Comment by taion** [comment]
If you depend on static methods getting inherited on ES6 classes, your code will not work for any of your users on IE9 or IE10. It's pretty painful unfortunately.

**Comment by xpepermint** [comment]
Thanks man! Closing ...

**Comment by goatslacker** [comment]
I could copy over all the static methods in your component onto the container created by connectToStores but that's a bit magical. This statics util lets you explicitly set things at the top level.

**Comment by goatslacker** [comment]
Make sure statics is your last wrapped container though!

**Comment by xpepermint** [comment]
OK, will do. Thx!
