### ISSUE TITLE
DataSource.loading does not pass arguments to action

### ISSUE THREAD

**Issue by mull** [goatslacker/alt#404]
Given a data source like this:

```
  fetchUniversity: {
    remote(state, id) {
      return qlearningApi.getUniversity(id);
    },

    local(state, id) {
      return findUniversityWithId(state.get('universities'), id);
    },

    loading: UniversityActions.loadingUniversity,
    success: UniversityActions.receivedUniversity,
    error: UniversityActions.fetchingUniversityFailed,
  }
```

I can confirm that my actions *do* get called, and my store listeners *do* get called. They however **don't** get the `id` parameter passed to `fetchUniversity`. These are the arguments passed:

![screen shot 2015-07-16 at 17 32 54](https://cloud.githubusercontent.com/assets/646665/8727575/be410c1a-2be0-11e5-8bf1-236f70958300.png)

Tested on `0.17.1`. I work around this for now by calling the action in `remote`.

**Comment by mull** [comment]
I realise now that this is probably a feature request rather than a bug report as this is probably specced behaviour.

**Comment by taion** [comment]
Use `interceptResponse` to do this: http://alt.js.org/docs/async/#interceptresponseresponse-action-args

**Comment by mull** [comment]
@taion that works too, although it feels even more unintuitive than just calling the action from `remote()`. Is there a reason for passing null?

**Comment by taion** [comment]
I can't speak for original intentions, but note that the data source itself has no visibility into e.g. how your arguments are named, so the best it could do would be to pass an array of args, which would not be an ideal API.

Like really you want your payload to be something like e.g. `{id, result}` or perhaps `{id, params, result}`, but we can't really generate that.

**Comment by mull** [comment]
That would be an okay API to me, but it's fine. The easiest way to do this is just to call the loading action from `remote`. To me at least. :)
