### ISSUE TITLE
setting store state as Immutable.js Map is returned without __proto__: src_Map__Map when store.getsState()

### ISSUE THREAD

**Issue by soundobj** [goatslacker/alt#405]
I am setting a store in this way:

 var SubmissionsListStore = alt.createStore({
 state : Immutable.Map({
            submissions : []
        }),
......

When in my component I do a data = SubmissionsListStore.getState();

I have noticed that the data.proto has changed to __proto__: Object
It should be __proto__: src_Map__Map
It seems that Alt is doing cloning the state in a funny way and I cannot longer perform a  .toJS() on the immutable map.

Any help would be greatly appreciated

**Comment by srph** [comment]
Have you tried using `ImmutableUtil`?

**Comment by soundobj** [comment]
I tried but our setup is es5 and we were getting this error:

immutableUtil.js:3 Uncaught ReferenceError: exports is not defined

regards,

**Comment by jdlehman** [comment]
You can do this without ImmutableUtil, the util just tries to reduce the boilerplate you have to write yourself by setting some items in the store's `config` property.

```js
var SubmissionsListStore = alt.createStore({
  state : Immutable.Map({
  submissions : []
  }),
  config = {
    setState: function(currentState, nextState) {
      this.state = nextState
      return this.state
    },
    getState: function(currentState) {
      return currentState
    },
    onSerialize: function(state) {
      return state.toJS()
    },
    onDeserialize: function(data) {
      return Immutable.fromJS(data)
    }
  }
  ...
});
```

Here are the [config docs](https://github.com/goatslacker/alt/blob/master/docs/createStore.md#storemodelconfig) if you want to customize this more for your needs

**Comment by goatslacker** [comment]
@soundobj you need to webpack/browserify ImmutableUtil if you want to use it in the browser, which it sounds like that's what you're doing.

**Comment by soundobj** [comment]
@jdlehman  the config setup works although I donk quite understand how it works when I am calling setState with a single parameter thus:

this.setState(this.state.set('submissions',payload.submissions));

the signature is two params: setState: function(currentState, nextState) {

am I doing something wrong here?

many thanks for the awesome support!

**Comment by jdlehman** [comment]
The `currentState` is passed in for you by alt. So you are supplying `nextState`

The [src](https://github.com/goatslacker/alt/blob/master/src/alt/store/index.js#L17-L21) for the curious
