### ISSUE TITLE
Setting up a store/action through a API

### ISSUE THREAD

**Issue by kkotwal94** [goatslacker/alt#410]
I'm stuck trying to figure out how to write a flux store and action that works in just fetching data from my express API
```
    import $ from 'jquery';
    
    const utils = {
    
    myProfile: () => {
        return $.ajax({
          url: '/myProfile',
          type: 'GET'
        });
      }
    };
```
This is how I believe I should write my GET request for just grabbing a user's profile (which should return a json with user info).

then for my store :
```
    import UserActions from 'actions/UserActions';
    import alt from 'altInstance';
    class UserStore {

    constructor() {
       this.userProfile = [];
       this.on('init', this.bootstrap);
       this.on('bootstrap', this.bootstrap);
       this.bindListeners({
       fetchUserProfile: UserActions.FETCHUSERPROFILE,
         });
      }
    
    fetchUserProfile(profile) {
        this.userProfile = profile;
      }
    }
    export default alt.createStore(UserStore, 'UserStore');
```
However the action is where i'm the most clueless
```
    import alt from 'altInstance';
    import UserWebAPIUtils from 'utils/UserWebAPIUtils';
    fetchProfile(){
        this.dispatch();
        UserWebAPIUtils.getProfile()
          //what do we do with it to let our store know we have the data?
          });
             }
          }
      }
```
All im trying to do, is grab data from the server, tell my store we've recieved the data and fill the userprofile array with the data from our api, and the messenger for telling our store is through a dispatcher which belongs to 'actions' correct? I've looked at a lot of tutorials but I still dont feel very confident on how I am thinking about this. What if I wanted to update data through a POST request what would that be like?

**Comment by srph** [comment]
Let `fetchProfile` dispatch an action (one to handle the success request, one to handle failed request)

```js
fetchProfile() {
  this.dispatch();

  SomeAPIUtils.getProfile()
    .then(::this.actions.fetchProfileSuccess)
    .then(::this.actions.fetchProfileError);
}
```

**Comment by taion** [comment]
Oh god it's a wild Puck.

Your other option for data loading specifically is something like http://alt.js.org/docs/async/. This is a little in flux (hah) right now but will enable you to do some cool isomorphic things down the road, and shouldn't change in ways that make it difficult to catch up to.

**Comment by srph** [comment]
Yea, and that. I heard that the async api is getting an improvement soon (although I think it's pretty okay as it is atm).

**Comment by taion** [comment]
A little bit - things to do with how to connect components to data sources, see #393 and #400. But the `local`/`remote`/`success`/`error` bits aren't going to meaningfully change, and I think it's a nice way to set up async data loads.

**Comment by kkotwal94** [comment]
If I were to grap the data with a promise I would just do something along the lines of : 

```
let myInit = { method: 'GET',
               mode: 'cors',
               cache: 'default' };
  fetch('/myProfile', myInit).then(function(response) {
    return response;
  });
```
I would like to get accustomed to promises as well that's why I ask.
