### ISSUE TITLE
Configuring actions through parameters.

### ISSUE THREAD

**Issue by kevinwolfcr** [goatslacker/alt#412]
Hello guys, I am wondering if I am doing this correctly, or there is another way to achieve it:

I am creating a chat component on top of React and Alt for internal use on some projects on the company I work.

What I want to achieve, is to make my component modular so I can set the socket url like this:

``` html
<Chat socket="https://apogeelive-chat-server.herokuapp.com/" />
```

I did achieved the above by adding a setter function on the `ChatActions.js` file, but I am not sure if this can be the best practice:

``` js
import alt from '../alt';
import io from 'socket.io-client';

let socket;

@alt.createActions
class ChatActions {

  constructor () {
    this.generateActions('uidReceived', 'messageReceived');
  }

  setSocketUrl (url) {
    socket = io.connect(url);

    socket.on('chat:receivedMessage', (message) => {
      ChatActions.messageReceived(message);
    });

    socket.on('chat:receiveUid', (id) => {
      ChatActions.uidReceived(id);
    });
  }

  addMessage (message) {
    socket.emit('chat:addMessage', message);
  }

}

export default ChatActions;
```

And configuring it within my component:

``` javascript
// Third parties.
import React from 'react';
import connectToStores from 'alt/utils/connectToStores';

// Actions & Stores.
import ChatActions from '../actions/ChatActions';
import ChatStore from '../stores/ChatStore';

// UI Components.
import ChatItem from './ChatItem';
import ChatForm from './ChatForm';


@connectToStores
class ChatView extends React.Component {

  static getStores () {
    return [ ChatStore ];
  }

  static getPropsFromStores () {
    return ChatStore.getState();
  }

  constructor (props) {
    super(props);
    this.addMessage = this.addMessage.bind(this);
    ChatActions.setSocketUrl(this.props.socket);
  }

  addMessage (text) {
    ChatActions.addMessage({ uid : this.props.uid, text : text });
  }

  render () {
    let messages = this.props.chatMessages.map((message) => {
      return <ChatItem key={message.id} message={message} uid={this.props.uid} />;
    });

    return <div>
      <ul>{messages}</ul>
      <hr />
      <ChatForm onAddMessage={this.addMessage} />
    </div>;
  }

}

export default ChatView;
```

My question is:
- **Is this the correct way to achieve what I want?**
- **There is another way to achieve this, that I am missing?**

Regards.

**Comment by taion** [comment]
This doesn't seem quite correct to me. What happens if you ever have two `ChatView` components at the same time?

**Comment by jdlehman** [comment]
Yeah, it feels like it is stepping outside of the flux pattern. I think this data should be backed by stores. Then it would allow you to have multiple `ChatView` components and match something like an `id` with the socket url.

Then I would probably do the socket initialization in the `componentDidMount` lifecycle state in your components.

**Comment by kevin-wolf** [comment]
Any example of how you guys will do that?

**Comment by taion** [comment]
@kevin-wolf Depends on whether you want to support multiple `ChatView` components or not. Do you?

**Comment by kevin-wolf** [comment]
Yes, I do.

**Comment by taion** [comment]
Sorry, I mean - multiple `ChatView` components with different sockets.

**Comment by kevin-wolf** [comment]
Yes, that's the idea.

**Comment by taion** [comment]
Essentially, do what @jdlehman said above - keep track of everything separately in your stores/actions by the socket you're using for the `ChatView`, and always ensure you reference things by the socket. Also should probably make sure your tear down subscriptions in `componentWillUnmount`.

You might need to implement `componentWillReceiveProps` if the `socket` prop on the `ChatView` might change.

**Comment by kevin-wolf** [comment]
I am not understanding. Can you give me a code sample please?
