### ISSUE TITLE
Question: Multiple actions being called from one action

### ISSUE THREAD

**Issue by joshhornby** [goatslacker/alt#414]
I am currently doing this inside one of my actions, when the date is set I then update the other stores which need the new updated data.

```
  setDates(start, end) {
    this.dispatch({ start: start, end: end });
    TrafficActions.getTraffic();
    CardActions.getTraffic();
  }
```

Is there a nice alt way of doing this?

**Comment by taion** [comment]
http://alt.js.org/docs/actions/#actiondefer

Generally you should try to structure things not to require this, though.

**Comment by joshhornby** [comment]
@taion what would be the better way to structure the all to call multiple actions?

The state returned from setDates is key to rendering the components which I am calling above.

**Comment by taion** [comment]
Well, if you need to use it, you need to use it. The other alternative is to use `waitFor`.

**Comment by goatslacker** [comment]
I would just have one single getTraffic action and then have all the stores listen to that action and act accordingly.

Calling actions inside of an action is OK though. This is fine :+1:
