### ISSUE TITLE
BindAction - invalid reference

### ISSUE THREAD

**Issue by srph** [goatslacker/alt#418]
In `bindAction` in *Store*s, it's a bit inconvenient to track which action reference being passed is invalid.  Anybody having the same issue? Is it possible we put the name of the action?

I'm still on a low-end pc somewhere, I'll try to send a PR when I get the time.

**Comment by goatslacker** [comment]
you mean in the error message?

**Comment by srph** [comment]
Yes.

**Comment by goatslacker** [comment]
This one: https://github.com/goatslacker/alt/blob/master/src/alt/store/StoreMixin.js#L110 ??

**Comment by srph** [comment]
Yes, haha :laughing:

**Comment by goatslacker** [comment]
But chances are you're not passing in an action to symbol.id will be undefined. I can however tell you what store you're trying to bind to but that information is sort of useless if you have a stack trace.

**Comment by srph** [comment]
I see. Thanks.

```
bindAction	@	script.js:23951
(anonymous function)	@	script.js:24009
(anonymous function)	@	script.js:22920
(anonymous function)	@	script.js:22919
eachObject	@	script.js:22918
bindListeners	@	script.js:23997
ContactStore	@	script.js:39236
Store	@	script.js:23511
createStoreFromClass	@	script.js:23532
createStore	@	script.js:23126
(anonymous function)	@	script.js:22863
(anonymous function)	@	script.js:39464
(anonymous function)	@	script.js:39466
__webpack_require__	@	script.js:20
(anonymous function)	@	script.js:39019
__webpack_require__	@	script.js:20
(anonymous function)	@	script.js:19041
__webpack_require__	@	script.js:20
(anonymous function)	@	script.js:57
__webpack_require__	@	script.js:20
(anonymous function)	@	script.js:40
(anonymous function)ffmpeg -i rae.mov -pix_fmt rgb24 -r 10 -f gif - | gifsicle --optimize=3 --delay=3 > rae.gif
```

**Comment by goatslacker** [comment]
Ah yes when your stack trace is webpack vomit then it's not very useful :(
