### ISSUE TITLE
connect to multiple stores

### ISSUE THREAD

**Issue by nlhkh** [goatslacker/alt#420]
If I want to connect a React component to a store, I can do this

    @connectToStores
    class TodoView extends Component {
      static getStores() {
        return [TodoStore];
      }

      static getPropsFromStores() {
        return TodoStore.getState();
      }

      render() {
        return (
          <ul>
           {this.props.todos.map((todo) => {
              return (
                <li key={todo.id}>{todo.text}</li>
             );
            })}
         </ul>
        );
      }
    }

But if I want to have more than a store, for example for authentication, how I can do that with @connectToStore?
I suppose

    static getStores() {
        return [TodoStore];
    }

but I am not sure about the `getPropsFromStores` method.

**Comment by jdlehman** [comment]
`getPropsFromStores` returns an object that is passed into your component as props.

```js
static getPropsFromStores() {
  var todoState = TodoStore.getState();
  var anotherState = AnotherStore.getState();
  return {
    todos: todoState.todos,
    selectedTodo: todoState.selectedTodo,
    anotherProp: anotherState.someProp
  }
}

static getStores() {
  [TodoStore, AnotherStore];
}
```

you can also do this more concisely with the spread operator
```js
static getPropsFromStores() {
  return {
    ...TodoStore.getState(),
    ...AnotherStore.getState()
  }
}
```

**Comment by nlhkh** [comment]
thanks @jdlehman !

**Comment by Nico-Echezarreta** [comment]
I think this one should be added to the docs as an example since it's a pretty common task.

**Comment by askogrand** [comment]
+1 To adding this to the docs. Spent a while searching for it and its a pretty typical use case.

**Comment by robertkraigcdg** [comment]
+++1, wish this was in the docs in the 1st place. wish I knew about this earlier. I'm always doing "storeName.lsitens(this.method.bind(this))"

**Comment by robertkraig** [comment]
+1

**Comment by jdlehman** [comment]
The documentation has been updated: http://alt.js.org/guide/container-components/

If you ever see outdated documentation, or documentation that could use more explanation in the future, please feel free to submit a PR with the changes. All of the docs that are on the website live in the [docs folder](https://github.com/goatslacker/alt/tree/master/docs)
