### ISSUE TITLE
DataSource & promises

### ISSUE THREAD

**Issue by mull** [goatslacker/alt#422]
Hey folks

I'm having an issue where I need to fetch five resources, each depending on the first one. In other words once I have the first one I get an ID to fetch the second one and so it goes.

If my fetch methods returned promises I would have code like so:

```
const firstId = this.props.id;
FirstStore
  .fetch(firstId)
  .then(firstResource => SecondStore.fetch(firstResource.parent_id))
  .then(secondResource => ThirdStore.fetch(secondResource.parent_id))
  .then(...)
```

Possibly setting state in each resolve block. How would you go about this with DataSources? Even if I return a Promise in my `remote` method I don't get a resolve value in my then method.

I don't understand the source code too well but I the return statement in the following block is what does it. What are datasource methods supposed to return exactly?

```
        var makeActionHandler = function makeActionHandler(action, isError) {
          return function (x) {
            var fire = function fire() {
              loadCounter -= 1;
              action(intercept(x, action, args));
              if (isError) throw x;
              else return args;
            };
            return _this.alt.trapAsync ? function () {
              return fire();
            } : fire();
          };
        };
```

Thanks for your help!

**Comment by taion** [comment]
I'm not quite sure what you're asking for. It's part of the design of data sources that the actions are only resolved at the end of the `remote` handler, such that we can have more control over when and how changes are dispatched into stores, which makes it nicer to handle isomorphic use cases.

**Comment by mull** [comment]
@taion the actions should of course only be called once the promise resolves. My problem is that when calling a datasource method (say `fetchResource`) whose remote method returns a Promise, I can not "attach" (sorry I don't know the right word) to that promise to get the results. All promises returned by a datasource method are resolved with no value.

How would you go about solving the problem I described up at the top where I need to load resources one by one in the correct order, each one depending on the previous?

**Comment by taion** [comment]
The value of the future is passed as the first argument to the `success` or `error` action, unless you've set up `interceptResponse` to do something different.

**Comment by mull** [comment]
@taion yes, the action. But not the promise chain. If your remote function returns a promise, then calling your datasource function also returns a promise. Right? But that promise is unusable as its resolve value is lost.

**Comment by taion** [comment]
That promise is just to indicate when the remote fetch is complete - you should handle the value in the completion actions.

**Comment by mull** [comment]
@taion makes very much sense.

So how would you go about my initial problem where I need to wait for each fetch to finish before I can fetch the next one? Thanks for your continued help!

**Comment by taion** [comment]
As it stands, if you can be sure that your fetches will return promises, can you just read the value from the store?

**Comment by mull** [comment]
How I didn't think of that is... embarrassing. Instead of expecting a resolve value for the promise just read from the store once the promise resolves! :grin: It's a little weird but it sure works. This is how it turned out. A bit disappointed with the mutable variables, but I couldn't think of a way that is prettier. What do you think?

```
let user, contentUnit, chapter, course, university;

Promise
  .all([ UserStore.fetch(userId), ContentUnitStore.fetch(unitId, unitType) ])
  .then((values) => {
    user = UserStore.find(userId);
    contentUnit = ContentUnitStore.find(unitId, unitType);

    return ChapterStore.fetch(contentUnit.chapter_id);
  })
  .then(() => {
    chapter = ChapterStore.find(contentUnit.chapter_id);
    return CourseStore.fetch(chapter.course_id);
  })
  .then(() => {
    course = CourseStore.find(chapter.course_id);
    return UniversityStore.fetch(course.university_id);
  })
  .then(() => {
    university = UniversityStore.find(course.university_id);
    console.log("All done!", user, contentUnit, chapter, course, university);
  })
  .catch((e) => console.error(e))
```

**Comment by taion** [comment]
You could nest the promises and use `const` bindings inside the continuations.

**Comment by mull** [comment]
I suppose so, although that doesn't really make it prettier I think. Thanks for the help!

**Comment by taion** [comment]
No worries. You can also use `async`/`await`, which gives nicer syntax for this. Anything else on this issue, or can we close?

**Comment by mull** [comment]
I haven't yet looked at async/await, so I suppose I should. Thanks again for the help! No further questions. :)

**Comment by kellyrmilligan** [comment]
I know this is closed, but I was just looking at this as well. I see a test case for a dispatcher being called for async trap = true. not sure what the expected functionality of it is. when would you want to set 

````
alt.trapAsync = true
````

? I also think its' reasonable to expect a return value that's not a function but is the same value your remote function is resolving. 

I have a fix, but not sure how to fix the test, or what the expected functionality is. 

@taion
