### ISSUE TITLE
Is it possible to delete stores?

### ISSUE THREAD

**Issue by bebraw** [goatslacker/alt#424]
Given it's possible to create store instances is it possible to delete them as well?

I recall asking this through gitter. We did find something but even then some references were left hanging around. I don't remember the exact solution. Regardless I would expect to have some API method for this.

I'm not going to need this anymore but I thought to bring it up given it seems kind of fundamental operation. It would allow you to set up weird setups like a dynamic store/actions pair created per component. I understand now that it's a Flux anti-pattern but still. :+1:

**Comment by goatslacker** [comment]
it's a flux anti-pattern so there's no API for it in order to discourage dynamically creating and deleting stores but if you really want to it's as easy as `delete alt.stores.TheStore`.

**Comment by bebraw** [comment]
Yeah, that's what I thought. :+1:

Feel free to close the issue.
