### ISSUE TITLE
Arguments passed to action handler

### ISSUE THREAD

**Issue by Satyam** [goatslacker/alt#425]
[This line](https://github.com/goatslacker/alt/blob/master/src/alt/store/StoreMixin.js#L116) is in contradiction with [this one](https://github.com/goatslacker/alt/blob/master/src/alt/store/AltStore.js#L56) since you pass two arguments but prevent the consumer from declaring more than one argument.  The argument is still available as `arguments[1]` but it doesn't look good.  

A warning if in some sort of development mode might be nice but throwing an error is a little extreme.

**Comment by goatslacker** [comment]
Yes it is...hmmm

So the reason an error is thrown is so people don't accidentally do this:

```js
FooActions = {
  fire() {
    this.dispatch(1, 2, 3);
  }
}

FooStore = {
  onFire(one, two, three) {
  }
}
```

And the only reason I'm passing in the action as the 2nd arg is for otherwise to have it. I cheated and created a shorthand that also enables actions to receive this 2nd arg, but it's useless for actions since you already know what the action is.

However since one function can listen to multiple actions maybe it makes sense to leave this as-is and remove the error being thrown?

**Comment by Satyam** [comment]
I understand the purpose of the warning and as such, it would be better served by a `console.warn`, not a fatal error.  Just like when you forget to provide a `key` argument to a list-item, React warns you about that, but it doesn't prevent you from shooting your foot.

I haven't checked to see if there are other such fatal errors that should be warnings, but it wouldn't be a bad idea to revise them all.

Also, there should be a way to drop those messages when in production.  After all, if you do share action handlers or whatever reason for any such warning, if you mean to do it, once in production, too many pointless messages simply clutter the log and might make significant messages scroll away.  (I am thinking server-side rendering here).   Possibly something that can also allow a minifier to detect it as dead code and not even include it in the bundle.

**Comment by Satyam** [comment]
React has a lot of conditionals like this:
```js
if ("production" !== process.env.NODE_ENV) {
```
Uglify evaluates as many expressions with constants, such as this
```js
if ("production" !== "production") {
// which turns into
if (false) {
```
Then it will detect those unreachable pieces of code and discard them.

For Webpack, you can add a plugin to have this value pre-defined: 
```js
	plugins: [
		new webpack.DefinePlugin({
			'process.env': {
				// This has effect on the react lib size
				NODE_ENV: JSON.stringify('production')
			}
		}),
		new webpack.optimize.DedupePlugin(),
		new webpack.optimize.UglifyJsPlugin({
			compress: {
				warnings: false
			}
		})
	],
```

Which means all those extra diagnostics won't even take a byte in the minified version for the client since they will be stripped out.

**Comment by goatslacker** [comment]
With return to dispatch this is really unnecessary, so it's removed: fbca3463885aec3f1e6e919283c1a56ff4409339
