### ISSUE TITLE
Action not always dispatched unless you call it inside setTimeout

### ISSUE THREAD

**Issue by xpepermint** [goatslacker/alt#428]
I noticed that the `this.dispatch` is not always triggered and you have to call it inside `setTimeout`. Why is that? 

I use `react-router` for navigation. I call `StatsActions.getStats` inside react's `componentDidMount` method. Everything works well if I switch between routes by clicking on links. The `getStats` action is not dispatched when I use `router.transitionTo` and I have to wrap it inside `setTimeout`.

```js
  componentDidMount() {
    StatsStore.listen(this.storeListener);
    StatsSocket.connect();
    setTimeout(() => {
      StatsActions.getStats();
    }, 0);
  }
```

The full source code of my project is available at https://github.com/xpepermint/isomorphic-react-flux-boilerplate.

**Comment by alexcurtis** [comment]
@xpepermint I've just stumbled into this issue. If you are using the connectToStores decorator/mixin then moving the code into componentDidConnect fixed the dispatcher issue for me.

**Comment by xpepermint** [comment]
@alexcurtis Thanks for the hint.

**Comment by xpepermint** [comment]
I noticed this:
```js
componentDidMount() {
   console.log(alt.dispatcher.isDispatching()); // TRUE when redirected to a component otherwise FALSE
}
```

Btw... I'm experiencing this only when rendering the component below which causes the redirect to the component above.

```js
import React from 'react';
import SessionActions from '../actions/SessionActions';

class Logout extends React.Component {
  componentDidMount() {
    SessionActions.logout();
    this.context.router.transitionTo('/');
  }

  render() {
    return null;
  }
}

Logout.contextTypes = {
  router: React.PropTypes.object.isRequired
};

export default Logout;
```

Suggestions?

**Comment by xpepermint** [comment]
Hum... maybe this is react/react-router related problem. See this https://github.com/rackt/react-router/issues/950.

**Comment by awinder** [comment]
I ran into this as well, and rather than the blind timeout I did this (just noting in case anyone finds it useful.  It's still a little hacky.)

```
        var intId = setInterval(function() {
          if (alt.dispatcher.isDispatching()) {
            return;
          }

          clearInterval(intId);
          this.context.router.transitionTo('...');
        }, 50);
```

**Comment by derek-duncan** [comment]
I encountered this same issue today. In this case, I'm calling an action. As I was debugging, both the action and the store receive the call, but the listening component doesn't detect the action. My source code is here –> https://github.com/derek-duncan/challenge/blob/master/src/pages/Home.jsx#L14

**Comment by goatslacker** [comment]
This might be of some help for you all: https://github.com/goatslacker/alt/pull/278

The current solutions are to patch transitionTo so it doesn't run in the same event loop. Use `defer`. Do setTimeout in componentDidMount. Or use the batching function.
