### ISSUE TITLE
@connectToStores doesn't work in pair to react-router statics

### ISSUE THREAD

**Issue by chiefGui** [goatslacker/alt#432]
The following code **doesn't** work:

```js
@connectToStores
export default class extends Component {
  static getStores() {
    return [PostStore]
  }

  static getPropsFromStores() {
    return PostStore.getState()
  }

  static willTransitionTo() {
    console.log('hi');
  }

  static willTransitionFrom() {
    console.log('bye');
  }

  render() {
    return <div>hello</div>
  }
}
```

As you can see, I have 4 static methods. Two of them are because of the alt's Stores, and two of them are the transitioning methods of [react-router](https://github.com/rackt/react-router).

The point is, they doesn't work in pair. When having the static methods of `@connectToStores`, the react-router's method doesn't work.

As an experiment, I just removed the notation `@connectToStores` from the top of the class and boom, it worked—but of course, the Store don't.

Suggestions?

**Comment by taion** [comment]
`@connectToStores` creates a wrapper component.

You'll have to define the `static` transition hooks on the decorated class.

**Comment by chiefGui** [comment]
@taion could you give me an example of how achieve this?

**Comment by taion** [comment]
```js
@connectToStores
export default class MyComponent extends React.Component { ... }

MyComponent.willTransitionTo = ...;
```

**Comment by chiefGui** [comment]
Thank you!

**Comment by aakashlpin** [comment]
@chiefGui @taion: I ran into this issue today. However, it's not working. Here's the code I have 

```
import React, { Component } from 'react';
import CardGroup from '../components/card/CardGroup';
import AccountSettings from '../components/settings/AccountSettings';
import PayoutsSettings from '../components/settings/PayoutsSettings';
import PricingSettings from '../components/settings/PricingSettings';
import SavedCardsSettings from '../components/settings/SavedCardsSettings';
import ProfileSettings from '../components/settings/ProfileSettings';
import SettingsActions from '../actions/SettingsActions';
import SettingsStore from '../stores/SettingsStore';
import connectToStores from 'alt/utils/connectToStores';

@connectToStores
export default class Settings extends Component {
  static getStores () {
    return [SettingsStore];
  }

  static getPropsFromStores () {
    return SettingsStore.getState();
  }

  constructor () {
    super();
  }

  isComponentDirty () {
    return this.props.isDirty;
  }

  render () {
    return (
      <div>
        <h1 className="beta push-one-half--top push-one-half--bottom">
          Settings
        </h1>
        <CardGroup>
          <AccountSettings />
          <PayoutsSettings />
          <PricingSettings />
          <SavedCardsSettings />
          <ProfileSettings />
        </CardGroup>
      </div>
    );
  }
}

Settings.willTransitionFrom = function (transition, component, cb) {
  let isComponentDirty = component.isComponentDirty();
  if (isComponentDirty) {
    if (!window.confirm('You have unsaved changes. Do you want to continue?')) {
      transition.abort('User Cancelled');
      // HACK - the router doesn't reflect the current url, so manually update that
      history.back();
    } else {
      cb();
    }
    return;
  }

  cb();
};
```

What am I doing wrong?

**Comment by taion** [comment]
That looks right to me. Wouldn't be able to tell you without further details.

**Comment by aakashlpin** [comment]
@taion: it throws `Uncaught TypeError: component.isComponentDirty is not a function` error. While if I remove `@connectToStores`, it works all good.

**Comment by johanneslumpe** [comment]
@taion @aakashlpin The issue is that `isComponentDirty` is also defined on the wrapped component and not on the connected component. The component that is being passed to the transition hook will be the connected one, which does not have the method in its prototype.

**Comment by aakashlpin** [comment]
@taion: this appears to be a Alt bug then?

**Comment by taion** [comment]
It's really the same issue as reported above - you just need to move all the statics onto the container rather than the contained component class.

**Comment by brenoc** [comment]
I had the same issue. What I did to solve was copy the static properties from the component to the high order component. You can see the code here:
https://github.com/vtex-apps/storefront-sdk/blob/master/src/utils/connectToStores.js#L52-L57

**Comment by brenoc** [comment]
Oh, and you need to declare `willTransitionTo` like this:

```js
static willTransitionTo = () => {
 ...
}
```

**Comment by goatslacker** [comment]
You can also use the statics util https://github.com/goatslacker/alt/blob/master/src/utils/statics.js to explicitly declare all your static methods.

Works as a decorator or not:

```js
export default statics({
  willTransitionTo() {
  }
}, connectToStores(MyComponent))
```
