### ISSUE TITLE
bootstrap() of partial store state causes rest of state to be undefined

### ISSUE THREAD

**Issue by mwilliams-change** [goatslacker/alt#434]
Code to illustrate the issue:

Store constructor:
```javascript
var myStore = alt.createStore(class MyStore {
    constructor() {
        this.foo = {};
        this.bar = {};
    }
   ...
```

Client init:
```javascript
alt.bootstrap('"MyStore":{"foo":{"key":"val"}}');
```

In some method of the store:
```javascript
this.foo; // { key: val }
this.bar; // undefined
```

**Comment by goatslacker** [comment]
This is the intended behavior. Bootstrap replaces all the state rather than merging it in together.

**Comment by Bangsheng** [comment]
First, I appologize for replying a closed topic. But this is the most related topic I could find to my problem. May I know how I can merge the default state with the bootstrap state instead of replacing at store level?

**Comment by goatslacker** [comment]
Get the state from the store, merge it, bootstrap that merged state.

**Comment by Bangsheng** [comment]
@goatslacker Thanks for the reply. My current solution is to merge the state during bootstrap. But I am looking for a solution which can achieve this inside the store, maybe by using onDeserialize, setState or some other ways. I tried, but still can't find such a solution.

**Comment by jdlehman** [comment]
Merging the state before or during bootstrap (as you are already doing) is probably the best solution.
