### ISSUE TITLE
Allow to specify both stores and store in AltContainer

### ISSUE THREAD

**Issue by endragor** [goatslacker/alt#436]
For some unexplained reason alt throws an exception if you provide both `store` and `stores` props to AltContainer. My first thought was that this is to prevent name clashing, but then I realised that the clashing is actually still possible when you use both `stores`/`store` and `inject`.

The ability to specify both would come very handy in my application, because usually there is a "main store" that is responsible for managing state of a certain page and there are "auxiliary stores" that manage common state of the application and might or might not be needed to render a certain component (for example, store that stores profile of the logged in user).

For now I've come with a workaround like this:

```jsx
class WrappedPage extends React.Component {
    render() {
        const functionalizedStore = _.mapValues(PageStore.getState(),
            (val, key) => () => PageStore.getState()[key]);

        const inject = Object.assign({}, functionalizedStore, {
            helpContextId: 'my_page',
            pageName: 'my_page',
            auth: () => AuthStore.getState()
        });

        return (
            <AltContainer
                stores={[PageStore, AuthStore]}
                inject={inject}
                component={Page}
                />
        );
    }
}
```

**Comment by goatslacker** [comment]
why don't you pass them all into stores rather than split them up into store and stores?

**Comment by endragor** [comment]
Because that way whenever I should access the "main" page properties (the ones that come from the main store), I'll have to use the long `this.props.nameOfTheStore.theProperty` notation which doesn't look pretty when you see it all over the code.

So this request is just about allowing the code to look cleaner in the situation when you have main and auxiliary stores used by a component.

**Comment by goatslacker** [comment]
you don't have to, you can just merge all of your state properties together if you'd like.

**Comment by endragor** [comment]
Could you please elaborate? I'm not sure I understand your comment.

**Comment by goatslacker** [comment]
Add this to your `<AltContainer />`

```js
transform={(props) => {
  return Object.assign({}, Store1.getState(), Store2.getState(), Store3.getState())
})
```

it'll merge all the states together into a single props object.
