### ISSUE TITLE
Confused sample code on view listen to  store

### ISSUE THREAD

**Issue by variable** [goatslacker/alt#438]
On this page:

http://alt.js.org/guide/view/

> But then we’ll want to listen to changes once the state in the store is updated. In your react component > on componentDidMount you can add an event handler using LocationStore.listen.

    LocationStore.listen(this.onChange);

This seems reversed while reading it naturally, the code makes me read that "the store listen to the view change."

**Comment by variable** [comment]
It makes more sense with something like

    LocationStore.addListener(this.onChange);

**Comment by goatslacker** [comment]
It definitely does. This API was [borrowed from RefluxJS](https://github.com/reflux/refluxjs#listening-to-changes-in-data-store)

I've thought about changing it to `subscribe`/`destroy` but I think that :ship: has sailed at this point.

**Comment by variable** [comment]
I think at least putting a note on the documentation and the tutorial will help a lot.

**Comment by goatslacker** [comment]
It already exists right towards the bottom of this section: https://github.com/goatslacker/alt#stores

and also here: http://alt.js.org/docs/stores/#storelisten
