### ISSUE TITLE
Get listed on CDNJS

### ISSUE THREAD

**Issue by rpeterson** [goatslacker/alt#441]
This isn't a bug or major issue, but we should work on getting Alt on CDNJS now that it is seeing some more traction.

**Comment by goatslacker** [comment]
That sounds like a good idea. Do you happen to have any experience with this?

**Comment by felguerez** [comment]
https://github.com/cdnjs/cdnjs/pull/5263

**Comment by felguerez** [comment]
https://github.com/cdnjs/cdnjs/pull/5263 closes #441

**Comment by goatslacker** [comment]
Thanks!

**Comment by goatslacker** [comment]
Whenever there's a new release I'm guessing we open a new PR?

**Comment by felguerez** [comment]
I think you're covered with the initial PR to cdnjs. 

From the [enabling `git` auto-update](https://github.com/cdnjs/cdnjs#enabling-gitrecommended-or-npm-auto-update) in the cdnjs README:

> cdnjs automatically updates libraries that are known to be hosted on npm or git repo, e.g., Lodash. npm auto-update relies on each release and git auto-update relies on the tags in git repo.
> ...
> To add git auto-update config to a library, update the package.json with configuration details and submit your pull request. ...

I included autoupdate config for `alt-with-addons.js`, `alt-with-addons.min.js`, `alt-with-runtime.js`, `alt.js`, and `alt.min.js` in the `package.json` submitted with the PR.

Thanks for creating / maintaining this repo!
