### ISSUE TITLE
Is there a way to destroy a store?

### ISSUE THREAD

**Issue by wangii** [goatslacker/alt#442]
My app allows users to open multiple instances of MessageEditor at the same time. Every MessageEditor is backed by a MessageEditingStore with messageId as the store identifier.  It's easy to create stores on-demand. however, I couldn't find a way to delete the store after a MessageBox is closed. Should I just delete the store from alt.stores, or, something wrong with my design? thanks.

**Comment by goatslacker** [comment]
deleting from alt.stores works fine :+1: .
