### ISSUE TITLE
@connectToStores and react-router

### ISSUE THREAD

**Issue by Nico-Echezarreta** [goatslacker/alt#443]
Hi,
I have already seen the other similar issue, but can't figure out how to get a way around this.
This is what i have

```javascript
@connectToStores
export default class Comp extends React.Component {
	constructor(props, context) {
		super(props, context);
	}
	static getStores() {
		return [SomeStore];
	}
	static getPropsFromStores() {
		return SomeStore.getState();
	}
    redirect() {
        this.context.router.transitionTo('/url/' + this.state.someItem.id);
    }
    render() { ... }
}

Comp.contextTypes = {
    router: React.PropTypes.func.isRequired
};
```

And the error is: Cannot read property 'transitionTo' of undefined.

Someone can explain how to fix this? :(

Thanks!

**Comment by goatslacker** [comment]
Context is getting blown away because of the HoC :(

Your top level most component should contain the router stuff, your lower level component should contain the store stuff...

**Comment by srph** [comment]
I stopped using `connectToStores` for `AltContainer` to avoid this issue.
