### ISSUE TITLE
Uncaught TypeError: subscription is not a function

### ISSUE THREAD

**Issue by ryenbeatty** [goatslacker/alt#445]
Hey there, I am having a hard time setting up a basic Alt implementation in flux. I am building a package-only Meteor app, and have a custom package that exposes the 'alt' global, which works great.

I have some Actions:

```javascript
class AccountActions {
  constructor() {
    this.generateActions(
      'loginUser',
      'loginFailed',
      'loginSuccess'
    )
  }

  loginUser(user) {
    this.dispatch(user)
      
      let email = user.email
    let password = user.password
    
    Meteor.loginWithPassword(email, password, function(error) {
      if (error) {
        this.AccountActions.loginFailed(error)
      } else {
        this.AccountActions.loginSuccess()
      }
    })
  }
}

this.AccountActions = alt.createActions(AccountActions)
```

And a Store:

```javascript
class AccountStore {
  constructor() {
    this.bindActions(AccountActions)
  }

  onLoginUser() {
    console.log('!')
  }
}
```

And my template calls the Action:

```javascript
  loginUser(e) {
    e.preventDefault()

    let data = {
      email: this.state.email,
      password: this.state.password
    }
    
    AccountActions.loginUser(data)
  }
```

So when I call the Action, I get the following error:

```
Uncaught TypeError: subscription is not a function
```

Any thoughts? Am I missing something dumb/simple?

**Comment by goatslacker** [comment]
Is there a stacktrace? This sounds like it's not an alt error.

Maybe there's a `this` binding issue?

**Comment by ryenbeatty** [comment]
stack trace:

![image](https://cloud.githubusercontent.com/assets/4946418/9125186/54b9629e-3ce1-11e5-9c2a-20655f2d724e.png)

**Comment by ryenbeatty** [comment]
could be a ```this``` binding issue incurred from Meteor.loginWIthPassword, will have to investigate.

**Comment by wlue** [comment]
I had this issue today, I was observing a store and the callback wasn't a function (it was undefined, I ended up removing the function and didn't notice).

**Comment by felguerez** [comment]
I also had this issue. Same basic issue as @wlue. It turns out I was passing `AltStore.listen()` an undefined value (via blindly following the 5 minute walk-through). 

`AltStore.listen()` and `AltStore.unlisten()` take functions as arguments, which are referred to as `subscription`. Hope this helps.

**Comment by goatslacker** [comment]
I'll add a check to make sure it throws if you don't pass in a function to listen.

**Comment by guyellis** [comment]
@felguerez - you are awesome! (I misspelled the function being passed into listen and unlisten.

**Comment by mull** [comment]
@ryenbeatty this issue can be closed right?

**Comment by goatslacker** [comment]
193206f4ab3a59352f4d9c09d2d593ba6ce6757b
