### ISSUE TITLE
Publish examples on how to test stores

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#45]
Need examples on testing stores with various frameworks: jest, jasmine, qunit, etc.

**Comment by jdlehman** [comment]
Working on this now

**Comment by goatslacker** [comment]
Cool, now I'm looking for a jest example.

**Comment by jdlehman** [comment]
Do we really need a jest example?  Jest provides a lot of nice tools for testing components, but doesn't give us anything we need to test stores.  Stores can be tested with simple unit tests and do not require mocking.  In the example I put up, there is nothing specific to any test framework (most seem to use `describe`, `it` blocks).

If you want to make sure that the docs are general and do not lean towards a particular way of doing something, we could even change the mention of `chai` to just use the built in node `assert` as the only thing I am using is `assert.equal`, so `chai` isn't even needed.

**Comment by jdlehman** [comment]
For the record, I talked to @goatslacker on gitter about the jest example, and I do think it is beneficial to add some jest examples as well.  The current examples demonstrate using a mocha/jasmine style test strategy, but jest does provide some nice tools for mocking and seems to be popular for testing React/Flux apps as it is the FB supported tool, so we should definitely not ignore it.

**Comment by goatslacker** [comment]
Got a small jest example with the example chat app.
