### ISSUE TITLE
Source loading action dispatch error

### ISSUE THREAD

**Issue by mikestopcontinues** [goatslacker/alt#451]
I've been trying to get into the groove of using alt, and I'm a bit frustrated that even when using sources, I still need to use the `setTimeout` hack. Without the following hack, I get a dispatch-during-dispatch error...

```javascript
// component
connectToStores(React.createClass({
  statics: {
    getStores(props) {
      return [PostStore];
    },

    getPropsFromStores(props) {
      return PostStore;
    }
  },

  componentDidMount() {
    PostActions.get(this.props.params.slug);
  }
}));
```

```javascript
// actions
PostActions = alt.generateActions(['get', 'getLoading', 'getSuccess', 'getError']);
```

```javascript
// source
PostSource = alt.createSource({
  get: {
    local() {return null;},
    shouldFetch() {return true;},
    remote() {return axios.get();},
    
    loading: PostActions.getLoading,
    success: PostActions.getSuccess,
    error: PostActions.getError
  }
});
```

```javascript
// store
PostStore = alt.createStore(class PostStore {
  constructor() {
    this.bindActions(PostActions);
    this.registerAsync(PostSource);
  }

  onGet() {
    if (!this.getInstance().isLoading()) {
      // what's the deal???
      setTimeout(() => this.getInstance().get(req));
    }
  }
});
```

Shouldn't next-tick behavior be baked into Sources? Or am I doing something wrong to be getting this issue?

Thanks!

**Comment by taion** [comment]
Why are you calling the data source via the actions, rather than directly on the store?

**Comment by mikestopcontinues** [comment]
I'm not. In the code sample above, the store calls the source. It's almost directly from the docs.

**Comment by powdahound** [comment]
I think that's just a misleading example in the doc, assuming you're referring to the [SearchStore.onSearch()](http://alt.js.org/docs/async/) code here. It tripped me up at first too. As I understand it, the proper flow would be to have your `componentDidMount()` call `PostStore.get(this.props.params.slug)`

**Comment by mikestopcontinues** [comment]
@powdahound, thanks, but I can't get behind that. `PostStore.get()` returns data that should be used to update the Store. That data shouldn't get returned to the view, except by subscription. That totally breaks unidirectional data flow.

**Comment by powdahound** [comment]
Well, `PostStore.get()` spawns actions that the store subscribes to, which then updates your view. You'd just be initiating the fetch from the component by calling that method. This is what the [alt-tutorial does](https://github.com/goatslacker/alt-tutorial/blob/master/src/components/Locations.jsx#L66):

```  componentDidMount() {
    LocationStore.fetchLocations();
  }```

**Comment by mikestopcontinues** [comment]
Cool. Thanks.
