### ISSUE TITLE
Namespacing for multiple data sources

### ISSUE THREAD

**Issue by nii236** [goatslacker/alt#454]
I can not find any information regarding a store that has multiple async data sources registered.

This is from the documentation:

> Now we’ll have a few methods available for use: SearchStore.performSearch(), and SearchStore.isLoading(). We can use them in SearchStore by this.getInstance().performSearch() and this.getInstance().isLoading()

`SearchSource` is the datasource, but the `performSearch()` and `isLoading()` functions are not namespaced to the datasource `SearchSource`.

What happens if I added `AnotherSearchSource`?  How would you call `isLoading()` so that it's only relevant to `AnotherSearchSource`?

**Comment by mull** [comment]
@nii236 the last encountered method would be added to the store, no name spacing. i.e. if you provide two data sources with the same method name, then the second one you provided will be available in the store.

**Comment by nii236** [comment]
Is there a way around this?

**Comment by mull** [comment]
@nii236 one could argue that more than one datasource per store is the problem. Your only way around it as far as I see is to name your methods & actions differently. Consider whether or not you're putting too many concerns into one store also.

**Comment by goatslacker** [comment]
Yeah the idea is if you've got one store with multiple data sources attached, any time a data source is "fetching" then the store is in "loading" state.
