### ISSUE TITLE
connectToStores decorator hides static methods of wrapped class

### ISSUE THREAD

**Issue by d4goxn** [goatslacker/alt#455]
The connectToStores decorator returns a new component, and does not transfer static methods to the returned component. As a result, they become inaccessible.

For example, if you use the following component as a route handler for React Router, RR will not find `willTransitionTo` on the wrapped Page component.

```js
@connectToStores
class Page extends React.Component {
	static willTransitionTo(transition, params, query) {
		console.log("transitioning");
	}

	static getStores() {
		return [PageStore];
	}

	static getPropsFromStore() {
		const state = PageStore.getState();
		return state.page;
	}

	render() {
		return <div>{this.props.page}</div>;
	}
}
```

As a workaround, static methods can be declared outside of the class declaration, so that they are assigned to the outermost class returned by the decorator. Leave the statics that `connectToStores` is expecting to find on the inner class.

```js
Page.willTransitionTo = (transition, params, query) => {
	console.log("transitioning");
}
```

Another workaround is to keep your route handlers small and simple, and have them render components that use stores, instead of using stores themselves. That might actually be an improvement, in terms of code quality / style. Separation of concerns and stuff.

**Comment by stevewillard** [comment]
+1 Have the same problem with static propTypes

**Comment by tony99nyr** [comment]
+1 
I actually thought it might have been a react-router issue at first. https://github.com/rackt/react-router/issues/1741#issuecomment-132742501

Fluxible solved this very same issue using hoist-non-react-statics. https://github.com/yahoo/fluxible/pull/176

**Comment by fraisse** [comment]
It seems to be a duplication on the #432 issue no?

**Comment by brenoc** [comment]
You can check how I solved this problem here: https://github.com/goatslacker/alt/issues/432#issuecomment-132781583

**Comment by taion** [comment]
It is - and as @goatslacker mentioned, you'll want to use `utils/statics` to handle this.

**Comment by tony99nyr** [comment]
Yup worked perfectly for me.  For additional clarity on usage:
```
import statics from 'alt/utils/statics';

export default statics({
    willTransitionTo() {
       ...
    }
},

@connectToStores
class Foo extends React.Component {
   static getStores() {
      ...
   }

   static getPropsFromStores() {
      ...
    }

   ...
})

```

**Comment by mull** [comment]
Looks like everyone got their answer!
