### ISSUE TITLE
Why connectToStores does use composition instead of mixin?

### ISSUE THREAD

**Issue by fraisse** [goatslacker/alt#457]
Using composition, a decorated component with `connectToStores` is rendered using the inner component passing then `this.props` and `this.state` as decorated component properties.

Then, "dynamic" properties of the decorated component, which should be accessible via `this.state` because a `setState` is used, become simple component properties accessible via `this.props`.

But, if these properties should have to be modified via the decorated component, the `this.setState` is used making these properties accessible via `this.state`. Then, how can we access these properties? using `this.props` or `this.state`?

I try a more mixin approach (using https://github.com/brigand/react-mixin for e.g.) and, IMHO, it works better: using the `setState` in the mixin modifies the `this.state` of the decorated component. Then, every modifications are consistent.

So, I would like to know if you have advices of using mixin over composition? Do you think this proposed way with mixin will go in a dead end?

Thanks in advance for your answer and thanks for your work.

**Comment by taion** [comment]
The benefit of using `props` instead of `state` is that it gives really good separation between things controlled by the component and things not controlled by the component. For example, I could re-use the same component in different contexts of either receiving data directly from stores, or receiving data as props from other components.

Also, it would be an error condition to call `setState` on some state you've gotten from the stores; passing store data in as props prevents this from happening.

**Comment by taion** [comment]
See also: https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

**Comment by fraisse** [comment]
I understand the first argument. Thank you for your quick answer.

Therefore, I don't understand why you said 
>it would be an error condition to call setState on some state you've gotten from the stores

When I look at examples which do not use the `connectToStores` utility, for e.g. TodoMVC (https://github.com/goatslacker/alt/blob/master/examples/todomvc/js/components/TodoApp.react.js), store listeners use naturally `this.setState` with new store state (`this.setState(getTodoState())`). Then, the render uses the component `state` properties (`allTodos={this.state.allTodos}`).

**Comment by taion** [comment]
In that context, it's fine for the listener itself to call `setState`. However, if you call `setState` for any other reason (i.e. not due to a store update), then your `state` data is confusingly out-of-sync with what's in the store.

**Comment by fraisse** [comment]
Ok, i understand.
But I don't want to modify the component state matching the data store state, I just have a component property that depend on data store state, at least, for its initialization. After that, this property gets its own life cycle, that's way `setState` is called.

At first, I initialized this property in the `getPropsFromStores` of my decorated component with the `ConnectToStores` because the data store state has just been changed. In this case, this property was accessible via `this.props`. I don't talk about data store state but the specific component property.
During the component interaction, this property has to change. Then I used `setState` making this property accessible via `this.state`.
I think you understand the inconsistence?

Thus, I created almost the same `ConnectToStore` mixin that the one provided in utils, like:
```javascript
const ConnectToStoreMixin = {
    getInitialState() {
        return this.getPropsFromStores();
    },

    componentWillReceiveProps(nextProps) {
        if (!shallowEqual(nextProps, this.props)) {
            this.setState(this.getPropsFromStores(nextProps));
        }
    },

    componentDidMount() {
        const stores = this.getStores();
        this.store_listeners = stores.map(store => {
            return store.listen(this.on_change.bind(this));
        });
        if (is.function(this.componentDidConnect)) { this.componentDidConnect(); }
    },

    componentWillUnmount() {
        this.store_listeners.forEach(unlisten => unlisten());
    },

    on_change() {
        this.setState(this.getPropsFromStores());
    }
};
```

And i use `react-mixin` in order to use it as a "real" mixin:
```javascript
export default component_class => {
    react_mixin.onClass(component_class, ConnectToStoreMixin);
    return component_class;
};
```

I can then use this mixin quite exactly as yours but the `getStores` and the `getPropsFromStores` methods don't have to be static.
With this mixin, the `this.setState` used in the `on_change` callback will affect directly the `state` of the decorated component.
Moreover, I think it solves the problem of access of some static methods like the `willTransitionTo` used by the `ReactRouter`.

Do you see problems using this mixin?

Thanks for all.

**Comment by taion** [comment]
I think you'd be much better off using e.g. `initialValue` props that are connected to the stores. That way, your dumb components end up not being tightly integrated to the stores. Ultimately this is your code, though, so it's your call which patterns work best for you.

**Comment by mull** [comment]
Looks to me like we can close this.
