### ISSUE TITLE
Second level and above nested components in AltContainer not receiving store as a prop

### ISSUE THREAD

**Issue by nii236** [goatslacker/alt#459]
When I create a component like this:

```
<AltContainer>
  <Component1>
    <Component2/>
  </Component1>
</AltContainer>
```

I noticed that `Component 2` does not receive the stores. Is this by design?

I would imagine either none of the components receive the stores as props (unless explicitly declared), or all of the components receive the stores as props. 

But here we have the first level of nested components receiving the store!

**Comment by taion** [comment]
That's how container components usually work - they almost always only inject props into the top-level children, because it gets pretty nasty to try to do so deeply throughout the tree.

**Comment by nii236** [comment]
Does this mean I'm better off declaring only a single level of nesting in this case, and then pass the stores as props manually in each extra level of nesting?

**Comment by taion** [comment]
Yes - either via `cloneElement`, or just by throwing everything into the contained component.

**Comment by wlue** [comment]
You can also implement the `render` function prop in `AltContainer` to pass props into the second level.

**Comment by nii236** [comment]
Great! Thanks all, I will try to implement some of the above suggestions.
