### ISSUE TITLE
testing component that uses `connectToStores`

### ISSUE THREAD

**Issue by peter-mouland** [goatslacker/alt#466]
I am trying to test a component that loads data from a store.  Before migrating to `alt` the test worked, now it's not.  It's a simple test as we are just getting the bare-bones app up and running. IS there an example of how to test a component?

**component**
```javascript
import React from 'react';
import connectToStores from 'alt/utils/connectToStores';
import ArticleStore from '../stores/ArticleStore';
import ArticleActions from '../actions/ArticleActions';

class ArticleView extends React.Component {

  static getStores() {
    return [ArticleStore];
  }

  static getPropsFromStores() {
    return ArticleStore.getState();
  }

  componentDidMount() {
    ArticleStore.getArticleData(this.props.params.id);
  }

  render() {

    return (
        <div>
          <h2>Article View</h2>
          <h3>{this.props}</h3>
          <h4>ftCom: {this.props}</h4>
        </div>
    );
  }
}

export default connectToStores(ArticleView);
```

**test**
```javascript
import { expect } from 'chai';
import React from 'react';
import Article from '../../src/shared/components/Article';
import createComponent from '../createComponent';

describe('Article component', function() {
  let article;

  beforeEach(function() {
    article = createComponent(Article, { params: {id: '123'} });
  });

  it('should render an article', function() {
    const articleId = article.props;
    console.log(articleId.children)//undefined
    expect(articleId.children[0].type).to.equal('h2');
    expect(articleId.children[1].type).to.equal('h3');
  });

});
```

**Comment by goatslacker** [comment]
Not sure what createComponent does or why that's not working. There's no special way to test connectToStores components. I recommend using React's component test utils.

**Comment by peter-mouland** [comment]
thanks.

for completeness, createComponent:
```javascript
import React from 'react/addons';
const TestUtils = React.addons.TestUtils;

export default createComponent;

function createComponent(component, props, ...children) {
    const shallowRenderer = TestUtils.createRenderer();
    shallowRenderer.render(React.createElement(component, props, children.length > 1 ? children : children[0]));
    return shallowRenderer.getRenderOutput();
}
```

**Comment by goatslacker** [comment]
I'll try this out

**Comment by ami44** [comment]
i'm also interested by an example which test alt store +react component

**Comment by ami44** [comment]
I search and i only found how test Action or Store (https://github.com/goatslacker/alt/tree/master/docs/testing) but not View+Store (or View+Store+Action).

Do you know where i can found examples ?
Thanks

**Comment by wonnage** [comment]
It's broken because you're using shallowRender, but connectToStores wraps your component in another component.

I had to deal with this and the two options are either to export the unwrapped component, or shallowRender twice. Dealing with the unwrapped component seemed cleaner.

**Comment by peter-mouland** [comment]
Thanks for the update - yesterday i moved to using [AltContainer](http://alt.js.org/docs/components/altContainer/) which allows me to keep to the store out of the component and pass the data as props.  Less code and seems much cleaner way of testing things.

**Comment by peter-mouland** [comment]
> closing this due to lack of interest (read: tidying up my outstanding issues feed!)
feel free to raise a new issue if you guys still care about this.
