### ISSUE TITLE
Discrepancy between tutorial and API docs.

### ISSUE THREAD

**Issue by bigblind** [goatslacker/alt#467]
In the [Fetching Data](http://alt.js.org/guide/async/) section of your "Getting Started" guide, fetchers are called by actions, and the actions dispatch data based on the response. 

In the [Handling Async](http://alt.js.org/docs/async/) section of the docs, these data sources themselves have methods for handling and dispatching actions for success and failure, and they are registered inside stores. 

It seams like on of these should be updated, but which one is correct?

**Comment by goatslacker** [comment]
I should make it clear that the tutorial is an incremental approach to teaching you how to flux. 

It doesn't exactly start with the "right way" of doing things but rather it builds up the understanding of how things are done so when you come across other patterns you can understand the "why's" of the new patterns.

There's also a discrepancy [here](http://alt.js.org/guide/view/) and [here](http://alt.js.org/guide/container-components/). In one you're listening to stores yourself and in the other you're using something like [connectToStores](https://github.com/goatslacker/alt/blob/master/src/utils/connectToStores.js) to listen to them automatically.

I would like to create a tutorial on the "blessed" way of doing things, but that'll include lots of new concepts that beginners might find surprising or confusing.
