### ISSUE TITLE
Alt getting started sample app

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#47]
What should the example app be?

I wouldn't like to do a TodoList. Already beaten to death.
The chat is already available as an example.
Email client, perhaps. But there are examples already out there.
Github search? Perhaps, but it's a bit narrow.
HN client. Also probably narrow.
RSS reader?
Music player?
A game?

Ideally this example app would:

* Be simple. Around 2 stores, 1 action
* Have asynchronous fetching involved.
* Have a store dependency so we can use `waitFor`
* Not have a very complex UI interaction, because the focus isn't the View layer.

**Comment by frederickfogerty** [comment]
The classic todomvc? :wink:

**Comment by troutowicz** [comment]
https://github.com/goatslacker/alt/tree/master/examples/todomvc

:p

**Comment by goatslacker** [comment]
I updated the issue with some ideas that have been floated

**Comment by frederickfogerty** [comment]
What more do you want out of a sample app?

**Comment by goatslacker** [comment]
Updated with what I'm looking for :) You guys sure reply fast!

**Comment by troutowicz** [comment]
There seems to be alot of debate on whether or not asynchronous operations should occur in an action, or in a store's action handler. So perhaps provide a scenario for your preferred method?

**Comment by frederickfogerty** [comment]
DaftPunKonsole in Alt.js?! http://codepen.io/kowlor/pen/MYOKRd

**Comment by bizmurr** [comment]
A full example with a server api would be good, so it not only covers the client side, but fetching and saving remote data. Maybe something like a crud interface for user accounts.

**Comment by goatslacker** [comment]
I thought about user accounts as well, nothing to do with login but just general "profile" management.

**Comment by bizmurr** [comment]
Yeah, I think that would be a pretty good practical example. :+1:

**Comment by goatslacker** [comment]
That daft punk console is legit.

**Comment by goatslacker** [comment]
https://github.com/goatslacker/alt/tree/master/guide
