### ISSUE TITLE
Partial listen to store

### ISSUE THREAD

**Issue by vkbansal** [goatslacker/alt#479]
Is it possible to partially listen to a store? What I mean is to trigger the change handler only when certain keys in the store's state are changed.

**Comment by mull** [comment]
Compare the state and see if your values have changed. :)

**Comment by vkbansal** [comment]
I'm already doing that but, I'm facing serious performance issues.

**Comment by mull** [comment]
Are you putting too much stuff into a single store? Immutable.js could be a good idea if you're dealing with equality checks for arrays/objects.

**Comment by goatslacker** [comment]
Split your store up into smaller stores where the state that you want to listen to is in another store

**Comment by vkbansal** [comment]
@mull I'm already using immutable.js

@goatslacker Then My components would have to listen multiple stores.

**Comment by mull** [comment]
Your equality checks in shouldComponentUpdate should take care of your problem just fine the way I see it. I don't know what you're storing in your stores and if they're related, maybe they belong in the same store maybe they don't.

Using shouldComponentUpdate to equality check the Lists and comparing the strings should be fast enough. Is the problem really that you're stores are updating too much, or that you're rendering too much?

**Comment by vkbansal** [comment]
After investigating I found that I was in fact rendering way too much.

Thanks @mull and @goatslacker

**Comment by goatslacker** [comment]
It's fine if your components listen to multiple stores FWIW.

This is pretty simple to setup with something like connectToStores
