### ISSUE TITLE
Data Sources: Make success and error optional

### ISSUE THREAD

**Issue by jfsiii** [goatslacker/alt#480]
We choose to handle `success`, `error` (and `interceptResponse`) behavior in our action creators to ensure the correct behavior & response format. e.g:

```
import flux from '../flux';
import FriendshipsAPI from '../api/Friendships';
import { addUserId } from '../api/transforms';

class FriendshipActions {
  constructor() {
    this.generateActions(
      'fetchFollowersFailed',
      'fetchFollowingFailed',
      'fetchFollowersSucceeded',
      'fetchFollowingSucceeded'
    );
  }

  fetchFollowers(data) {
    this.dispatch(data);

    return FriendshipsAPI.fetchFollowers(data)
      .then((data) => addUserId(data))
      .then(this.actions.fetchFollowersSucceeded,
            this.actions.fetchFollowersFailed);
  }

  fetchFollowing(data) {
    this.dispatch(data);

    return FriendshipsAPI.fetchFollowing(data)
      .then((data) => addUserId(data))
      .then(this.actions.fetchFollowingSucceeded,
            this.actions.fetchFollowingFailed);
  }
}

export default flux.createActions(FriendshipActions);
```

If we use Data Sources two success actions will be dispatched. One from the action creator (above) and one from the Data Source.

Can the API be changed to make these properties optional?

**Comment by goatslacker** [comment]
No, and I'm pretty adamant about it. I chose to make them required because it enforces you to handle your async requests through actions rather than inline in your store which is an anti-pattern.

Technically only success could be required but I chose to make failure required too so you'd always have to think about errors, specially since we're dealing with promises.

You could just skip the last then that you have in your actions and this would work as expected (except that maybe you have a cyclic dependency)

**Comment by jfsiii** [comment]
We *are* handling async requests via actions. With this approach, no matter which Source, Store, or View calls `FooActions.fetch`, we can be sure the correct actions are dispatched and transforms are applied. Otherwise, we must rely on the caller to implement this behavior.

I think the approach shown in the description is consistent with the behavior you want to enforce. We just consolidated the logic to one location.

**Comment by taion** [comment]
Why can't you handle all the requests via the data source?

**Comment by goatslacker** [comment]
Yeah I see what you're doing and that's totally :100:. If I remove the requirements though people will assume they can just call these from the stores and then handle them in place. That's what I was originally trying to avoid.

From your example, this would work as well:

```js
class FriendshipActions {
  fetchFollowers(data) {
    this.dispatch(data);

    return FriendshipsAPI.fetchFollowers(data)
      .then((data) => addUserId(data))
  }

  fetchFollowing(data) {
    this.dispatch(data);

    return FriendshipsAPI.fetchFollowing(data)
      .then((data) => addUserId(data))
  }
}
```
