### ISSUE TITLE
Question: What is the best way to batch this.setState from the Alt Store?

### ISSUE THREAD

**Issue by jcalfee** [goatslacker/alt#481]
In my Alt Store, I"m calling this.setState({...}) in a quick loop all within the main thread (not in a callback or a callback promise).  I am use to using this.setState in a component where I read that multiple calls will batch up and then only one update perform for the new state update.  In the store, I'm seeing that the components are being visited on every iteration or call to setState...

Is this the expected behaviour?  Do you recommend that I batch my own calls to setState withing the store or is their another way to do this?

**Comment by jcalfee** [comment]
More info about our particular case...

The private key store will set state for any new key that comes in.  This includes opening the wallet, importing keys, etc.. It can't know if another key is going to show up or not.  Maybe Atl could at least schedule and group the events in a promise (I'm guessing here) so that the user can keep the main thread in a loop and prevent everyone from firing (indexeddb does this).

When I do this, my components get hammered:
```javascript
<AltContainer store={PrivateKeyStore}>
    <AccountRefsOfKey/>
    <BalanceObjects/>
</AltContainer>
```

**Comment by goatslacker** [comment]
you mean you're getting multiple changes being emitted?

**Comment by jcalfee** [comment]
yes .. I see shouldComponentUpdate being called everytime my store calls setState...

**Comment by jcalfee** [comment]
Could you reference me to the code so I can understand it better?  I did find it easily by searching.

**Comment by goatslacker** [comment]
```js
import Alt from './'

const alt = new Alt()

const actions = alt.generateActions('fire')

const store = alt.createStore({
  state: { x: 0 },

  bindListeners: {
    fire: actions.fire
  },

  fire() {
    this.setState({ x: 1 })
    this.setState({ x: 2 })
    this.setState({ x: 3 })
    this.setState({ x: 4 })
  },
})

store.listen(x => console.log('changed', x))

actions.fire()

```

That emits only one event.

**Comment by jcalfee** [comment]
thank you
