### ISSUE TITLE
Cannot read property 'ref' of undefined

### ISSUE THREAD

**Issue by mhuggins** [goatslacker/alt#487]
I cloned [this boilerplate app](https://github.com/choonkending/react-webpack-node) today, which worked fine.  Now I'm working on updating all the dependencies, the biggest changes including react-router, babel-core, and babel-loader.  Unfortunately, I'm now getting an error when trying to use `AltContainer` when performing server-side rendering.

>     TypeError: Cannot read property 'ref' of undefined
>        at cloneWithProps (/Users/mhuggins/Development/ccg-redo/public/assets/app.server.js:21415:14)
>        at null.<anonymous> (/Users/mhuggins/Development/ccg-redo/public/assets/app.server.js:22894:19)
>        at Array.map (native)
>        at altRender (/Users/mhuggins/Development/ccg-redo/public/assets/app.server.js:22893:58)
>        at React.createClass.assign.render (/Users/mhuggins/Development/ccg-redo/public/assets/app.server.js:390:18)
>        at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/mhuggins/Development/ccg-redo/node_modules/react/lib/ReactCompositeComponent.js:789:34)
>        at ReactCompositeComponentMixin._renderValidatedComponent (/Users/mhuggins/Development/ccg-redo/node_modules/react/lib/ReactCompositeComponent.js:816:14)
>        at wrapper [as _renderValidatedComponent] (/Users/mhuggins/Development/ccg-redo/node_modules/react/lib/ReactPerf.js:70:21)
>        at ReactCompositeComponentMixin.mountComponent (/Users/mhuggins/Development/ccg-redo/node_modules/react/lib/ReactCompositeComponent.js:237:30)
>        at wrapper [as mountComponent] (/Users/mhuggins/Development/ccg-redo/node_modules/react/lib/ReactPerf.js:70:21)
>        at Object.ReactReconciler.mountComponent (/Users/mhuggins/Development/ccg-redo/node_modules/react/lib/ReactReconciler.js:38:35)
>        at ReactCompositeComponentMixin.mountComponent (/Users/mhuggins/Development/ccg-redo/node_modules/react/lib/ReactCompositeComponent.js:247:34)
>        at wrapper [as mountComponent] (/Users/mhuggins/Development/ccg-redo/node_modules/react/lib/ReactPerf.js:70:21)
>        at Object.ReactReconciler.mountComponent (/Users/mhuggins/Development/ccg-redo/node_modules/react/lib/ReactReconciler.js:38:35)
>        at ReactCompositeComponentMixin.mountComponent (/Users/mhuggins/Development/ccg-redo/node_modules/react/lib/ReactCompositeComponent.js:247:34)
>        at wrapper [as mountComponent] (/Users/mhuggins/Development/ccg-redo/node_modules/react/lib/ReactPerf.js:70:21)

The code in particular is pretty simple:

```jsx
import React from 'react';
import AltContainer from 'alt/AltContainer';
import UserStore from 'stores/UserStore';
import TopicStore from 'stores/TopicStore';

const App = React.createClass({
  propTypes: {
    children: React.PropTypes.object
  },

  render: function () {
    return (
      <AltContainer stores={{ UserStore, TopicStore }}>
        {this.props.children}
      </AltContainer>
    );
  }
});

export default App;
```

The server-side rendering looks similar to what is displayed in the [react-router documentation](https://github.com/rackt/react-router/blob/master/docs/advanced/ServerRendering.md).

If I substitute the `<AltContainer>` with a plan `<div>`, everything renders just fine.  Any ideas?

**Comment by goatslacker** [comment]
What version of react? I have no idea why replacing it with a div makes it work. I think it's because of the way the child is wrapped with an altcontainer?

**Comment by mhuggins** [comment]
I'm using React 0.13.3.  The backtrace stems through the AltContainer, and I only see the error if I use the AltContainer as well, so it's something to do with it in some sense.

**Comment by mhuggins** [comment]
Ugh, I take it back.  There was a stray `<Navigation/>` component being referenced that I overlooked.  It's related to that.  Sorry about that!
