### ISSUE TITLE
Create a util for data fetching

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#49]
This would settle the "how to do async" debate.

I wouldn't want this in core but I'm sure some of core would have to change so this can be supported first-class.

This util can be flexible so async can exists in actions or in stores or it can have a strict opinion.

Perhaps several interfaces can be included so this can all be hooked up easily with popular ~~cloud~~ butt based systems

**Comment by creatorrr** [comment]
I am currently using backbone models with co to fetch and update data from a server, like so:

```javascript
class SyncModel extends Backbone.Model {
  url () {
    return "/data";
  }
}

class TechnicalDataStore {
  constructor () {
    this.data = {};
    this.sync = new SyncModel(this.data);
  }

  updateSync () {
    this.sync.set(this.data);
  }

  saveData* () {
    let
      request = Promise.resolve(this.sync.save()),
      data = yield request;
    return data;
  }

  onSubmit () {
    co(this.saveData);
  }
}
``` 

If this looks like a good pattern, I could port it into a lightweight `alt` addon.

**Comment by goatslacker** [comment]
A util to interface with backbone models easily would be very welcome.

**Comment by ericclemmons** [comment]
@creatorrr: Interesting you have a generator in your store.  I've been avoiding them because of the complexity with using them on the client.  How are you solving that?

**Comment by creatorrr** [comment]
@goatslacker On my side project list! Don't you think it'd be better off letting alt core handle generators (as an opt-in feature)?

@ericclemmons [babelJS](http://github.com/babel/babel) does a decent job at supporting generators and transpiles the code down to ES5 with IE8+ support. If you really want to support IE6+, then you can use [traceur](https://github.com/google/traceur-compiler) with the es3 flag on and include all the shims and polyfills as needed.

**Comment by goatslacker** [comment]
Guess I can close this now that http://alt.js.org/docs/async/ is out.
