### ISSUE TITLE
Listen only component updates

### ISSUE THREAD

**Issue by omeshechkov** [goatslacker/alt#490]
Hello,

I have such stores structure (example):
```javascript
Shelves: {
  1: { id: 1, books: [5,6,7] },
  2: { id: 2, books: [8,9,10] },
  ...
}

Books: {
  1: {id: 1, title: 'Cinderella',}
  2: {id: 2, title: 'Harry Potter'},
  ...
}
```

Shelf component listens ShelfStore's actions (ADD, REMOVE) and BookStore's actions (ADD, REMOVE) in order to change shelf's book collection.

Book component listens BookStore's action CHANGE.

Suppose I have ~10 books on the same page. Then I fire CHANGE_BOOK action, all of the Book Components will receive BookStore's change notification and I will have to set state of every BookComponent, which is redundantly.

Is there any way to listen only events appropriate for particular instance? Or are there any best practices for such kind of problem?

Thanks in advance.

**Comment by mull** [comment]
Using `shouldComponentUpdate` (and possibly Immutable.JS for quick collection equality checks) you don't need to worry (mostly) about the number of times a component reacts to the store update. What you want to worry about is whether or not your components *should* update. Does that make sense?

**Comment by goatslacker** [comment]
React is smart enough to realize that things haven't changed and won't re-render. You could manually do checks in shouldComponentUpdate if you want to fine tune the performance of your application. If your app isn't running noticeably slow though I'd say don't worry about it and just keep building :) unless you're in perf-fix mode, then look into shouldComponentUpdate and tell React how to diff.
