### ISSUE TITLE
[react 0.14] `react/addons` and `cloneWithProps` are deprecated

### ISSUE THREAD

**Issue by SpainTrain** [goatslacker/alt#492]
With a cursory search over the repo, it looks like compatibility with 0.13 should be reasonably easy by replacing `React.addons.cloneWithProps` with `React.cloneElement`.

https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html

**Comment by goatslacker** [comment]
sure :)

**Comment by Rotemy** [comment]
Hey @goatslacker, can you please go over my last two issues? thanks

**Comment by bebraw** [comment]
Now that 0.14 is out, it would be nice to have this fixed. The warnings don't look particularly nice, esp. to new users going through the book.

**Comment by goatslacker** [comment]
Will be releasing 0.17.5 today.

**Comment by goatslacker** [comment]
eek this is going to be a breaking change...

**Comment by radiodario** [comment]
hey @goatslacker any news on 0.17.5? thanks!

**Comment by palmdeezy** [comment]
@goatslacker What's going on with this?

**Comment by goatslacker** [comment]
It's a breaking change so it'll require Alt@0.18.0. I don't want to release Alt@0.18.0 until I've got #503 in.

Alt still works with React 0.14, if you really want to get rid of the warnings however you have a few options at this point:

* Use connectToStores
* Replace the cloneWithProps stuff with React.cloneElement (if you don't care about some edge case context behavior)

I'm also open to other ideas...

I've created this repo: https://github.com/altjs/utils which houses all of the utils. I plan on also removing them from here for 0.18.0 and moving AltContainer to its own repo where you can have pre 0.14 behavior and React.cloneElement behavior.

The problem with just replacing cloneWithProps to React.cloneElement is that context gets all screwed up and some of the tests fail, so it'll be a breaking change.

**Comment by goatslacker** [comment]
Use `alt-container` package on npm.
