### ISSUE TITLE
[react-native] Uncaught SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by BerndWessels** [goatslacker/alt#495]
Hello

It looks like `alt` is not working with `react-native` at the moment.

I get `Uncaught SyntaxError: Unexpected token ILLEGAL` in `alt\lib\index.js : 1`

alt version 0.17.3
react-native version 0.11.0

From [this issue](https://github.com/goatslacker/alt/issues/328)
- I tried @0x80 fix, but that didn't help.
- I don't know how to do @ppiekarczyk fix in a react-native android application?

Still not working.

Please help, thank you
Bernd

**Comment by ppiekarczyk** [comment]
Hi BerndWessels, 

Try giving this a shot:
https://github.com/mrblueblue/react-native-alt-demo

I would start by updating react-native, alt & webpack and making sure it still works. 

I'm currently using something similar without any issues.

**Comment by BerndWessels** [comment]
OK @ppiekarczyk, I will try it tonight.

I am sure that I have the latest react-native and alt.

Not sure about webpack, I didn't install it at all, so must be unnecessary or is part of react-native.

Cheers
Bernd

**Comment by goatslacker** [comment]
Is there more to the stack trace not sure what that means

**Comment by BerndWessels** [comment]
Hi @goatslacker 
I am currently reproducing the error in a complete new clean project. Will give you more details once I have it working.
Thanks
Bernd

**Comment by goatslacker** [comment]
Closing until there are more details.
