### ISSUE TITLE
Use of JS objects as sets/maps instead of ES6 Maps

### ISSUE THREAD

**Issue by crertel** [goatslacker/alt#5]
Hello!

So, I noticed that in the `Alt` class and in the `Store` class, you use the normal JS pattern of objects-as-maps. Example would be here:

```js
// from Alt class constructor
this.actions = {}
this.stores = {}

// from Store contstructor
this[LIFECYCLE] = {}
this[LISTENERS] = {}
```

The use of `this` as an overloaded object-as-map seems central to a lot of the code, but for the examples I gave it's not as clear.

Why not use the ES6 Maps for this purpose?

**Comment by goatslacker** [comment]
The thought crossed my mind before but there's two reasons why I didn't go through with it:

* I don't want to introduce a Map polyfill and increase the size of the bundle dramatically.
* While maps are nice I'm getting away with just using strings and symbols as keys so I'm keeping it simple.

**Comment by crertel** [comment]
Thanks for the discussion! :)

**Comment by goatslacker** [comment]
Np, cheers!
