### ISSUE TITLE
Cannot dispatch in the middle of a dispatch

### ISSUE THREAD

**Issue by NetanelBasal** [goatslacker/alt#500]
I am trying to call to login action after the register action and i get this error.

This are my files and i am calling to AuthActions.register():

//AuthActions.js

```js
  register( user ) {
    $.ajax({
    ...ajax to register the user
    }).then(( res ) => {
      this.dispatch(res);
    });
  }

  loginAction( user ) {
    ...ajax to get the user
    this.dispatch(user);
  }

```

//RegisterStore.js
```js
this.bindListeners({
    register: AuthActions.register
 });

 register( user ) {
      // here i get the error
      AuthActions.loginAction(user);
  }

```

//LoginStore.js

```js
login() {
 //login the user
}

```

**Comment by goatslacker** [comment]
You shouldn't be calling an action inside a store, why don't you handle the login stuff inside the register method?

**Comment by NetanelBasal** [comment]
Because the code related to the LoginStore and my other components are listening to LoginStore, why i need all this duplication? what you suggest to do? thanks.

**Comment by goatslacker** [comment]
Have your LoginStore listen to the register action and log the user in.

**Comment by bigblind** [comment]
@goatslacker Can you clarify what you mean by "log the user in?" Wouldnt that involve doing what's currently happening in loginAction? 

I'm currently having a similar issue, where my app wants to fetch user data as soon as the user has logged in, but I can't do it directly in a listener to the auth store, because it'll trigger this error, so I'm finding myself using `setTimeout(()=> fetchData() )` all over the place, which doesn't look good.

**Comment by goatslacker** [comment]
Unless login happens in a variety of places, I imagine you have 1 react component that takes care of logging in. Under these assumptions...

```js
class Login extends React.Component {
  doLogin() {
    attemptToLogUserIn(username, password).then((user) => {
      // you could return your user information here...
      // or not, we could just query for it

      return fetchUserInformation()
    })
  }

  render() {
    return (
      <form>
        <button onClick={this.doLogin}>Login</button>
      </form>
    )
  }
}

```


In NetanelBasal's particular example you can do:

```js
  register( user ) {
    $.ajax({
    ...ajax to register the user
    }).then(( res ) => {
      this.dispatch(res);
      this.actions.loginAction(user)
    });
  }

  loginAction( user ) {
    ...ajax to get the user
    this.dispatch(user);
  }
```

**Comment by NetanelBasal** [comment]
Yes thats works for me, thanks by the way.

**Comment by CreativeManix** [comment]
As per the latest release the dispatch method is removed. How can we do the same without dispatch method?

**Comment by goatslacker** [comment]
@CreativeManix I've updated the example to reflect the latest changes.
