### ISSUE TITLE
ActionsClass usage

### ISSUE THREAD

**Issue by wonnage** [goatslacker/alt#501]
I have some information in my stores, that my actions need to pass when creating an API client object. I'm using alt instances, so the API constructor has no access to these stores - I have to pass the data in Intuitively, I'd do something like this:

````
class MyAction {
  constructor() {
    this.apiClient = new ApiClient(this.alt.stores.AuthStore.getStuff());
  }
  
  makeRequest(params) {
    this.dispatch(params)
    this.apiClient.get('/endpoint', params)
  }
}
````

Unfortunately, this doesn't work, because the way Alt creates actions rips all the methods off of this class and binds them to an AltAction instead. Do you have any suggestions on alternatives, or maybe how we could improve how makeActions works with a class? As it stands, the classes don't behave like classes at all, and might as well be object hashes.

**Comment by goatslacker** [comment]
> As it stands, the classes don't behave like classes at all, and might as well be object hashes.

+1

let me think about this.

**Comment by goatslacker** [comment]
ok there are two options here.

remove this.dispatch from alt or remove action classes altogether.

**Comment by taion** [comment]
Hey! I made the exact same complaint here: https://github.com/goatslacker/alt/issues/359 :D

I had a few proposals there toward the end of the thread, all of which would have been major breaking API changes, but probably getting rid of action classes would be the simplest approach by far.

**Comment by goatslacker** [comment]
#503

**Comment by goatslacker** [comment]
Will be releasing this at some point soon.
