### ISSUE TITLE
Lifecycle listeners beforeEach and afterEach firing in wrong place? 

### ISSUE THREAD

**Issue by mkontula** [goatslacker/alt#505]
Using 0.17.4 and documentaqtion from https://github.com/goatslacker/alt/blob/master/docs/lifecycleListeners.md I thought that: 
1. beforeEach is supposed to fire before the action reaches the listening stores
2. afterEeach is supposed to fire after the store has published the change in it's state

Using connectToStores to keep things cleaner, I came across the following order with debug:
1. Action was dispatched
2. Store received the action
3. Listening Component received new props (getPropsFromStores)
4. Store's beforeEach fired
5. Store's afterEach fired

I was hoping to be able to do common error handling and other interception in beforeEach. Is this behavior by design or have I missed something or totally messed up my code?

**Comment by goatslacker** [comment]
```js
import Alt from 'alt'

const alt = new Alt()

const actions = alt.generateActions('current')

const store = alt.createStore(class {
  constructor() {
    this.on('beforeEach', () => console.log('before', this.state))
    this.on('afterEach', () => console.log('after', this.state))
    this.bindActions(actions)

    this.state = { x: 0 }
  }

  current() {
    console.log('current before', this.state)
    this.setState({ x: 1 })
    console.log('current after', this.state)
  }
})

actions.current()

```

I get it in the right order, what are you doing?

**Comment by goatslacker** [comment]
Closing for now. Feel free to re-open.
