### ISSUE TITLE
Warning: An action was called but nothing was dispatched

### ISSUE THREAD

**Issue by aksonov** [goatslacker/alt#506]
Could you clarify why it happens? I'm using alt from my component, react-native-router-flux and have such warnings after each 'action' call. Maybe it is connected that actions call another actions?
https://github.com/aksonov/react-native-router-flux/issues/13

**Comment by goatslacker** [comment]
Yeah it's just a warning. Sometimes you fire an action but it doesn't dispatch and it's because you're returning undefined. This will be even more useful once alt switches completely to return to dispatch.

**Comment by aksonov** [comment]
So all store methods should return 'true' to avoid this warnings? I thought setState should be enough at the end of store listeners...

**Comment by goatslacker** [comment]
no it's the actions not the store

**Comment by aksonov** [comment]
Could you clarify how to avoid this warning? All actions in my component are really dispatched, maybe problem that they return other actions?

                    RouterActions[name] = alt.createAction(name, function (data) {
                        if (typeof(data)!='object'){
                            data={data:data};
                        }
                        var args = {name: name, data:data};
                        var action = child.props.type || 'push';
                        return RouterActions[action](args);
                    });

**Comment by goatslacker** [comment]
what does RouterActions[action](args) return?

**Comment by aksonov** [comment]
It just returns input params

Pavel.

**Comment by skylinezum** [comment]
I've been seeing this warning as well and I tried to test if I'm doing something wrong.

in my actions:
    
    fetchLogs(filter) {
       //get logs with a filter
       var data = ['added new mes', 'created new share'];

       this.actions.updateLogs(data);
    }

in my store

    onUpdateLogs(data) {
       this.setState({
         data: data
       });
       console.log(this.state.data);
    }

console outputs the expected array, and yet the warning shows up.

**Comment by thesnackalicious** [comment]
I'm getting this warning as well, my `create` action calls `this.actions.creating` which does a dispatch, but the warning still shows up.

**Comment by Faolain** [comment]
I have the same issue

**Comment by goatslacker** [comment]
I'm going to remove this warning in the next release and table it until I get rid of this.dispatch in actions.

**Comment by iam4x** [comment]
@goatslacker Thank's :+1:

**Comment by sahat** [comment]
:+1:

**Comment by jamesfzhang** [comment]
@goatslacker I still see this warning in the latest release (0.18.4). Any plans to remove it? I'm setting running `console.warn = function(){}` to disable the warnings right now.

**Comment by StefanSchwartze** [comment]
Would be great to have the possibility to turn this off.

**Comment by ethan-deng** [comment]
I saw this too in 0.18.4
ReferenceError: An action was called but nothing was dispatched

**Comment by rahulthewall** [comment]
Yeah, I am getting these warnings ever since I upgraded from 0.17.9 to 0.18.6. Would love to disable them.

**Comment by olypros** [comment]
Warning here too. Someone disable it please ? submit some merge

**Comment by imerkle** [comment]
@goatslacker  any update on this ?

**Comment by eshenk** [comment]
For those who are my kind of stupid: Note that every function in your Action class will get wrapped and checked for a return value.  So I had a helper function like this in my class:
```
  callAjax(etc) {
    $.ajax(etc);
  }
  doAction() {
    this.callAjax(etc);
    return true;
  }
```
So even though the action itself returned a value, the "callAjax" function did not and therefore was throwing the warning.  Lesson:  Don't put any helper functions in the class itself.  Import them.

**Comment by imerkle** [comment]
@eshenk use mobx. im using mobx

**Comment by CrazyPython** [comment]
FYI, you can disable this for your own repo by changing `"alt": "version number"` to `"alt": "crazypython/alt#silence-payloadless-dispatch-warning"`. You can always edit a package's source code, fork it, and then install from GitHub.
