### ISSUE TITLE
Alt devtool

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#51]
Developer tool (Chrome first) for using Alt.

You can help by discussing things you want to see in it and by contributing that code.

**Comment by srph** [comment]
I think you forgot the link to the repository. Anyway, [**alt-devtool**](https://github.com/goatslacker/alt-devtool).

**Comment by goatslacker** [comment]
Oh it's not ready yet :)

**Comment by goatslacker** [comment]
ad9c2bb5a2b8df13c4f0ac3e3360e95ffcffb0f0
