### ISSUE TITLE
Best way to route authenticated page

### ISSUE THREAD

**Issue by bsdo64** [goatslacker/alt#515]
I'm new to react 0.14.0, react-router 1.0.0-rc3.
But when I routes some url, all alt store's state of page which is rendered from server are reset.
So I can't access authenticated page

Further more, I'm using jwt auth with cookie, I can't access jwt and initialize store witch depend on user auth. 
So, is there a way to initialize and maintain all page's state? What could be the best practice?

**Comment by rozzzly** [comment]
um I think this would have to be more of a `react-router` issue? and idk what `jwt` is.

> [...] routes some url, all alt store's state of page which is rendered from server are reset [...] 

are you trying to say you're authed if the server render's it, but when you try to do something locally, you don't have access?

**Comment by bsdo64** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

bsdo@naver.com 님께 보내신 메일 <Re: [alt] Best way to route authenticated page (#515)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by rozzzly** [comment]
Well, I don't know how to respond to that. Best of luck.

**Comment by bsdo64** [comment]
I found some solution initializing some data with by serverside rendering.
With [Iso Example](https://github.com/choonkending/react-webpack-node/blob/master/server/config/routes.js) by using locals I could initialize some datas

Like this
````javascript
app.use((req, res) => {
    res.locals.data =  {
      TopicStore: { topics: topicmap},
      UserStore: { user: user }
    };
    next();
}

app.use((req, res) => {
    var html = App(JSON.stringify(res.locals.data || {}), req, res);
    html = html.replace("TITLE", Header.title)
                .replace("META", Header.meta);

    if(process.env.NODE_ENV === 'devhotloader') {
      html = html.replace("LINK", '');
    } else {
      html = html.replace("LINK", Header.link);
    }

    res.contentType = "text/html; charset=utf8";
    res.end(html);
});
````

Thanks choonkending!

I'll close this ticket
