### ISSUE TITLE
alt.dispatcher.register exception on startup

### ISSUE THREAD

**Issue by jcalfee** [goatslacker/alt#516]
alt-instance.js (this is our own class, just an example)
```javascript
var Alt = require("alt");
var alt = new Alt();

// DEBUG log all action events
alt.dispatcher.register('alt.dispatcher', console.log.bind(console))

module.exports = alt;
```

When alt-instance is included as it is above with the `alt.dispatcher.register` statement, the following error occurs and prevents the app from running:

`Uncaught TypeError: this.$Dispatcher_callbacks[id] is not a function`

Dispatcher.js
```javascript
  /**
   * Call the callback stored with the given id. Also do some internal
   * bookkeeping.
   *
   * @param {string} id
   * @internal
   */
  Dispatcher.prototype.$Dispatcher_invokeCallback=function(id) {
    this.$Dispatcher_isPending[id] = true;
    this.$Dispatcher_callbacks[id](this.$Dispatcher_pendingPayload);
    this.$Dispatcher_isHandled[id] = true;
  };
```

This is likely timing, I was able to register the console.log in the dispatcher in my code by letting the webpack hot loader update it live (no  reloading or refreshing) and I did see it work.

**Comment by goatslacker** [comment]
That's because alt.dispatcher.register takes a function as its only arg. Not a string

**Comment by jcalfee** [comment]
I owe you like 3 beers now...  I was intending to write it like this: `alt.dispatcher.register(console.log.bind(console, 'alt.dispatcher'))`

**Comment by goatslacker** [comment]
Haha. It happens 🍻🍺
