### ISSUE TITLE
How to handle requests that can be canceled?

### ISSUE THREAD

**Issue by janpieterz** [goatslacker/alt#517]
I have a question about actions that execute an ajax request, that should be cancelled.
For example, a user moves to a collection page, finds out that it is the wrong collection, navigates back and into a new page before the collection is retrieved.

I can solve this by keeping track of the last collection id that is retrieved, and discarding all results that don't match this id, but that seems dirty, since the right action would be to cancel the request and then fire a new one.

I can keep a reference to this request and cancel this, but the question than remains where the best place for this would be. Firing an action, starting the request, passing the request to the store places it in the store, which seems a bit weird. Keeping it in the action also doesn't feel right (and I'm not even sure is possible; perhaps related: #503 )

I'm very curious towards a solution, so far I haven't found any real input on this, let alone input using alt.

**Comment by taion** [comment]
FWIW I've handled this sort of pattern by storing all collections in my stores, and just showing the relevant one - makes state management easier too. You can then e.g. track all pending queries if you want (but you don't have to).

**Comment by goatslacker** [comment]
If you ever need to store something, anything, you put it in a store 😀

**Comment by janpieterz** [comment]
Sweet, thanks for the clarity.
