### ISSUE TITLE
Future of Alt

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#52]
This is just to openly discuss any ideas on where you'd like to take alt or what you'd like to do with it. Perhaps actionable tasks can come out of this discussion.

**Comment by creatorrr** [comment]
With [React v0.13](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html) the use of ES6 classes will be available. Also, according to facebook/react#1380 mixins will not be supported for ES6 classes like they are today with createClass.

So, keeping those in mins,
 1. Are there any plans for supporting `alt` with ES6 classes once React v0.13 lands (which is coming soon)?
 2. Consideration should be made for alternatives to implement the functionality currently offered via mixins.

**Comment by goatslacker** [comment]
You can already use alt with `React.Element` in v0.13. It seems like mixins are going to be left to be addressed at the language level, if there's a solution that pops up though alt will pick it up and support it. 

It was mentioned that there will be [first-class support for flux store subscriptions](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#mixins), that's an interesting development.

**Comment by bjyoungblood** [comment]
With actions that fetch data asynchronously, it seems to be a pretty common pattern to have associated success and failure actions. It might be worthwhile to explore a way to auto-generate those.

`this.generateActions` could possibly be modified to support an API [similar to Reflux's](https://github.com/spoike/refluxjs#asynchronous-actions).

To take this a bit further, I think it's common for an action to create a Promise that calls a corresponding success or failure action with its result. [MartyJS achieves this](http://martyjs.org/guides/action-creators/index.html) by creating the actions and triggering one of them for you with the result of the promise.

**Comment by RnbWd** [comment]
Maybe use a mixin pattern like this? https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775

**Comment by creatorrr** [comment]
@RnbWd Interesting but how would this work with multiple mixins overriding the same methods?

**Comment by creatorrr** [comment]
@goatslacker Another question for alt is whether it's better to keep it to a small and extensible core or expand it to provide a decent feature set for developing frontend apps. IMHO, the direction of this conversation will depend on that.

**Comment by RnbWd** [comment]
@creatorrr having multiple mixins overriding the same methods sounds like a bad idea.. honestly I don't know.  Do the current mixins override the same methods? I was just passing along a tweet I saw @gaearon post.

Also, haven't tried out all the new mixins yet, are there conflicts with overriding methods? I'm still experimenting within mixin alternatives.. not sure what the pros and cons are yet.

**Comment by gaearon** [comment]
>Interesting but how would this work with multiple mixins overriding the same methods?
>having multiple mixins overriding the same methods sounds like a bad idea.

In React, mixins currently have "merging" behavior for lifecycle methods (or mixins would be useful). This is implicit and makes mixin-heavy codebase harder to maintain as it grows.

That "higher level components" gist solves this problem by *wrapping* components. This way you get lifecycle methods called for free by the virtue of wrappers being real components and thus also receiving lifecycle hooks.

I think Flummox chose right approach: components over mixins. See [Why Flux Component is better than Flux Mixin](https://github.com/acdlite/flummox/blob/master/docs/why-flux-component-is-better-than-flux-mixin.md). In the recent release, custom rendering was added, I dig this approach:

```js
let BlogPostPage = React.createClass({
  render() {
    <div>
      <SiteNavigation />
      <MainContentArea>
        <FluxComponent
          connectToStores={{
            posts: (store, props) => ({
              post: store.getPost(props.postId),
            })
          }}
          render={props => {
            // render whatever you want
            return <BlogPost {...props} />;
          }}
        />
      </MainContentArea>
      <SiteSidebar />
      <SiteFooter />
    </div>
  }
});
```

Gives you full control, and no mixins.

**Comment by goatslacker** [comment]
cc @mattmccray who's exploring components over mixins in alt.

**Comment by mattmccray** [comment]
Yeah, I've just started working with components vs mixins in a new app I'm working on.

I called mine `Controller` and it has a few API changes from `FluxComponent` -- Mainly I don't like that `render` prop, so I have it applying a context to child components. You can see it here: https://gist.github.com/mattmccray/5f3a8cd7935404830a63

It's likely to evolve, and I welcome feedback. So far it's actually been kinda fun to use. That said, I haven't had to do anything hairy with it yet.

**Comment by gaearon** [comment]
Just noting that React has its own concept of `context` so it may be better to avoid naming confusion. In fact, in React 0.14 it will behave exactly the way you might want for `Controller`.

**Comment by mattmccray** [comment]
True! I need to change `context

Yeah, I'm interesting in parent-based contexts. Primarily for formdata management with custom fields, but also this kind of use.

There's simplicity in passing props, and passing data in a react context is rather obscure... So I'm not sure if a `Controller` that passes data via a react context is a great idea.

**Comment by acdlite** [comment]
Yeah, I agree. Context is usually a hack and should be avoided, hence why it's undocumented. Flummox uses it (optionally) to expose the main Flux instance to arbitrarily nested views, but never for passing store state.

**Comment by goatslacker** [comment]
@creatorrr late answer to one of your questions. I aim to keep alt core small but provide many components, mixins, and utils.

**Comment by pekeler** [comment]
When Relay is released, how will this impact Alt?

**Comment by goatslacker** [comment]
Good question, I don't think something like Relay will replace Flux and there's a [good section on it here](https://gist.github.com/wincent/598fa75e22bdfa44cf47#How_does_it_relate_to_Flux). I do expect to support the bits of Relay that I can and are useful though.

**Comment by troutowicz** [comment]
@pekeler 
As the link @goatslacker posted explains, Relay is a framework whereas Flux is a front-end design pattern. Relay will be useful for complex applications with many components that require data fetching from a server. Instead of child components depending on data being passed down from N number of parents, the component can statically declare its data dependencies within itself. This will make components more modular and provide a clearer, simpler picture of the needs of each component.

**Comment by cpsubrian** [comment]
To add to the higher-order-components vs. mixins coversation, I've been using the following utility with alt. Note: this works whether you use ES6 classes or createClass().

**connect_to_stores.jsx**
```jsx
import React from 'react'

/**
 * 'Higher Order Component' that controls the props of the wrapped
 * component via stores.
 *
 * Expects the Component to have two static methods:
 *   - getStores(): Should return an array of stores.
 *   - getPropsFromStores: Should return the props from the stores.
 */
const connectToStores = function (Component) {

  // Cache stores.
  const stores = Component.getStores()

  // Wrapper Component.
  const StoreConnection = React.createClass({

    getInitialState () {
      return Component.getPropsFromStores(this.props)
    },

    componentDidMount () {
      stores.forEach(store => store.listen(this.onChange))
    },

    componentWillUnmount () {
      stores.forEach(store => store.unlisten(this.onChange))
    },

    onChange () {
      this.setState(Component.getPropsFromStores(this.props))
    },

    render () {
      return <Component {...this.props} {...this.state} />
    }
  })

  return StoreConnection
}

export default connectToStores
```

**component.jsx**
```jsx
import React from 'react'
import connectToStores from './connect_to_stores'
import myStore from './store'

const MyComponent = React.createClass({

  statics: {
    getStores () {
      return [myStore]
    },
    getPropsFromStores (props) {
      return {
        myProperty: myStore.getState().myProperty
      }
    }
  },

  render () {
    return (
      <div>
        <h1>My Component</h1>
        <p>
          {this.props.myProperty}
        </p>
      </div>
    )
  }
})

export default connectToStores(MyComponent)
```

If you want to use ES6 classes you can just use regular `static` methods like:

```jsx
// ...

class MyComponent extends React.Component {

  static getStores () {
    return [myStore]
  }

  static getPropsFromStores (props) {
    return myStore.getState();
  }
}
// ...
```

**Comment by troutowicz** [comment]
@cpsubrian :+1: 

I really like that approach!

**Comment by goatslacker** [comment]
@cpsubrian I wouldn't mind merging this in if you want to submit a PR

**Comment by cpsubrian** [comment]
Oh cool. I'll work up a PR over the next few days as time allows :)

**Comment by cpsubrian** [comment]
Posted PR at #115

**Comment by srph** [comment]
@bjyoungblood Has anybody or have you tried this approach?

```js
// Action
fetch() {
  fetchUtil.doSomethin()
    .then((res) => {
      this.dispatch({ data: res.data, err: null });
    })
   .catch((err) => {
      this.dispatch({ err: null });
   })
}

// Store
handleFetch(result) {
  var { err, data } = result;
  if ( err ) // do something

  // whatever
}
```

It's just an attempt to simplify success and error actions. But this has downsides, which most I can't take note at the moment.

**Comment by goatslacker** [comment]
Thanks for feedback everyone <3

We've got 
* A [function that wraps components](https://github.com/goatslacker/alt/blob/master/src/utils/connectToStores.js)
* A [higher-order component](https://github.com/goatslacker/alt/blob/master/components/AltContainer.js) that acts as a high-performance container.

**Comment by stowns** [comment]
if we're using flux instances as shown http://alt.js.org/docs/altInstances/ how can we take advantage of connectToStores()? this.props.flux isn't available in the static methods defined on the class. Should these 2 just not be used together?
