### ISSUE TITLE
AltContainer using depreciated React-Addons

### ISSUE THREAD

**Issue by nlhkh** [goatslacker/alt#521]
In React 0.14, AltContainer still use the addons from React 0.13.3, and this error message shows up

```
Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.
```

**Comment by goatslacker** [comment]
No it doesn't https://github.com/altjs/container/blob/master/src/AltContainer.js#L58 :)

**Comment by sizeon** [comment]
I guess it's not yet updated in alt 17.6 ?  Or is it under a different repo in NPM?

**Comment by goatslacker** [comment]
It won't be part of alt. It's on npm

`npm install alt-container`

**Comment by nlhkh** [comment]
Oh, so it is a separated package now right? I didn't see any documentation on this :)

**Comment by Lockyy** [comment]
It seems like the package of Alt being served isn't including that version of AltContainer that you linked @goatslacker. I'm currently on version 0.17.7 and components/AltContainer is still the old version.

![screen shot 2015-10-29 at 18 19 43](https://cloud.githubusercontent.com/assets/1465268/10827982/d05e24c4-7e69-11e5-84dc-0b5c0d234953.png)

**Comment by goatslacker** [comment]
@Lockyy @nlhkh 

`npm install alt-container`

and in your app

```js
import AltContainer from 'alt-container';
```

The legacy AltContainer is also available in that package so you can also use it with older versions of alt.

**Comment by alexklibisz** [comment]
:+1:
