### ISSUE TITLE
How to work with Super class?

### ISSUE THREAD

**Issue by JoeGrasso** [goatslacker/alt#527]
**I have 3 forms of navigation on a website:**

     (1) Top Navigation, 
     (2) Mobile Navigation, 
     (3) Side Bar Navigation (filtered items). 

They all take from the same store, but have different render mark up. Why should I have each connect to a store, when I can have a super class connect to the store and let them just inherit?

This works as a stand alone:

**top-nav-zone.js**

     import React, { Component, PropTypes } from 'react';
     // components
     import NavMenuItem from './top-nav-menu-item';
     // alt
     import NavStore from '../../../alt/stores/nav-store';
     import NavActions from '../../../alt/actions/nav-actions';
     import connectToStores from 'alt/utils/connectToStores';

     class TopNavZone extends Component {

       static getStores() {
         return [NavStore];
       }

       static getPropsFromStores() {
         return NavStore.getState();
       }

       componentDidMount() {
         const clientId = this.props.clientId;
         // Loading initial data from server
         NavActions.getNavItems(clientId);
       }

       fetchMenu() {
         const results = [];
         const navItems = this.props.navItems;
         navItems.map((item, index) => {
           results.push(
             <NavMenuItem key={ index }
                          clientId={ this.props.clientId }
                          item={ item }
                          index={ index }
                          parent={ this.refs.navList }/>
           );
         });
         return results;
       }

       render() {
         // if (!this.state.navItems) return <div>Loading ...</div>;
         return (
           <section>
              <nav>
                <ul>
                 { this.fetchMenu() }
               </ul>
             </nav>
           </section>
         );
       }
     }

     TopNavZone.propTypes = {
       clientId: PropTypes.string.isRequired,
       navItems: PropTypes.array
     };

     export default connectToStores(TopNavZone);

But, if I take that same basic code, without the render & fetch (as they are top-nav-zone specific) and put it in a super class called Navigation, and instead do this:

**navigation.js**

     import { Component } from 'react';
     // alt
     import NavStore from '../../alt/stores/nav-store';
     import NavActions from '../../alt/actions/nav-actions';
     import connectToStores from 'alt/utils/connectToStores';

     class Navigation extends Component {

       static getStores() {
         return [NavStore];
       }

       static getPropsFromStores() {
         return NavStore.getState();
       }

       componentDidMount() {
         const clientId = '1234';
         // Loading initial data from server
         NavActions.getNavItems(clientId);
       }
     }

     export default connectToStores(Navigation);

**top-nav-zone.js**

     import React, { PropTypes } from 'react';
     // super class
     import Navigation from '../index';
     // components
     import NavMenuItem from './top-nav-menu-item';

     export default class TopNavZone extends Navigation {

       fetchMenu() {
         const results = [];
         const navItems = this.props.navItems;
         navItems.map((item, index) => {
           results.push(
             <NavMenuItem key={ index }
                          clientId={ this.props.clientId }
                          item={ item }
                          index={ index }
                          parent={ this.refs.navList }/>
           );
         });
         return results;
       }

       render() {
         // if (!this.state.navItems) return <div>Loading ...</div>;
         return (
           <section>
             <nav className="top-nav" id="TopNavigation" _flyout="true" data-aflyout="true"      name="TopNavigation">
               <ul ref="navList" className="">
                 { this.fetchMenu() }
               </ul>
             </nav>
           </section>
         );
       }
     }

     TopNavZone.propTypes = {
       clientId: PropTypes.string.isRequired
     };
 
The app breaks and I receive this error:

Uncaught (in promise) TypeError: Cannot read property 'bind' of undefined(…)bindAutoBindMethod @ ReactClass.js:554bindAutoBindMethods @ ReactClass.js:596Constructor @ ReactClass.js:695TopNavZone @ top-nav-zone.js:77TopNavZone @ VM579:4ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:148wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:37ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:241ReactDOMComponent.Mixin._createContentMarkup @ ReactDOMComponent.js:592ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:482ReactReconciler.mountComponent @ ReactReconciler.js:37ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:241ReactDOMComponent.Mixin._createContentMarkup @ ReactDOMComponent.js:592ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:482ReactReconciler.mountComponent @ ReactReconciler.js:37ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:241ReactDOMComponent.Mixin._createContentMarkup @ ReactDOMComponent.js:592ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:482ReactReconciler.mountComponent @ ReactReconciler.js:37ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:241ReactDOMComponent.Mixin._createContentMarkup @ ReactDOMComponent.js:592ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:482ReactReconciler.mountComponent @ ReactReconciler.js:37ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:37ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:241ReactDOMComponent.Mixin._createContentMarkup @ ReactDOMComponent.js:592ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:482ReactReconciler.mountComponent @ ReactReconciler.js:37ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:241ReactDOMComponent.Mixin._createContentMarkup @ ReactDOMComponent.js:592ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:482ReactReconciler.mountComponent @ ReactReconciler.js:37ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:37ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:241ReactDOMComponent.Mixin._createContentMarkup @ ReactDOMComponent.js:592ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:482ReactReconciler.mountComponent @ ReactReconciler.js:37ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:37ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:37ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:37ReactCompositeComponentMixin._updateRenderedComponent @ ReactCompositeComponent.js:570ReactCompositeComponentMixin._performComponentUpdate @ ReactCompositeComponent.js:544ReactCompositeComponentMixin.updateComponent @ ReactCompositeComponent.js:473wrapper @ ReactPerf.js:66ReactCompositeComponentMixin.performUpdateIfNecessary @ ReactCompositeComponent.js:421ReactReconciler.performUpdateIfNecessary @ ReactReconciler.js:102runBatchedUpdates @ ReactUpdates.js:129Mixin.perform @ Transaction.js:136Mixin.perform @ Transaction.js:136assign.perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147wrapper @ ReactPerf.js:66Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62enqueueUpdate @ ReactUpdates.js:176enqueueUpdate @ ReactUpdateQueue.js:24ReactUpdateQueue.enqueueSetState @ ReactUpdateQueue.js:190ReactComponent.setState @ ReactComponent.js:64(anonymous function) @ index.js:99

How can this be? It seems pretty straight forward?????

**Comment by jdlehman** [comment]
`connectToStores` actually wraps your component with another component that handles passing the store data down as props for you. (you can see this component tree in the React dev tools in your browser).

So what is actually happening in your code is that `TopNavZone` is extending the wrapper around `Navigation` instead of `Navigation` itself.  You can fix this by using a named export to just export the `Navigation` class or make the default export for `Navigation` and wrap it with `connectToStores` elsewhere.

**Comment by JoeGrasso** [comment]
OK, I got this to work with  some simple changes:

**navigation.js**
     1. export default class Navigation extends Component
     2. remove the connectToStores

**top-navigation-zone**
    1. class TopNavZone extends Navigation 
    2. export default connectToStores(TopNavZone);
