### ISSUE TITLE
Actions / async function called twice

### ISSUE THREAD

**Issue by maxs15** [goatslacker/alt#528]
Hey,

I'm having some trouble with an async function in my action, for some mysterious reason, it is called twice..

Here is my code for example:
```js
class HomeActions {
	fetch() {
		console.log('step 1');
		return (dispatch) => {
			console.log('step 2');
			util.get('apps')
			.then((apps) => {
				dispatch(apps)
			});
		}
	}
}
```

The step 1 is only called once, but the step 2 is called twice.
Am I doing something wrong or is it a bug in Alt ?

Thanks for the help

**Comment by goatslacker** [comment]
not sure, that looks fine...

I just ran this on an empty project and it dispatches once for me

```js
import Alt from 'alt'

const alt = new Alt()


class HomeActions {
  fetch() {
    console.log('step 1');
    return (dispatch) => {
      console.log('step 2');
      setTimeout(() => dispatch(5))
    }
  }
}

const ha = alt.createActions(HomeActions)

ha.fetch()

```

**Comment by maxs15** [comment]
Indeed, my fault, I just discovered that I called createStore twice by mistake..

Thanks for the fast answer ! :)
