### ISSUE TITLE
Decorater combined with contextTypes does not work

### ISSUE THREAD

**Issue by jbandi** [goatslacker/alt#529]
I have a React component that uses a context (location from ReactRouter).

The following code works:

```javascript
class Footer extends React.Component {
  // use this.context.location
}

Footer.contextTypes = {
    location: React.PropTypes.object.isRequired
};
export default connectToStores(Footer);
```

However the following code does not work:
```javascript
@connectToStores
export default class Footer extends React.Component {
  // Problem: this.context.location is undefined!
}

Footer.contextTypes = {
    location: React.PropTypes.object.isRequired
};
```

I guess this has to do with the fact, that the Decorater function is executed before the context is attached to the class, and therefore the context is not copied to the wrapper-opject inside `connectToStores` ... 

Is there somehow a way to use the decorater together with React contexts?

**Comment by wlue** [comment]
I'd recommend defining context types like this:

```
@connectToStores
export default class Footer extends React.Component {
    static contextTypes = {
        location: React.PropTypes.object.isRequired
    };
}
```

**Comment by jbandi** [comment]
Thanks!
Using a static property initializer  as @wlue suggested solved the problem.
I guess this only works with the flag `es7.classProperties` enabled in Babel ...
