### ISSUE TITLE
Better rollback system

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#53]
Currently rollback only works if you've recently taken a snapshot. Perhaps there can be a way to enable automatic rollbacks in case something goes wrong. Ideally this would add minimal code.

**Comment by jareware** [comment]
Neat idea! A concrete use case where this would be cool is an error during dispatch to stores A & B, but say A has been updated but B not, and it errors out. This could make store updates atomic, which would be pretty braggable.
