### ISSUE TITLE
Provide consistent way to specify identifier for Stores & Actions

### ISSUE THREAD

**Issue by jfsiii** [goatslacker/alt#531]
A Store's identifier can be supplied via `alt.createStore(FooStore, 'FooStore')`. However, an Actions identifier must be the specified via a `displayName` property in the definition. 

Ideally, `alt.createActions(FooActions, 'FooActions')` would work (mirroring `alt.createStore`) but, IMO, there should be a symmetrical/complementary API for this.

**Comment by goatslacker** [comment]
There's addStore and addActions which has a symmetrical API. 

Honestly I just set displayName on both stores and actions
