### ISSUE TITLE
Warnings after upgrade to React 0.14

### ISSUE THREAD

**Issue by orkisz** [goatslacker/alt#533]
I get warnings after upgrading React from 0.13.3 to 0.14.2:

``Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.``

``Warning: cloneWithProps(...) is deprecated. Please use React.cloneElement instead.``

First comes from AltContainer,js, second one from mixinContainer.js.

Do you plan to fix those files to be compliant with new React?

**Comment by adduss** [comment]
@goatslacker maybe you should merge commit: https://github.com/goatslacker/alt/commit/0570617ef5a1c8cca444a183c6d0bce91927dabd
to latest release ?

**Comment by goatslacker** [comment]
Use the npm package alt-container for React 0.14 compatible AltContainer
