### ISSUE TITLE
Passing undefined functions to ActionListeners causes silent failure

### ISSUE THREAD

**Issue by maximilianschmitt** [goatslacker/alt#536]
```js
actionListeners. addActionListener(alt.actions.UserActions.LOGIN, somethingUndefined);
```

If `somethingUndefined` is `undefined`, it will cause a silent failure. No error is logged and other listeners for `UserActions.LOGIN` are not triggered.

**Comment by goatslacker** [comment]
What's `addActionListeners`?

**Comment by maximilianschmitt** [comment]
Sorry, I meant [addActionListener](https://github.com/altjs/utils/blob/master/src/ActionListeners.js#L29)

**Comment by goatslacker** [comment]
Ah ok. Please open an issue [here](https://github.com/altjs/utils). Also, I'm :+1: on accepting a pull request that throws an error if you don't pass in a function.
