### ISSUE TITLE
Alt instance usage outside of action, store, and component

### ISSUE THREAD

**Issue by mehcode** [goatslacker/alt#541]
So I'm playing with alt instances and got to a point where I (think) that I need to call an action / check a store and I'm stuck.

```js
function requireAuth(nextState, replaceState) {
  const alt = getAltWithMethodThatExistsSomewhere()
  if (!alt.stores.Session.getState().isAuthenticated) {
    replaceState({next: nextState.location.pathname}, "/login")
  }
}

export default (
  <Route path="/">
    <Route path="login" component={Login} />

    <Route onEnter={requireAuth}>
      <IndexRoute component={Index} />
    </Route>
  </Route>
)
```

Not sure what `getAltWithMethodThatExistsSomewhere` is supposed to be at this point. In case you're not familiar with `onEnter`: It's from react-router 1.x and it gets invoked before trying to actually render. It doesn't get much useful information (there isn't a component instance yet).

----

Cross-posted (from a different perspective) to https://github.com/rackt/react-router/issues/2543

**Comment by goatslacker** [comment]
I create my routes dynamically and pass the alt instance in through there. 

Then my onEnter route looks like this

    <Route flux={alt} onEnter={requireAuth}>

And requireAuth

    function requireAuth() {
      if (this.flux.stores.UserStore.isLoggedIn()) ...
    }
