### ISSUE TITLE
Issue with Immutable datatypes on recycle

### ISSUE THREAD

**Issue by tquetano-r7** [goatslacker/alt#545]
So I've noticed a strange issue where if I have a non-Immutable store, but I use Immutable datatypes in the constructor, when I recycle the store I get the plain JS version of the object.

**Comment by goatslacker** [comment]
Are you using the ImmutableUtil? Immutable Map?

**Comment by tquetano-r7** [comment]
In this case I'm not using ImmutableUtil, but making constructor variables Immutable values. example:

```
class MyStore {
    constructor() {
        this.example = Immutable.Map({
            some:"value"
        });

        this.example2 = Immutable.fromJS([
            "arrays",
            "too"
        ]);
    }
    ...
}
```

And it's my understanding that ImmutableUtil is intended for when you want the entire Store to be one big Immutable object, not necessarily in a case like above. I know it's weird (and I'm now using ImmutableUtil on all new stores I create, that works perfectly),  but I'm trying to avoid rewriting the entire store based on Immutable.

**Comment by goatslacker** [comment]
You'll have to provide your own hooks on how to bootstrap recycle and snapshot that since alt has no way of knowing what to do in that scenario. 

Check out the lifecycle listeners.
