### ISSUE TITLE
Time Traveling

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#55]
Original:

With DispatcherRecorder you can replay certain events in your application. It would be cool if there was a util that would allow you to timetravel through your application but also allow you to specify if you'd only like to time travel certain stores.

Update:

I've got a util that lets you TimeTravel through your entire application's state. It uses alt (very meta) for the time travel bit. You have a set of actions: `revertTo`, `revertStoreTo`, and `destroyAll` which will revert to a specific point in time, revert a specific store to a point in time, or destroy all the stored events.

My only concerns at this point are with memory usage. This should probably use something like immutable or some cursors so we can keep memory usage pretty low.

I need help now fleshing out the rest of the API and most importantly if you've got feature requests then send them in :)

Open questions:

* If people want to be able to select certain values to be cursors then what does that look like? Which library should we use if any?
* What other features should this support?
* Thoughts on what the API should look like?

**Comment by goatslacker** [comment]
Incoming PR for this

**Comment by goatslacker** [comment]
cc @kenwheeler

**Comment by goatslacker** [comment]
cc @gaearon who also might have opinions on this

**Comment by kenwheeler** [comment]
+1 on immutable. Perhaps keep an array of actions and their payload values for replay? I'll think around this for a bit and report back.

**Comment by kenwheeler** [comment]
What arguments would revertStoreTo take?

**Comment by goatslacker** [comment]
`TimeTravelActions.revertStoreTo(name: string, id: string): undefined`

`name` is the store's name you'd like reverted although I could potentially use just the store itself here. `id` is a 7-character unique id that each snapshot will contain, this is used to identify to which state we should revert to.

```js
// if you defined a store like this
var myStore = alt.createStore(MyStore, 'MyStore')

time.getActions('TimeTravelActions').revertStoreTo('MyStore', 'abcd123')

// also possible:
time.getActions('TimeTravelActions').revertStoreTo(myStore, 'abcd123')
```

`TimeTravelActions.revertTo(id: string): undefined`

Reverts the entire application to the `id` provided.

`TimeTravelActions.destroyAll(): undefined`

Removes all snapshots from cache.

**Comment by jareware** [comment]
This is really cool stuff. :) I'm not completely sure I understand why this would require any extra components, though, given how we already can `takeSnapshot()` after every dispatch. Shouldn't "time travel" be as easy as calling `bootstrap` with whatever snapshot you have previously taken?

**Comment by ziflex** [comment]
It's nice feature, but I hope it will be optional and turned off by default. :)

**Comment by goatslacker** [comment]
It's a util so it's separate from core.

**Comment by goatslacker** [comment]
@jareware it's the glue for all of this so you don't have to write it yourself.

**Comment by jdlehman** [comment]
@goatslacker does the snapshot return an object with the snapshot data and the snapshot's id?  curious how one obtains the id so that it can be used later.

**Comment by goatslacker** [comment]
I've got an update coming to simplify this a bit...

**Comment by goatslacker** [comment]
#208 

Been playing around with this API:

```js
@timetravel;
class TodoStore {
  static displayName = 'TodoStore'

  constructor() {
    this.todos = {};
    this.selectedTodo = null;
  }
}

export default alt.createStore(TodoStore);
```

```js
import TodoStore from '../stores/TodoStore';
TodoStore.undo(3); // rollback 3 transactions
```

**Comment by jdlehman** [comment]
I like how simple this is!  I think all it needs is a `redo` function on the store and it should be good to ship.

**Comment by goatslacker** [comment]
Keeping this open so we can talk more about it.
