### ISSUE TITLE
Extending Actions

### ISSUE THREAD

**Issue by og2t** [goatslacker/alt#554]
It seems impossible to extend the Actions, i.e.

```
import alt from '../alt';
export default class ActionsBase {
	loadData(path) {
		...	
	}
}
```

then

```
import alt from '../alt';
import ActionsBase from './actions-base'
class PlanActions extends ActionsBase {
	constructor() {
		super();
		console.log('whoami', this);
	}
}
```

`whoami` yields `ActionGenerator {}` and calling `PlanActions.loadData()` is not possible.

**Comment by goatslacker** [comment]
This PR will fix that behavior https://github.com/goatslacker/alt/pull/503

which will be in the 0.18.0 release
