### ISSUE TITLE
calling `setState` inside Action Handler in a Store blocks dispatching to other Stores

### ISSUE THREAD

**Issue by zapakuj-to** [goatslacker/alt#555]
Hey,

as far as I understand, *Actions* are meant to be dispatched to all *Stores* or to all *Stores* that bind handlers to some *Actions*.

Is this correct? 

If yes, then I think the version `0.17.8` or `0.17.9` of `alt`, this is a bit broken.

If you call `setState` inside one of the handlers to update *Store*'s state, the other Stores won't get the dispatch.

### UserStore
```
class UserStore {
  static displayName = USER_STORE;

  constructor() {
    this.bindListeners({
      handleLoginSuccess: UserActions.loginSuccess
    });

    this.state = {
      user: undefined
    };
  }

  handleLoginSuccess(payload) {
    // this.waitFor(LoginFormStore.dispatchToken);
    this.setState({
      user:      payload,
    });
  }
}
```

### OtherStore
```
class OtherStore {
  static displayName = OTHER_STORE;

  constructor() {
    this.bindListeners({
      handleLoginSuccess: UserActions.loginSuccess
    });

    this.state = {
      somethingElse: undefined
    };
  }

  handleLoginSuccess(payload) {
    // I am never called
  }
}
```

Is anyone else getting this?

Weirdly, if I call `this.waitFor()` inside the `UserStore`, then the `OtherStore` will get the dispatch. However, `UserStore` doesn't depend on any data from `UserStore` and I don't want it to.

**Comment by zapakuj-to** [comment]
Actually.. I have no idea why but it suddenly works. 
I am closing this now, it's very strange.

**Comment by goatslacker** [comment]
Code you posted should work fine.
