### ISSUE TITLE
React Native v0.16 causes Transform error

### ISSUE THREAD

**Issue by adriansprod** [goatslacker/alt#558]
Hi

I have just updated RN to v0.16 and see this error which I assume is due to the Babel updates in RN

TransformError: /Users/…/node_modules/alt/lib/index.js: [BABEL] /Users/…/node_modules/alt/lib/index.js: Unknown option: /Users/…/node_modules/alt/.babelrc.stage

Removing .babelrc seems to fix the problem

**Comment by cnjsstong** [comment]
+1

Same here. Removing `.babelrc` fixed the issue.

**Comment by sebmck** [comment]
`.babelrc` should be added to `.npmignore`.

**Comment by taion** [comment]
Better to use `package.files` instead of `.npmignore` IMO. I noted this at https://github.com/goatslacker/alt/pull/543#issuecomment-156721365.

**Comment by taion** [comment]
Although note we are ignoring `.babelrc`: https://github.com/goatslacker/alt/blob/07d8902be883b0ef59f132435224a24586b4895b/.npmignore#L9

**Comment by myusuf3** [comment]
so whats the work around for this?

**Comment by goatslacker** [comment]
I'll use package.json files and publish a new build.

**Comment by ljharb** [comment]
> .babelrc should be added to .npmignore if you're publishing the package prebuilt.

@sebmck why, if i'm also including the original source in the distribution alongside the compilation output?

**Comment by rainer-liao** [comment]
Remove .babelrc haven't fix the problem

**Comment by athena0304** [comment]
so how to solve this problem?

**Comment by enix223** [comment]
Remove .babelrc did solve this issue.

**Comment by JonathanZWhite** [comment]
Seems like .babelrc in npm packages cause this issue and running `npm run clean` should do the trick

**Comment by ljharb** [comment]
imo this is a babel bug. Each module should be able to declare its own babel version and transformation settings, and include these with the published package.

**Comment by zsading** [comment]
Removing .babelrc works for me

**Comment by ellyliang** [comment]
Removing .babelrc works for me +1

**Comment by yreenchan** [comment]
Removing .babelrc doesn't works for me, what should I do to solve the problem?

**Comment by artokun** [comment]
If the .babelrc problem is persisting even though you create a new project run the following command provided by @JonathanZWhite 

`find ./node_modules -name react-packager -prune -o -name '.babelrc' -print | xargs rm -f`

**Comment by StormFactory** [comment]
I had the same error after creating the default project using ```react-native init [project]``` using react-native v0.42.2.

Opening up the project in Visual Studio Code and renaming .babelrc fixed the problem so ignoring it would still work too.
