### ISSUE TITLE
IE <= 10, static method for connectToStores

### ISSUE THREAD

**Issue by believer** [goatslacker/alt#562]
In IE10 and earlier I get the error `connectToStores() expects the wrapped component to have a static getStores() method`. I figure this is because IE10 does not support static methods.

Is it necessary to re-write all the code using the old standard with store.listen and setting it on the state?

The setup is webpack with babel transform.

**Comment by janmyler** [comment]
I would say something is wrong with your Babel setup. Classes and also their static methods should get transpiled to ES5 compatible code in order to run correctly in all browsers.

**Comment by taion** [comment]
Did they fix the https://github.com/babel/babel.github.io/blob/862b43db93e48762671267034a50c30c00e433e2/docs/advanced/caveats.md#classes-10-and-below caveat for Babel 6 somehow? If not, then static property inheritance across classes is something known to be missing.

**Comment by believer** [comment]
yeah, seems like it's that caveat @taion! will have to rewrite without the static properties I guess.
