### ISSUE TITLE
What happened to alt/utils/connectToStores?

### ISSUE THREAD

**Issue by Ganasist** [goatslacker/alt#566]
I believe I'm doing something stupid. Installed Alt via npm and tried to do this:

```
import connectToStores  from 'alt/utils/connectToStores'
import React  from 'react'
import CustomerActions  from '../actions/customer-actions.js'
import CustomerStore  from '../stores/customer-store.js'

@connectToStores
export default class Greeting extends React.Component {
.....
```

And I'm getting the persistent error: "Cannot resolve module 'alt/utils/connectToStores'"

That file / location doesn't exist in my installed node_modules folder, and I also can't find it anywhere in this repo. What am I doing wrong here?

**Comment by jdlehman** [comment]
[`connectToStores`](https://github.com/altjs/connect-to-stores) is now a separate repo

**Comment by nbwar** [comment]
How do we add it back to our project. Doesn't seem to be an module for it.

**Comment by sloria** [comment]
`connect-to-stores` has not yet been released to npm. Will `connect-to-stores` be maintained, or is `AltContainer` preferred?

**Comment by taion** [comment]
It seems like the published version is actually on alt-utils? Is that correct/intentional? It doesn't match what's documented in the README on this repo.

**Comment by sloria** [comment]
Yeah, looks like alt-utils has `connectToStores`, but I also see that `alt-react` has a `connect` function which does something similar. Which is preferred?

**Comment by goatslacker** [comment]
https://github.com/altjs/react and `npm install alt-react`

**Comment by goatslacker** [comment]
The old connectToStores is available in `alt-utils` npm package. `alt-react` has the new stuff.

**Comment by sloria** [comment]
It would be great to have this documented somewhere, though I'm not sure of the best place. Looks like the "Container Components" section of the docs could use an update? Let me know if I can help in any way.

**Comment by goatslacker** [comment]
Container Components looks nice. I'd like to restructure the README with an updated good example.

**Comment by sloria** [comment]
Also, perhaps the https://github.com/altjs/connect-to-stores should clearly marked as abandoned in favor of alt-react.
