### ISSUE TITLE
DOCS: Constant UPDATE_LOCATIONS not defined in previous actions section

### ISSUE THREAD

**Issue by thinkloop** [goatslacker/alt#568]
In the store docs: http://alt.js.org/guide/store/

There is `handleUpdateLocations: LocationActions.UPDATE_LOCATIONS`

However in the previous actions sections: http://alt.js.org/guide/actions/

There is no mention of the constant UPDATE_LOCATIONS.

**Comment by yujingz** [comment]
@thinkloop 
`updateLocations` was defined in the `LocationActions` and it automatically gets you the [action symbol](http://alt.js.org/docs/actions/#actionconstant) `UPDATE_LOCATIONS`. This is because behind the scenes flux uses these constants to dispatch events.

**Comment by thinkloop** [comment]
Thanks for the reply. So does it use the camel case to decide where to put
the underscore?

**Comment by yujingz** [comment]
yeah that's the convention

**Comment by thinkloop** [comment]
Thank you. I am replying by email but will close the issue when I get back
to my desk. Please feel free to close meanwhile.

Best,
Baz
