### ISSUE TITLE
circular dependency between action and webapi

### ISSUE THREAD

**Issue by jongbeau** [goatslacker/alt#57]
I was looking at the chat example and the pattern of an action calling the webapi which then calls another action after receiving the response from the API. If the web API wants to call an action from the same class as the original action, it results in a circular dependency with the require modules:

ActionClass -> requires WebAPI -> requires ActionClass

Any thoughts on how to structure this better?

**Comment by goatslacker** [comment]
If you're using commonjs you can use `exports` to get around this:

`alt.createActions(ActionClass, exports)`

**Comment by troutowicz** [comment]
Another option is to use a callback.

```javascript
class Actions {
  constructor() {
    this.generateActions('actionOne');
  }

  actionTwo() {
    WebAPIUtils.someAsyncOp((err, data) => {
      this.actions.actionOne(data);
    });
  }
}
```

**Comment by jongbeau** [comment]
@goatslacker - thanks, that worked! Can you explain what happens behind the scenes when using alt.createActions(ActionClass, exports) ?

@troutowicz , that was the approach I was going to take as last resort, but I like goatslacker's solution better.

**Comment by goatslacker** [comment]
The docs mention what that 2nd parameter is for: https://github.com/goatslacker/alt/blob/master/docs/createActions.md#createactions

Essentially it'll just add each action to exports. You can pass any object into createActions as its second parameter and it'll add all the actions to that object.

action.foo becomes exports.foo

Does that answer it or were you looking for a why does this work in commonjs when you use exports but not module.exports?

**Comment by jongbeau** [comment]
I'm more curious as to why it works, but doesn't when I use module.exports.

**Comment by jdlehman** [comment]
@jongbeau Here is a relatively short [article](https://coderwall.com/p/myzvmg/circular-dependencies-in-node-js) that should help explain what is happening under the covers.

Note that not all module systems do a great job at handling circular dependencies.  I typically use [webpack](http://webpack.github.io/) as it handles circular dependencies well and just like Node (in the way described in the article above).

**Comment by goatslacker** [comment]
Oh interesting didn't know that tidbit.

It works because the values get assigned to `exports` later on so they'll be available at run-time when you need them.
