### ISSUE TITLE
Warning when returning undefined from an action

### ISSUE THREAD

**Issue by euge** [goatslacker/alt#575]
Hello, just wanted to clarify something. Is returning undefined from an action considered an ok pattern? I saw in the docs "Returning undefined (or omitting return altogether) will not dispatch the action" but noticed that when this happens a console warning is generated "ReferenceError: An action was called but nothing was dispatched(…). " Thanks!

**Comment by goatslacker** [comment]
It's ok it's just that nothing gets dispatched...so if you're intention is to call a function that does nothing then ok, otherwise return something.

**Comment by euge** [comment]
Cool thanks. My use case was when calling something like `LocationActions.fetchLocations` and if there is a current request in progress, to just ignore the action.

**Comment by brewsoftware** [comment]
If it's valid not to dispatch something from an action. Can we please at least have a way of turning off the warnings? Throwing junk warnings like this messes up the error console... It's either valid or not.

**Comment by StefanSchwartze** [comment]
+1 I'm also confused by this message because it's still an Error and an Error indicates that something is not okay with the application.
