### ISSUE TITLE
this.dispatch is not a function

### ISSUE THREAD

**Issue by mkotar** [goatslacker/alt#576]
I am not able to dispatch anything in my actions

Uncaught (in promise) TypeError: this.dispatch is not a function(…)

example: 
        setData(data) {
            this.dispatch(data);
        }

also i am not able to call any action from another action by using this.actions.someAction

and when action doesn't dispatch anything i get this:
ReferenceError: An action was called but nothing was dispatched(…)

**Comment by goatslacker** [comment]
https://github.com/goatslacker/alt/blob/master/CHANGELOG.md#breaking-changes

There's an upgrade guide there too.

**Comment by mkotar** [comment]
Thanks!
 - I don't know how I missed this article. Lot of work ahead.
