### ISSUE TITLE
alt/utils/connectToStores and alt/utils/decorators could not be resolved

### ISSUE THREAD

**Issue by abilashs90** [goatslacker/alt#578]
Hi, I was setting up a react flux project and I have the following error.

```
Module not found: Error: Cannot resolve module 'alt/utils/connectToStores' 
Module not found: Error: Cannot resolve module 'alt/utils/decorators'
```
My package.json contains the following

```
 "dependencies": {
    "alt": "^0.18.1",
    "babel-runtime": "^6.3.19",
    "history": "1.13.x",
    "normalize.css": "^3.0.3",
    "react": "^0.14.3",
    "react-dom": "^0.14.3",
    "react-router": "1.0.2"
},
"devDependencies": {
    "babel-core": "^6.3.21",
    "babel-loader": "^6.2.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.3.16",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "css-loader": "~0.16.0",
    "cssnext": "~1.8.4",
    "extract-text-webpack-plugin": "^0.9.1",
    "html-webpack-plugin": "^1.7.0",
    "postcss-loader": "^0.5.0",
    "postcss-mixins": "^0.3.0",
    "postcss-nested": "^0.3.2",
    "postcss-simple-vars": "^0.3.0",
    "style-loader": "^0.13.0",
    "webpack": "^1.12.9",
    "webpack-dev-server": "^1.14.0"
}
```
And my usage is as follows

```
import createActions from 'alt/utils/decorators';

@createActions(flux)
class DummyAction {
	constructor() {
		//My Non Sense
	}
}
export default DummyAction;
```

**Comment by jdlehman** [comment]
alt utils have moved out of this repo and into their [own](https://github.com/altjs/utils)

**Comment by jbaumbach** [comment]
Now that "npm install alt --save" doesn't get everything required to use Alt, what is the recommended way to get these additional files?

**Comment by Andyccs** [comment]
@jbaumbach for now I guess the only way to solve it is:

```Shell
npm install alt-utils
```

@goatslacker We probably need to update the main [README.md](https://github.com/goatslacker/alt/blob/master/README.md) and explicitly spell out the way to install alt-utils to avoid confusion?

**Comment by crowdbytes** [comment]
@Andyccs +1
I also came across to this problem once I decided to use decorators instead of the class methods for more aesthetic code. Would be really awesome to point this part out in your ReadMe documentation as I evaluate it from my perspective.

Either way, you do a really great work, I'm glad using it.
