### ISSUE TITLE
Store class inheritance

### ISSUE THREAD

**Issue by quangbuule** [goatslacker/alt#58]
The Store class inheritance doesn't work:

```js
class BaseStore {
  static doSomethingOnBase() {
    console.log('doSomethingOnBase()');
    this.emitChange();
  }
};

class Store extends BaseStore {
  static doSomething() {
    console.log('doSomething()');
    this.emitChange();
  }
}

var storeInstance = alt.createStore(Store);

storeInstance.listen(() => {
  console.log('Triggered.');
});

console.log(BaseStore.doSomethingOnBase);

storeInstance.doSomething();
storeInstance.doSomethingOnBase();
```

`BaseStore.doSomethingOnBase` still exists but `storeInstance.doSomethingOnBase` is undefined.

**Comment by jdlehman** [comment]
This does not work because of `Object.getOwnPropertyNames(obj)` works, which is being used [here](https://github.com/goatslacker/alt/blob/master/src/alt.js#L40).

See this [example](https://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=class%20Parent%20%7B%0A%20%20parentMethod()%20%7B%7D%0A%20%20static%20parentStaticMethod()%20%7B%7D%0A%7D%0A%0Aclass%20Child%20extends%20Parent%20%7B%0A%20%20childMethod()%20%7B%7D%0A%20%20static%20childStaticMethod()%20%7B%7D%0A%7D%0A%0A%2F%2F%20parent%0Aconsole.log(Object.getOwnPropertyNames(Parent))%3B%0A%2F%2F%20child%0Aconsole.log(Object.getOwnPropertyNames(Child))%3B) of what happens in Babel's repl.

I am also curious if extending a store is a common use case.  I cannot think of an example where this would be done in an application (that doesn't mean there isn't a use case, I just can't think of one off the top of my head).

**Comment by troutowicz** [comment]
If there ends up being a use case for extending a store, this change should make that possible.

```javascript
let storeProto = {};
if (Object.getPrototypeOf(StoreModel) !== Object.getPrototypeOf(NoopClass)) {
  storeProto = getInternalMethods(Object.getPrototypeOf(StoreModel), builtIns));
}

storeInstance = assign(new AltStore(this.dispatcher, store), getInternalMethods(StoreModel, builtIns), storeProto);
```

**Comment by quangbuule** [comment]
Inheritance is the beautiful thing come to ES6 :)

**Comment by jdlehman** [comment]
Looks good @troutowicz. I think there are a few more issues we need to handle.

1. A store could have any number of ancestors. So `getInternalMethods` should be recursive or have some iteration to ensure that we collect all of the ancestors' internal methods.
2. The way you are using `assign` right now means that `storeProto`, the parent, will override all properties with the same name of the child. So we would also need to make sure that we end up with something like `assign(altStore, ...,  grandparent, parent, child);`, which will ensure that the child methods have precedence over its ancestors. (we can't go breaking the prototype chain now can we :wink:)

Though I do still want to make sure there is some sort of use case, and hear @goatslacker's thoughts.

**Comment by goatslacker** [comment]
Yeah I guess this should work. Although it's maybe best not to rely on this behavior since babel does come with certain [caveats](http://babeljs.io/docs/usage/caveats/)

**Comment by troutowicz** [comment]
@goatslacker I think that is more of a IE <= 10 caveat, babel does what it can.

I'll clean up my code including @jdlehman's suggestions, and submit a PR.

**Comment by troutowicz** [comment]
@quangbuule 
Can you provide any more info on why you want to extend a store?

**Comment by quangbuule** [comment]
Example, we have collection stores having same interface.

```js
class CollectionStore {

  static getItem(id) {
    // return an items
  }

}
```

With a large app, we would like to extends the `BaseClass` just like above.

**Comment by goatslacker** [comment]
Seems reasonable. I was discussing a few ideas in the gitter channel maybe those will be preferable.

How about if there is an explicit method to make these functions available, you can put it in the constructor.

```js
class CollectionStore {

  constructor() {
    this.exportPublicMethods(this.getItem)
  }

  getItem(id) {
    // return an items
  }

}
```

**Comment by jdlehman** [comment]
I am still not sure if inheritance makes a lot of sense for stores.  Based on Facebook's docs on [stores](http://facebook.github.io/flux/docs/overview.html#stores), we should not think of a store as a model like we are familiar with in traditional MVC architectures.  Instead, a store represents data within a particular domain.  It might make sense to use inheritance in models that might be contained within a store (I actually do this in an app I am currently working on), but I do not really see inheritance being needed to architect stores as they are not a single model, but a collection of related models/data for a domain in an app.

In general it seems that FB tends to support a more functional approach as it lends itself better to this style of reactive functional programing.  See this [discussion](https://github.com/facebook/react/issues/613) on using ES6 classes to create React components as it contains a lot of relevant thoughts on the topic at hand.

All of that aside, I think the biggest factor in my decision is that if a store is inheriting methods from another store, more than likely it is in the SAME domain as its parent and the two stores should really just be one.  Inheritance in stores feels like a Flux anti-pattern.

**Comment by goatslacker** [comment]
It's currently supported so I don't want to un-support it, plus I want to allow the flexibility regardless of my opinion about inheritance vs composition. That being said, I think the larger issue here is that `static` makes methods public. This is magic, and not very good magic.

**Comment by troutowicz** [comment]
@goatslacker and I were discussing the magic involved with making ```static``` methods ```public``` in glitter earlier this evening. I am writing up the code for a mixin dubbed ```exportPublicMethods``` that will provide a more clear cut way of defining methods meant to be public in a store.

**Comment by jdlehman** [comment]
I will agree that the magic of `static`s being made public confused me a bit when I first started using alt.  It seems strange that an alt instance of a store can call methods you defined as `static`.

I do want to :+1: the following syntax in that case: `this.exportPublicMethods(this.getItem)`.  I did not realize it was being discussed as an alternative to defining public methods.  I think it does 2 things.  It cleans up the magic, and is flexible enough to support our current use case as well as the use case @quangbuule desires.

**Comment by jdlehman** [comment]
@troutowicz thanks for being awesome, you are knocking these ideas out in rapid fire!  I better keep a gitter window open so I don't miss out on the fun. :smile:

**Comment by troutowicz** [comment]
:+1:  gitter is where the magic happens, or doesn't happen in this instance ;)

**Comment by mshick** [comment]
I'm curious -- will the ExportPublicMethods mixin preserve the current functionality, where public methods are available only on the instance, and do not appear when calling `getState()`? As a matter of hygiene I like the current approach.

As for a use case: I currently extend certain stores from a base ListStore class. It allows me to wrap up some repetitive id / object storage / pagination bits. It's all functionality that could probably be included via a mixin just as well, but class extends struck me as a cleaner, more visible, more ES6 way to go about it.

**Comment by troutowicz** [comment]
Yes, current functionality is preserved. `getState()` is for state, not methods. It will also work with your use case.

**Comment by mshick** [comment]
I was just testing out the new mixin, and there's one aspect of inheritance it doesn't seem to address -- I still cannot seem to define a class method in my super class and have it available privately for the store. 

i.e., this works

```js
class Store {
  privateMethod() {}
  onAction() { this.privateMethod(); }
}
```

while this does not.

```
class Super {
  privateMethod() {}
}
class Store extends Super {
  onAction() { this.privateMethod(); }
}
```

I realize I can make the method public, and then access it via `this.getInstance().privateMethod()` but that is undesirable for a number of reasons.

Further, if I did make this method public via `exportPublicMethod()` ideally it would remain available privately as well.

My use case here: I have a `getList(key)` method which grabs a list from many lists via some index. This is used internally, to find a list and store to it, and externally, to retrieve the list in a component.

Currently I hack this by setting the method directly in my super class constructor, but that pollutes my state. `exportPublicMethod()` gets me one step closer, but not being able to inherit the method privately is a problem.

**Comment by goatslacker** [comment]
Did you call super in the constructor?

**Comment by mshick** [comment]
I do, yeah

**Comment by jdlehman** [comment]
This works for me:

```js
class ParentStore {
  constructor() {
  }

  privateMethod() {
    console.log('here');
  }
}

export class ChildStore extends ParentStore {
  constructor() {
    super();
    this.bindActions(myActions);
  }

  onSomeAction(data) {
    this.privateMethod(); //=> logs "here" in console
  }
}

export default alt.createStore(ChildStore, 'ChildStore');
```

This works based on how ES6 classes work. alt does not need to do anything special.  Let me know if I misunderstood what you are trying to do.

**Comment by mshick** [comment]
I would expect that to work as well, and that’s the desired set up, but wasn’t seeing it. Let me explore in something more isolated — perhaps I missed something.

**Comment by maksad** [comment]
@jdlehman :+1:

**Comment by dspoonia7** [comment]
Hey @jdlehman, I was doing code optimisation and I found some old code similar to the code like you have mentioned [in above comment](https://github.com/goatslacker/alt/issues/58#issuecomment-82436559).

```
// ParentStore.js
export default class ParentStore extends ReduceStore {
  constructor(dispatcher) {
    super(dispatcher)
  }
  privateMethod() {
    console.log('here');
  }
  reduce (state, action) {
    const { type,  data } = action
    switch (type) {
      case 'TYPE_1':
        return updatedState1;
      default':
        return state;
     }
  }
}

// ChildStore1.js
class ChildStore1 extends ParentStore {
  onSomeAction(data) {
    this.privateMethod(); //=> logs "here" in console
  }
}
export default new ChildStore1(dispatcher)

// ChildStore2.js
class ChildStore2 extends ParentStore {
  onSomeOtherAction(data) {
    this.privateMethod(); //=> logs "here" in console
  }
}
export default new ChildStore2(dispatcher)
```
Above ParentStore is getting bind with the dispatcher twice, once by each child store. Now when an action triggers, ParentStore's reducer invokes twice. 
How can I remove the redundant binding and bind the ParentStore only once? Great if you can help here. Thanks!
