### ISSUE TITLE
connectToStore decorator not workin in 0.18.1

### ISSUE THREAD

**Issue by kandaraj** [goatslacker/alt#581]
```import connectToStores from 'alt/utils/connectToStores'; ``` works in version 0.17.9 but when I upgraded to 0.18.1, it seems to have broken my build. 

Error:

```Module not found: Error: Cannot resolve module 'alt/utils/connectToStores' in /```

**Comment by sloria** [comment]
`connectToStores` has been moved to a separate `alt-utils` package. `alt-react` has a newer `connect` function.

Ref: https://github.com/goatslacker/alt/issues/566

**Comment by taion** [comment]
^
