### ISSUE TITLE
createActions broken after uglify

### ISSUE THREAD

**Issue by shlomokraus** [goatslacker/alt#585]
Given the following example: 

class MyActions {... }
export default alt.createActions(MyActions);

Actions will be added under alt.actions.MyActions, allowing me to access them via the alt instance 
anywhere in the code.
But after running Uglify, MyActions losses its name and is assigned under a different var, ie - alt.actions.aksks.

Is there a way to assign a constant name when using createActions instead of alt using reflections for the assignment? 

btw, I know I can use addActions, but then I don't get the actions object and hence I can not export it for direct use. 

Thanks

**Comment by goatslacker** [comment]
```js
class MyActions {
  static displayName = 'MyActions'
}
```
