### ISSUE TITLE
Losing component's methods when exporting with connectToStores

### ISSUE THREAD

**Issue by WoLfulus** [goatslacker/alt#589]
I'm using Alt.js's connectToStores to access store state inside a component, but when I try to call this component's method from aother component (using a ref), the method seems to be lost because of a wrapper component (gives undefined method).

**comp_a.js**

    class CompA extends React.Component {

        ...

        static getStores() { ... }
        static getPropsFromStores() { ... }

        ...

        method() { 
        }

        ...
    }

    export default connectToStores(CompA);

**comp_b.js**

    class CompB extends React.Component {

        ...

        test() {
            // Causes error because "method()" is lost during connectToStores export
            // It seems that connectToStores doesn't inherit the base component, instead it wraps the component with another component.
            this.refs.other.method(); 
        }

        ...

        render() { 
            return (
                <CompA ref="other" />
            );
        }

        ...

    }

 1. Is there any way to still call **method()** ?

 2. Is there any way to access the wrapped component?

**Comment by jdlehman** [comment]
You are correct that `connectToStores` just wraps the component. All `connectToStores` does is pass its state (that it gets from the store) to the wrapped component as props.

To answer your question, I don't think it is a good React practice to dig into the refs to call methods on other components. Instead you should have `CompB` pass a function as a prop to `CompA`.

Something like the following:

**comp_a.js**

    class CompA extends React.Component {

        ...

        static getStores() { ... }
        static getPropsFromStores() { ... }

        ...

        method() { 
          this.props.yourMethod();
        }

        ...
    }

    export default connectToStores(CompA);

**comp_b.js**

    class CompB extends React.Component {

        ...

        method() {
           // method logic (maybe just calling a Flux action)
        }

        ...

        render() { 
            return (
                <CompA ref="other" yourMethod={this.method} />
            );
        }

        ...

    }
