### ISSUE TITLE
Unable to import 'alt' using webpack (succesful with 'alt/lib)

### ISSUE THREAD

**Issue by DisruptiveMind** [goatslacker/alt#593]
When importing Alt (0.18.1) using just the module name:

```javascript
import Alt from 'alt';
```

webpack spits out
```javascript
_alt2.default not a function
```

I managed to make it work by using the 'alt/lib' path instead:

```javascript
import Alt from 'alt/lib';
```

Then everything works as expected. I must be missing something....

**Comment by DisruptiveMind** [comment]
It was a bad resolve setting in webpack, but I'm still unable to resolve `alt/utils/connectToStore`.

**Comment by DisruptiveMind** [comment]
using 'alt-utils/lib

**Comment by jdlehman** [comment]
`connectToStore` has moved to another repo: https://github.com/altjs/utils

**Comment by DisruptiveMind** [comment]
@jdlehman thanks!

**Comment by lekishvili** [comment]
@DisruptiveMind I have same problem, when I'm removing resolve.root works fine, how did you fix?

**Comment by DisruptiveMind** [comment]
@lekishvili I had to use the updated package as @jdlehman mentioned above
