### ISSUE TITLE
Calling actions with isomorphic flux instances

### ISSUE THREAD

**Issue by voronianski** [goatslacker/alt#62]
Hey, it would be nice to hear your point of view on the following.

I am using `Alt` inside isomorphic app which uses alt's flux instances feature. Currently my actions that deal with API look like:

```javascript
import { getStats } from '../../../webAPIUtils';

export default class MatchDetailActions {
    constructor() {
        this.generateActions('receiveStats', 'failReceiveStats');
    }

    requestStats(requestOptions) {
        this.dispatch(requestOptions);

        // method just calls superagent with necessary url
        getStats(requestOptions, function (err, stats) {
            if (err) {
               this.actions.failReceiveStats(err);
               return;
            }
            this.actions.receiveStats(stats); // calling actions inside action (bad?)
        }.bind(this));
    }
}
```

As you see I'm calling success/error actions inside the initial request action which is considered an anti-pattern. But this allows me to call such actions on the server side without worrying how to pass the flux instance created by request inside web api utils.

What is your approach in similar situation?

**Comment by goatslacker** [comment]
That's fine to do, you'd be doing the same thing essentially if it was a util.

Are you only limiting yourself to calling one action server-side?

**Comment by voronianski** [comment]
@goatslacker I'm calling several actions server-side but actually all of them are sync for now.I have an API endpoint that returns needed data per request and then I create `new Flux` instance and just call necessary "receiveActions".

Also the reason of the question was having one general action for failed requests. Is this possible to get other actions inside action without including them as singletons?

**Comment by goatslacker** [comment]
How do you know when all actions have finished so you can render the component? Are you using something like the [final store](https://github.com/goatslacker/alt/blob/master/utils/makeFinalStore.js)?

I like the idea of having a util/addon that facilitates the whole success/fail pattern for actions.

I'm not sure I understand your last question though.

**Comment by voronianski** [comment]
@goatslacker regarding the rendering, per request it looks as follows:

```javascript
apiUtils.getAllConfigs(function (err, mlConfigs) {
    if (err) {
        return next(err);
    }

    var flux = new Flux();

    flux.getActions('myclub').getMyClubFromRequest(req);
    flux.getActions('articles').receiveFeeds(mlConfigs.feeds);
    flux.getActions('matches').receiveLeagues(mlConfigs.leagues);

    var snapshot = flux.takeSnapshot(); // bootstrapping it on client

    Router.run(routes, req.url, function (Handler) {
        var content = React.renderToString(React.createElement(Handler, {flux: flux}));
        res.render('base', {
            content: content,
            snapshot: snapshot
        });
    });
});
```

Regarding my second question I mean:

```javascript
getStats(requestOptions, function (err, stats) {
   if (err) {
        this.flux.getActions('errorActions').failRequest(err); // "get another action inside action"
        return;
   }
   this.actions.receiveStats(stats);
}.bind(this));
```

**Comment by goatslacker** [comment]
It's available on `this.alt`

```js
const Alt = require('alt')

class Actions {
  fire() {
    this.alt.getActions('actions').fireFail
  }

  fireFail() { }
}

class Flux extends Alt {
  constructor() {
    super()
    this.addActions('actions', Actions)
  }
}


const flux = new Flux()

flux.getActions('actions').fire()
```

**Comment by voronianski** [comment]
@goatslacker thanks!

**Comment by goatslacker** [comment]
Any time!
