### ISSUE TITLE
listeners are fired when I write to this.state in Store

### ISSUE THREAD

**Issue by continuata** [goatslacker/alt#620]
I'm wanting to silently set state on the store without triggering listeners.

An example of my Store
```js
import alt from './alt'
import AppActions from './AppActions'

class AppStore {
  constructor () {
    this.bindActions(AppActions)
    this.state = {
      forms: {}
    }
  }
  
  initForms (data) {
    this.state.forms = data
  }
}
export default alt.createStore(AppStore, 'AppStore')
```

My Component
```js
import React from 'react'

import AppStore from '../AppStore'
import AppActions from '../AppActions'

let { Component } = React

export default class Input extends Component {
  componentDidMount () {
    AppStore.listen(data => {
       console.log('forms changed', data.forms)
    })
    AppActions.initForms({foo: "bar", bar: "foo"})
  }
  
  render () {
    return <div>Hello</div>
  }
}
```

Why is my listener being triggered when I use `this.state` on the Store, I thought you needed to use `this.setState()` to trigger the listeners

**Comment by jdlehman** [comment]
If you return false from your store methods like `initForms`, it will not trigger the listeners. It's [here](https://github.com/goatslacker/alt/blob/master/docs/createStore.md#storemodelpreventdefault) in the docs.

**Comment by continuata** [comment]
thanks so much, completely missed that
