### ISSUE TITLE
Isomorphic application with authentication!

### ISSUE THREAD

**Issue by LestaD** [goatslacker/alt#624]
I use `react-router`.
I want make server-side rendering on React with Alt.
I want load all data before rendering on server.
Ex.: authenticate by [JWT](http://jwt.io)
How can i do that?

**Comment by goatslacker** [comment]
Authenticate using JWT. Use alt.bootstrap to load all the data into your stores. Render your components.

**Comment by goatslacker** [comment]
http://alt.js.org/docs/bootstrap/

**Comment by LestaD** [comment]
@goatslacker what if i have so many data in db?!

**Comment by LestaD** [comment]
for example:

in react router i have search page

```jsx
<Route path="/search/:query" component={SearchComponent} />
```

I want return rendered component with founded data.

Another example: get friend list

**Comment by LestaD** [comment]
I don't want to write crutches, ex: make api in express special for react server side render.

**Comment by goatslacker** [comment]
I'm not sure what your application stack looks like. If you want to share API calls between server and client then you'll need to create and pass around instances of flux per request so you don't have data collisions. If you already have all the data then you can safely bootstrap/flush it on each request.
