### ISSUE TITLE
promise resolved from remote action sends correct payload to store, but not to other functions attached to the promise

### ISSUE THREAD

**Issue by kellyrmilligan** [goatslacker/alt#631]
is it possible to get the payload back from a source with a remote call with a .then() attached to the call as well as it sending the right payload to the store?  would be nice sometimes to just get it back and do something right there instead of looking up in the store.

**Comment by jacobangel** [comment]
Probably not, as this violates the principles of Flux architecture.

**Comment by kellyrmilligan** [comment]
I should have closed this sorry. It was already merged into a recent pr.  I agree with you in principle, however for control flow scenarios it's more practical to check something right there then get it from he store
