### ISSUE TITLE
mixins/ListenerMixin not found 

### ISSUE THREAD

**Issue by johnlim5847** [goatslacker/alt#646]
Hi guys, I'm having some trouble to find the **ListenerMixin.js** in the source.Due to I'm very new to react-native and I just got the project from the previous author may  I know which part of the code I have to modify to get it running ? 
![screen shot 2016-04-28 at 12 35 06 pm](https://cloud.githubusercontent.com/assets/3675946/14875547/5eee9832-0d3e-11e6-93d4-530e34f4acd6.png)
The current code refers to`'alt/mixins/ListenerMixin'` where there is no **alt** directory inside my **Components** directory, I'm assuming the previous author trying to refer to `ListenerMixin.js` for some reasons he did it that way instead to refer to **node_mudule alt** but I also cannot find the `ListenerMixin.js` in the **node_mudle alt** though. Did you guys rename the file name or deprecated the file ? It would be helpful if someone can enlighten me! thank you :)

**Comment by Sparragus** [comment]
Mixins are a thing of the past. They are gone on v0.18.x. What you are looking for is on the [v0.17.x branch](https://github.com/goatslacker/alt/blob/v0.17.9/mixins/ListenerMixin.js)
