### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by allenylzhou** [goatslacker/alt#670]
Is there a style guide on how to name/structure your files and variables when using Alt as the flux framework?

**Comment by goatslacker** [comment]
Not that I'm aware of. The [Airbnb Style Guide](https://github.com/airbnb/javascript) has some general rules though that could apply.

You can check out the [React](https://github.com/airbnb/javascript/tree/master/react) guide and the [Naming Conventions](https://github.com/airbnb/javascript#naming-conventions) section.
