### ISSUE TITLE
alt seems to be a moving target.  any help nailing it down?

### ISSUE THREAD

**Issue by sjatkins** [goatslacker/alt#673]
This project seems to be really a moving target.  Every time I thing I have it nailed what it where I see a different way that now seems to be preferred.  It is quite disconcerting.  Is it possible to please decide what the API really is including what modules have what and freeze it?   Examples on the net are seriously lagging some of these changes.  Is there a canonical reasonably full set of all things alt-ish that is kept up-to-date?   I would love to find such.   Does it exist and I have just missed it?

**Comment by goatslacker** [comment]
It hasn't really changed in a while...but I have some bad news. It'll change again :( this time for good though.

If you're interested in what that looks like you can check it out (and give feedback) here: https://github.com/goatslacker/alt/pull/669

For the "canonical" "reasonable" full set of all things alt that's kept up to date you can check either the README or the website.

**Comment by sjatkins** [comment]
I did check these things and they were not adequate.  So thanks very much.

**Comment by goatslacker** [comment]
What do you mean by adequate? Is there something you're expecting that isn't there?

**Comment by sjatkins** [comment]
Hi,
Where I am getting a bit lost in in alt/utils vs from the alt-utils project.  And in using decorators vs exporting the function approach for things like createActions, createStore and connectToStores.  Using the decorator approaches throughout I see a funny issue where my Component decorated with connectToStores doesn't seem to ever update from my action firing.  I tracked the actions being fired through the actions and to the stores.  But returning truthy value from the store doesn't seem to be firing an update.  I am attempting to put together a smaller example than my main code to publish on the problem.

As far as I can tell reading source the connectToStores sets up a wrapping component that includes setting up the listeners and responding with I imagine refiring the getPropsFromStores.  Yet putting a breakpoint here never fires when I know the store has changed. 

Deciphering over google plus the relevant githubs is a bit daunting wher I am translating over decorators vs not and ES6 vs not and some concepts that while interesting I am not sure are directly applicable at all. 

I started pretty much with using the patterns in git@github.com:richard-lopes/webpack-example.git upgrading it to the latest babel6.

**Comment by goatslacker** [comment]
@sjatkins fwiw I'm expecting to also revamp to whole confusing alt ecosystem of tooling. The APIs are all fine they just need documentation and consistency :)

A failing set of code would be great to debug this issue. If the store is not firing a change event then something else is happening (perhaps the store is not receiving the dispatch in the first place)

**Comment by sjatkins** [comment]
I put in breakpoints that persuaded me the store does receive the dispatch.  More when I get back to debugging it.

**Comment by goatslacker** [comment]
If the store is receiving the dispatch you can check it by doing `store.listen(state => console.log(state))`
