### ISSUE TITLE
Add "magic" of alt section to readme

### ISSUE THREAD

**Issue by troutowicz** [goatslacker/alt#69]
Alt by design implicitly makes class methods immutable/private to everything but actions. This keeps the flow unidirectional. However, alt provides an exception to this functionality by using `static` methods. When a method is declared `static`, alt magically adds the method to the object returned from `alt.createStore()`, giving `public` access to the method. This behavior is strange, confusing, and twists the expected behavior of the `static` method type. `static` methods are meant to be properties of an object, not the properties of an object's instance. 

A better solution is to use a mixin that provides the ability to explicity state which methods of a class should be made public in the resultant altStore instance. See PR #66.

I propose this `static` method support be dropped from alt and replaced by something akin to what is described above.

**Comment by mattmccray** [comment]
I understand why you say that. But "dropping static method" support seems like the nuclear option here. Semantically you may not like it, but it does provide a good demarcation for what's publicly accessible.

**Comment by goatslacker** [comment]
We aren't dropping static. We can just support both.

**Comment by troutowicz** [comment]
I understand that for alt's logic, `static` provides a way (I wouldn't say good) to distinguish what can be made public and what should be kept private, but the expected behavior of `static` methods shouldn't be warped simply because it works. Especially when their are other ways to do it better.

Yes it would be a breaking change, I wouldn't expect this to really be considered until a major release.

**Comment by goatslacker** [comment]
Probably way in the future. But the static methods should stay for now.

**Comment by jdlehman** [comment]
I agree with @troutowicz's sentiments, it is definitely an unexpected behavior for `static` methods when you first start working with alt.  I think the documentation was very clear on alt's API, but the magic can confuse people a bit, especially if they are new to ES6.

I think a good short term "fix", is to add a note in the store docs that clarifies that this behavior is different than how `static`s are typically used in ES6.

**Comment by goatslacker** [comment]
PR #66 creates an explicit path for this. We won't be killing static but I will add a section about the magic in alt to the README.

**Comment by goatslacker** [comment]
A lot of the magic has been documented pretty well in the README lately plus it has been replaced by more explicit methods.
