### ISSUE TITLE
Recursive nested stores. Why?

### ISSUE THREAD

**Issue by hyanmandian** [goatslacker/alt#690]
It was supposed to be this way?

![Example](http://i.imgur.com/30OXO4w.jpg)

**Comment by goatslacker** [comment]
Yes it was. Because each store has a reference to alt and alt has a reference to the store.

Are you trying to JSON.stringify alt or something?

**Comment by hyanmandian** [comment]
i was trying to simplify use of the cancellation feature in my current project, adding a method on alt instance, but doesn't work :(

Thanks for reply!

**Comment by hyanmandian** [comment]
I was trying to debug an error.

Thanks for reply :)
