### ISSUE TITLE
Add hook/event after action was dispatched.

### ISSUE THREAD

**Issue by irium** [goatslacker/alt#7]
I think snapshotting functionality isn't that usable on the client, because snapshots usually should be done at **predefined** moments in app lifecycle. In Flux this is usually **after** some action(s) **completed**. But I wasn't able to find proper hook in the `Alt`. It could be better if we could use it like:
```javascript
alt.actionDispatched = (action) => {
...
}
```
Or something like this.
`actionDispatched` should be called after `Dispatcher.dispatch(...)` method completes.

**Comment by goatslacker** [comment]
This is a good point. One pattern that I've adopted is to have a store that waits for every store, I then register a listener on that store and do snapshots there.

```js
class SnapshotStore {
  constructor() {
    this.bindActions(whateverActions)
  }

  onAction() {
    this.waitFor(['Store1', 'Store2', 'Store3', 'Store4'])
  }
}

var snapshotStore = alt.createStore(SnapshotStore)

snapshotStore.listen(() => alt.takeSnapshot())
```

Funny you mention this, I have some code sitting in a local branch that does something like this. Here's the proposed change which would register a listener on the alt instance for those actions called:

```js
alt.addActionListener(whateverActions.action, () => {
  alt.takeSnapshot()
})
```

**Comment by irium** [comment]
I've seen that branch `listen-to-actions`. But that's not a solution, because it uses internally `dispatcher.register(...)` and this doesn't guarantee calling order of listeners - such listener is just one more between others.

You solution with `SnapshotStore` looks interesting, but bug-prone - I have to remember to include every new store there.

For now, I'm using something like this:
```
class Flux extends Alt {

    constructor() {
        super();
        this.dispatcher.dispatch = _.wrap(this.dispatcher.dispatch, (dispatch, payload) => {
            dispatch.call(this.dispatcher, payload);
            this.onAction(payload);
        });

        this.storage = new Storage('state');
    }

    onAction(payload) {
        var state = this.takeSnapshot();
        this.storage.writeRaw(state);
    }
}
```

But this feels somewhat hacky, henсe my proposal.

**Comment by goatslacker** [comment]
Ah, I see what you're looking for. I also wish I had the same thing, essentially a "done" handler for when all dispatches have been completed.

This needs to be provided by flux's dispatcher.

For now your workaround, although hacky, is fine.

**Comment by goatslacker** [comment]
A similar discussion: https://github.com/facebook/flux/issues/138#issuecomment-72803318

**Comment by goatslacker** [comment]
I went ahead and added a helper function for the `SnapshotStore` discussed above. You mentioned you didn't want to keep track of including every store in there so I made sure it's automatically done.

The commit is here: c104fb73eedd61f4c1dbd4ac074ce8a2f4b818bf

Usage is:

```js
var makeFinalStore = require('alt/utils/makeFinalStore');
var FinalStore = makeFinalStore(yourAltInstance)

FinalStore.listen(function () {
  console.log('All dispatches have been completed')
})
```
