### ISSUE TITLE
Cannot dispatch in the middle of a dispatch

### ISSUE THREAD

**Issue by jongbeau** [goatslacker/alt#71]
From a Login react component, I have a login action that makes an API request and on successful response, it updates a SessionStore. The Login component sees the value of the session store updated through it's props passed down from the parent component, and in shouldComponentUpdate, it does a transitionTo (using react-router) to an account page. The account page then calls an action to update the SessionStore in ComponentWillMount.

I'm getting this error message:
Uncaught Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.

I believe it's due to the account page trying to update the SessionStore as the result of the SessionStore just getting updated from a previous action. Any suggestions on how to architect this differently?

NOTE: things work when using react-router's HashLocation, but not with the HistoryLocation.

**Comment by goatslacker** [comment]
If you can, move the action out of the store listener's path. I've seen this happen with transitionTo often, it's probably not a good idea to transitionTo immediately in a store listener. Try setting the transitionTo in a setTimeout/setImmediate so it happens on next tick.

**Comment by mshick** [comment]
I've dealt with similar problems using Flux & react-router together. Building off of this document [React Router in a Flux App](https://github.com/rackt/react-router/blob/master/docs/guides/flux.md), and ideas similar to @goatslacker I put together a scheme like this [gist](https://gist.github.com/mshick/436a053ea58ca2aa3d3f)

It gives me a consistent interface for invoking the router, and removes the need to think about when a `setTimeout`/`setImmediate` is necessary. After working with it a bit I feel that router state transitions should always happen in a new execution loop since it's a unique type of app activity, occurring in a separate dispatcher.

You'll also see in that gist a mixin I use for sending optional actions on the `willTransitionTo`/`willTransitionFom` static hooks, which can be used to, say, do an async data fetch when transitioning to a new route, or setting flags when leaving a route. This is a little like that `fetchData` method in the react-router async examples.

**Comment by deser** [comment]
Sorry guys but I think that dispatcher should query and fire in turn actions if they are fired simultaneously. Am I right? If so could you please improve dispatcher of alt. Thanks.

**Comment by troutowicz** [comment]
The dispatcher handles actions synchronously. If an action is fired inside another action's context, the dispatcher will throw an error. As others have said before, if you cannot move the nested action elsewhere, use setTimeout to fire the nested action in a new context.

FYI, there is no need to open new Issues just to bump another.

**Comment by deser** [comment]
Guys from facebook say that this solution not bad: https://monosnap.com/image/VfYSlclKucvgSkudGJnliEkn19upZu

P.S. setTimeout is not silver bulletin. I can't use setTimeout elsewhere

**Comment by deser** [comment]
By the way sorry for opening new issue

**Comment by troutowicz** [comment]
Apologies, I thought you were the OP of this issue. In your scenario, an action queue would be a good approach. But that would not be part of the dispatcher, the dispatcher will always handle one action at a time. It could possibly be made into a util for alt though.

Like fisherwebdev wrote, before firing the actions for each query result, check the dispatcher's `isDispatching`. If the dispatcher is free, fire the next action. :)

**Comment by deser** [comment]
:) I think in this case code will be a little unreadable.
Can you provide me some details in which way I can modify alt dispatcher?
Thanks

**Comment by goatslacker** [comment]
Do you have anything in mind in terms of implementation details? 

My opinion on the matter: in lieu of implementing a custom dispatcher I defer over to Facebook's dispatcher, if they implement a queue then Alt will have it.

**Comment by deser** [comment]
Yep, in flux i've made such dispatcher: 
https://monosnap.com/image/XM8PJLB9nsHtfNCYbAjv2HjfpIilh2

**Comment by jdlehman** [comment]
Cool.  You can also effectively do the same thing with `MyActions.someAction.defer()` in alt, which boils down to wrapping the action in a setTimeout like your dispatcher implementation.

**Comment by deser** [comment]
Your solution is not always suitable because in some cases I need this action to be deffered in some cases I don't need. That's why i've made processing of such situations centralized in dispatcher.

**Comment by jdlehman** [comment]
Well right, you don't always use defer. You just need it if you call an action inside of another action.

**Comment by deser** [comment]
And exactly this situation is complex to catch :). One action can be triggered from view1 another from view2.

**Comment by goatslacker** [comment]
:+1:

**Comment by mhuggins** [comment]
@deser Thanks for sharing!  Small FYI, it looks like in newer versions of the Flux dispatcher, you can instead just call `this.isDispatching()` instead of `this.$Dispatcher._isDispatching`. :smile:

**Comment by marklevi** [comment]
Thanks, the setTimeout worked for transitions.

**Comment by aksonov** [comment]
So is usage of setTimeout OK? Or maybe is it wrong "Flux" way when i do "login" fetch action to do login, then get success result, change login store, and then react component calls action to go to next screen?

**Comment by mull** [comment]
@aksonov setTimeout (or deferring) is generally not desirable but sometimes unavoidable. I follow the _"try not to use it"_ approach. ;)

**Comment by aksonov** [comment]
So what is correct way for typical login scenario?

Pavel.

**Comment by mull** [comment]
@aksonov this is one of the times I use defer/setTimeout.

**Comment by mib32** [comment]
What would you recommend to do in my case:
PhotoUploader component is mounting within the dispatching of some higher level action. I want to alter the PhotoUploaderStore state (clear it, so uploader would display no image) during `componentWillMount` of PhotoUploader. And it throws `cannot dispatch in a middle of dispatch`.

How could i avoid deferring in that case? 

Sorry if such a question is inappropriate here.

**Comment by goatslacker** [comment]
On photouploaderstore listen to that higher level action that mounts all the things and then clear the store then. 

Actions can do various things they don't have to be 1:1.

**Comment by mib32** [comment]
@goatslacker thanks Josh.

**Comment by jamesfzhang** [comment]
What's an appropriate timeout to set, 50ms? 100ms? I imagine it must get affected by system resources?

**Comment by jdlehman** [comment]
@jamesfzhang You can set it with 0ms. All you want is for it to be in the next event loop.

**Comment by jamesfzhang** [comment]
Thanks @jdlehman

**Comment by mib32** [comment]
@goatslacker What if I want to make a chain of actions, in a waterfall way?

- I can't use promises in the component because it breaks flux
- I don't want to get into a defer trap

**Comment by CrazyPython** [comment]
@mib32 I'm not exactly sure what your case is, please clarify.
