### ISSUE TITLE
ES5 Examples

### ISSUE THREAD

**Issue by quangv** [goatslacker/alt#73]
Hey there,

I am interested in using alt for my current project and at the same time have decided to not use ES6, are there any ES5 examples of using Alt?

Thanks.

**Comment by goatslacker** [comment]
There are examples scattered about everywhere but not in a single place in particular.

You can use regular old constructors and prototypes:

```
function TodoStore() {
  this.todos = {};

  this.bindListeners({
    handleAddTodo: TodoActions.ADD_TODO
  });
}

TodoStore.prototype.handleAddTodo = function (todo) {
  var id = todo.id;
  this.todos[id] = todo;
};

var todoStore = alt.createStore(TodoStore);
```

**Comment by goatslacker** [comment]
Question: would you prefer to use plain old javascript objects to define stores? You can use the ES3 module pattern with this approach:

(not in master yet)

https://github.com/goatslacker/alt/blob/a-fun-experiment/test/es3-module-pattern.js#L11

**Comment by quangv** [comment]
Hey @goatslacker,

Thanks for the reply, I can use it as reference for the other examples in the Readme.

I am using coffee-script + CommonJS/Browserify
