### ISSUE TITLE
Changing stores with react-hot-loader

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#85]
When making changes to a store don't create a new store.

**Comment by zfogg** [comment]
+1

**Comment by goatslacker** [comment]
Note to self: look into module.hot, maybe this is better served by an addon.

**Comment by goatslacker** [comment]
66c875ca5b90955f6a4df1f6d705ab87fc805673

API:

```js
import makeHot from 'alt/utils/makeHot';

class TodoStore {
  constructor() {
    this.todos = {};
  }
}

export default makeHot(alt, TodoStore, 'TodoStore');
```

**Comment by ami44** [comment]
:+1:

**Comment by koistya** [comment]
Nice

**Comment by maciejmyslinski** [comment]
Don't know why, but didn't work for me with Rails.
But, I've done it simply by:
```javascript
delete alt.stores['TodoStore'];
export default alt.createStore(NewPageStore, 'TodoStore');
```

**Comment by goatslacker** [comment]
If you're using alt@0.17.2 it just works now: https://github.com/goatslacker/alt/blob/master/src/alt/index.js#L54
