### ISSUE TITLE
ClassName duplication after uglify

### ISSUE THREAD

**Issue by quangbuule** [goatslacker/alt#91]
ReferenceError: A store named e already exists, double check your store names or pass in your own custom identifier for each store {stack: (...), message: "A store named e already exists, double check your …pass in your own custom identifier for each store"}

To fix this, we have to pass the `iden` when create Store:

```js
alt.createStore(Store, iden);
```

**Comment by goatslacker** [comment]
Yes, you can pass in the identifier or choose to turn off snapshots for that particular store.
