### ISSUE TITLE
Move utils out to separate repo?

### ISSUE THREAD

**Issue by goatslacker** [goatslacker/alt#98]
Maybe we should move each individual util out to its own separate repo that way it can be versioned accordingly?

This may make sense for larger utils but not so much for smaller ones. I'm thinking we do the same for components.

Thoughts?

I sort of like having everything in one repo so I'm a bit hesitant, the versioning is the only pro we really gain.

**Comment by jdlehman** [comment]
This isnt a bad idea.  I think there is something nice about everything being in one place (easier to find etc), but moving utils/components out might also help encourage more people to develop their own alt utils.  Do you see alt bringing in these utils/components as dependencies that it also exports, or do you see users needing to bring these deps into their projects explicitly?  It seems like it might be a bit excessive to have each util/component in its own repo, so a third option to discuss would be a components repo and a utils repo.

Another alternative would be to better export these "addons" as named exports:
```js
import alt from '../src/alt';
import manager from '../utlis/AltManager';

export default alt;
export const AltManager = manager;
```

usage
```js
import alt, {AltManager}, {AnotherUtil}, {Util3} from 'alt';
```

**Comment by goatslacker** [comment]
I don't want to have them as named exports because then the code bundle size increases. Having them part of addons is ok right now. But yeah, maybe we should selectively move some utils out to separate repos?

**Comment by jdlehman** [comment]
That makes sense.  The question is, which ones do we move out?  If we only move out some will it be hard for people to find the utils they need?  Obviously we would need to add a list of the official ones somewhere.

**Comment by goatslacker** [comment]
I think if this is premature, we can think about moving them out later :)
